<div class="header header-filter" style="background-image: url('/img/bg-recep-ori.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="brand">
                    <h1>Volley-ball.eu</h1>
                    <h3>Gestion de groupes, entrainements, matchs.</h3>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="main main-raised">
    <div class="section section-basic">
        <div class="container">
            <div class="title">
                <h2><?= $group->name ?>: Vos adresses</h2>
            </div>

            <div class="row">
                <table class="table table-striped table-hover">
                    <tr>
                        <th>Lieu</th>
                        <th>Adresse</th>
                        <th>Action</th>
                    </tr>
                    <?php foreach ($places as $place): ?>
                        <tr>
                            <td><?= $place->name ?></td>
                            <td><?= $place->getFullAddress() ?></td>
                            <td></td>
                        </tr>
                    <?php endforeach ?>
                </table>
            </div>
        </div>
    </div>
</div>
