<div class="col-md-4 col-sm-6">
    <div class="card-container">
        <div class="card">
            <div class="front">
                <div class="cover">
                    <img src="img/rotating_card_thumb2.png"/>
                </div>
                <div class="user card text-center">
                    <div class="agenda">
                            <div class="agenda-header">
                                <b>Novembre</b>
                            </div>
                            <div class="agenda-content">
                                <p>Jeudi</p>
                                <p class="day">25<p>
                            </div>
                    </div>
                </div>
                <div class="content">
                    <div class="main">
                        <h3 class="name">Entrainement Mardi</h3>
                        <p class="profession">Dunois REM</p>
                        <p class="text-center">Le RDV est à <b>20h00</b></p>
                        <p class="text-center">
                            Au gymnase Maurice Bacquet<br/>
                            70 rue de Dunois <br/>
                            75013 Paris
                        </p>
                    </div>
                    <div class="footer">
                        <i class="fa fa-mail-forward"></i> Auto Rotation
                    </div>
                </div>
            </div> <!-- end front panel -->
            <div class="back">
                <div class="header header-success">
                    <h5 class="motto">Vous êtes noté <b>présent</b> à cet évènement</h5>
                </div>
                <div class="content">
                    <div class="main">
                        <h3 class="name">Entrainement Mardi</h3>
                        <p class="profession">Dunois REM</p>
                        <p class="text-center"><a href="https://www.google.fr/maps/search/70+rue+de+Dunois+75013+Paris"><i class="material-icons">place</i>Afficher la carte dans google maps</a></p>

                        <div class="stats-container">
                            <div class="stats">
                                <h4>15</h4>
                                <a href="#" class="btn-tooltip btn btn-success btn-round btn-xs" data-toggle="tooltip" data-placement="top" data-html="true" title="Répondre <b>présent</b> à l'évènement">
                                    Présent
                                </a>
                            </div>
                            <div class="stats">
                                <h4>5</h4>
                                <a href="#" class="btn-tooltip btn btn-danger btn-round btn-xs" data-toggle="tooltip" data-placement="top" data-html="true" title="Répondre <b>Absent</b> à l'évènement">
                                    Absent
                                </a>
                            </div>
                            <div class="stats">
                                <h4>2</h4>
                                <a href="#" class="btn-tooltip btn btn-warning btn-round btn-xs" data-toggle="tooltip" data-placement="top" data-html="true" title="Répondre <b>à confirmer</b> à l'évènement">
                                    Attente
                                </a>
                            </div>
                        </div>

                    </div>
                </div>
                <div>
                    <div class="text-center">
                        <a href="event/detail/1">Voir les Détails</a>
                    </div>
                </div>
            </div> <!-- end back panel -->
        </div> <!-- end card -->
    </div> <!-- end card-container -->
</div> <!-- end col sm 3 -->