<?php if ($this->menu): ?>
    <div class="fixed-action-btn click-to-toggle" style="bottom: 45px; right: 24px;">
        <a class="btn-floating btn-large red">
            <i class="material-icons md-48">add</i>
        </a>

        <ul>
            <?php foreach ($this->menu as $row): ?>
                <li>
                    <a class="btn-floating <?= $row['color'] ?> btn-tooltip" data-toggle="tooltip" data-placement="left" title="<?= $row['tooltip'] ?>" href="<?= $row['link'] ?>">
                        <i class="material-icons submenu"><?= $row['icon'] ?></i>
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
<?php endif ?>