<?php
	$class = "";
    switch ($guest->response) {
        case Application\Model\Guest::RESP_OK:
            $class = 'header-success';
            break;
        case Application\Model\Guest::RESP_NO:
            $class = 'header-danger';
            break;
        case Application\Model\Guest::RESP_INCERTAIN:
            $class = 'header-warning';
            break;
    }
?>
<div class="col-md-4">
    <div class="card card-nav-tabs card-small-header" style="min-height:180px">
        <div class="header <?= $class ?>">
            <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->
            <div class="nav-tabs-navigation">
                <div class="nav-tabs-wrapper">
                    <ul class="nav nav-tabs" data-tabs="tabs">
                        <li class="active">
                            <a href="#profile-<?= $event->id ?>" data-toggle="tab">
                                <i class="material-icons">access_time</i>
                            </a>
                        </li>
                        <li>
                            <a href="#messages-<?= $event->id ?>" data-toggle="tab">
                                <i class="material-icons">done</i>
                            </a>
                        </li>
                        <li>
                            <a href="#settings-<?= $event->id ?>" data-toggle="tab">
                                <i class="material-icons">location_on</i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="tab-content text-center">
                <div class="tab-pane active" id="profile-<?= $event->id ?>">
                    <div class="text-center col-xs-5">
                        <div class="agenda">
                            <div class="agenda-content">
                                <p><?= \Application\Service\Date::toFr($date->format("l")) ?></p>
                                <p class="day"><?= $date->format("d") ?><p>
                                <?= \Application\Service\Date::toFr($date->format("F")) ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-7">
                        <h3 class="name"><?= $event->name ?></h3>
                        <p class="profession">
                            <i class="fa fa-users"></i> <?= $group->name ?><br>
                            <i class="fa fa-clock-o"></i> <?= $date->format("H\hs") ?>
                        </p>
                    </div>
                </div>
                <div class="tab-pane text-center" id="messages-<?= $event->id ?>">
                    <h3 class="name">Disponibilité</h3>
                    <div class="col-xs-6">
                        <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_OK ?>" class="text-success"><i class="material-icons large">event_available</i>
                        </a>
                    </div>
                    <div class="col-xs-6">
                        <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_NO ?>" class="text-danger"><i class="material-icons large">event_busy</i>
                        </a>
                    </div>
                    <div class="col-xs-6">
                        <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_INCERTAIN ?>" class="text-warning"><i class="material-icons large">date_range</i>
                        </a>
                    </div>
                    <div class="col-xs-6">
                        <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_INCERTAIN ?>" class="text-warning"><i class="material-icons large">date_range</i>
                        </a>
                    </div>
                </div>
                <div class="tab-pane" id="settings-<?= $event->id ?>">
                    <p class="text-center">
                        <b><?= $event->place ?></b><br/>
                        <?= $event->address ?><br/>
                        <?= $event->zipCode ?>, <?= $event->city ?>
                    </p>
                    <p class="text-center"><a href="https://www.google.fr/maps/search/70+rue+de+Dunois+75013+Paris"><i class="material-icons">place</i>Afficher la carte dans google maps</a></p>
                </div>
            </div>
        </div>
    </div>
</div>