<?php
    switch ($guest->response) {
        case Application\Model\Guest::RESP_OK:
            $class = 'header-success';
            break;
        case Application\Model\Guest::RESP_NO:
            $class = 'header-danger';
            break;
        case Application\Model\Guest::RESP_INCERTAIN:
            $class = 'header-warning';
            break;
        default:
            $class = 'header-primary';
            break;
    }
?>
<div class="col-sm-12 col-md-6 col-lg-4">
    <div class="card card-nav-tabs card-small-header" style="min-height:180px">
        <div class="header <?= $class ?>">
            <div class="nav-tabs-navigation">
                <div class="nav-tabs-wrapper">
                    <ul class="nav nav-tabs" data-tabs="tabs">
                        <li class="active">
                            <a href="#profile-<?= $event->id ?>" data-toggle="tab">
                                <i class="material-icons">access_time</i>
                            </a>
                        </li>
                        <li>
                            <a href="#messages-<?= $event->id ?>" data-toggle="tab">
                                <i class="material-icons">done</i>
                            </a>
                        </li>
                        <li>
                            <a href="#settings-<?= $event->id ?>" data-toggle="tab">
                                <i class="material-icons">location_on</i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="tab-content text-center">
                <div class="tab-pane active" id="profile-<?= $event->id ?>">
                    <div class="text-center col-xs-5">
                        <div class="agenda">
                            <a href="/event/detail/<?= $event->id?>" class="event-list-date">
                                <div class="agenda-content">
                                        <p><?= \Application\Service\Date::toFr($date->format("l")) ?></p>
                                        <p class="day"><?= $date->format("d") ?><p>
                                        <?= \Application\Service\Date::toFr($date->format("F")) ?>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-xs-7">
                        <h3 class="name">
                            <?= $event->name ?>
                        </h3>
                        <p class="profession">
                            <i class="fa fa-users"></i> <?= $group->name ?><br>
                            <i class="fa fa-clock-o"></i> <?= $date->format("H\hs") ?>
                        </p>
                    </div>
                </div>
                <div class="tab-pane text-center" id="messages-<?= $event->id ?>">
                    <div class="col-xs-6">
                        <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_OK ?>" 
                           class="text-success response" 
                           data-event="<?= $event->id ?>" 
                           data-response="<?= Application\Model\Guest::RESP_OK ?>">
                                <i class="material-icons large">event_available</i>
                        </a>
                    </div>
                    <div class="col-xs-6">
                        <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_NO ?>"
                           class="text-danger response"
                           data-event="<?= $event->id ?>" 
                           data-response="<?= Application\Model\Guest::RESP_NO ?>">
                                <i class="material-icons large">event_busy</i>
                        </a>
                    </div>
                    <div class="col-xs-6" style="margin-top: 10px;">
                        <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_INCERTAIN ?>"
                           class="text-warning response"
                           data-event="<?= $event->id ?>" 
                           data-response="<?= Application\Model\Guest::RESP_INCERTAIN ?>">
                                <i class="material-icons large">date_range</i>
                        </a>
                    </div>
                    <div class="col-xs-6" style="margin-top: 10px;">
                        <a href="/guest/detail/<?= $event->id ?>" class="text-info"><i class="material-icons large">search</i>
                        </a>
                    </div>
                </div>
                <div class="tab-pane" id="settings-<?= $event->id ?>">
                    <div class="col-xs-12">
                        <h3 class="name"><?= $event->place ?></h3>
                        <p class="profession">
                            <?= $event->address ?><br/>
                            <?= $event->zipCode ?>, <?= $event->city ?><br>
                        </p>
                            <a href="https://www.google.fr/maps/search/70+rue+de+Dunois+75013+Paris"><i class="material-icons">place</i>Google Maps</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>