<?php
	$class = "";
    switch ($guest->response) {
        case Application\Model\Guest::RESP_OK:
            $class = 'text-success';
            break;
        case Application\Model\Guest::RESP_NO:
            $class = 'text-danger';
            break;
        case Application\Model\Guest::RESP_INCERTAIN:
            $class = 'text-warning';
            break;
    }
?>

<div class="row debrief">
    <div class="col-md-12">
        <div class="card">
            <div class="col-md-12">
                <div class="content" style="padding:20px 0;">
                    <div class="main">
                        <div class="owl-carousel-3 owl-theme">
                            <div class="text-center item">
                                    <div class="col-xs-5" style="padding:0;">
                                        <div class="card">
                                            <div class="agenda">
                                                <div class="agenda-header">
                                                    <b><?= \Application\Service\Date::toFr($date->format("F")) ?></b>
                                                </div>
                                                <div class="agenda-content">
                                                    <p><?= \Application\Service\Date::toFr($date->format("l")) ?></p>
                                                    <p class="day"><?= $date->format("d") ?><p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-7" style="min-height:120px;">
                                        <h3 class="name <?= $class ?>"><?= $event->name ?></h3>
                                        <p class="profession">
                                            <i class="fa fa-users"></i> <?= $group->name ?><br>
                                            <i class="fa fa-clock-o"></i> <?= $date->format("H\hs") ?>
                                        </p>
                                    </div>
                            </div>
                            <div class="text-center item">
                                <h3 class="name">Disponibilité</h3>
                                <div class="col-xs-4">
                                    <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_OK ?>" class="text-success"><i class="material-icons large">event_available</i>
                                    </a>
                                </div>
                                <div class="col-xs-4">
                                    <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_NO ?>" class="text-danger"><i class="material-icons large">event_busy</i>
                                    </a>
                                </div>
                                <div class="col-xs-4">
                                    <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_INCERTAIN ?>" class="text-warning"><i class="material-icons large">date_range</i>
                                    </a>
                                </div>
                            </div>
                            <div class="text-center item">
                                <p class="text-center">
                                    <b><?= $event->place ?></b><br/>
                                    <?= $event->address ?><br/>
                                    <?= $event->zipCode ?>, <?= $event->city ?>
                                </p>
                                <p class="text-center"><a href="https://www.google.fr/maps/search/70+rue+de+Dunois+75013+Paris"><i class="material-icons">place</i>Afficher la carte dans google maps</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>