<div class="sidebar-wrapper">
    <div class="user">
        <div class="info">
            <div class="photo">
                <img src="/img/default-avatar.png" />
            </div>

            <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                <span>
                    <?= (isset($user) && $user) ? $user->getFullName() : ''; ?>
                    <b class="caret"></b>
                </span>
            </a>
            <div class="clearfix"></div>

            <div class="collapse" id="collapseExample">
                <ul class="nav">
                    <li>
                        <a href="/user/params">
                            <span class="sidebar-mini">Mp</span>
                            <span class="sidebar-normal">Mon Profil</span>
                        </a>
                    </li>
                    <li>
                        <a href="/holiday/create">
                            <span class="sidebar-mini">Va</span>
                            <span class="sidebar-normal">Vacances</span>
                        </a>
                    </li>
                    <li>
                        <a href="/auth/signout">
                            <span class="sidebar-mini">Dé</span>
                            <span class="sidebar-normal">Déconnexion</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <ul class="nav">
        <li>
            <a data-toggle="collapse" href="#groups">
                <i class="ti-clipboard"></i>
                <p> Mes Groupes
                    <b class="caret"></b>
                </p>
            </a>
            <div class="collapse" id="groups">
                <ul class="nav">
                    <?php if ($this->groups): ?>
                        <?php foreach ($this->groups as $group): ?>
                            <li>
                                <a href="<?= $group->getPublicLink() ?>">
                                    <span class="sidebar-mini"><?= substr($group->name, 0, 2) ?></span>
                                    <span class="sidebar-normal"><?= $group->name ?></span>
                                </a>
                            </li>
                        <?php endforeach ?>
                    <?php else: ?>
                        <li>
                            <a href="/group/create">
                               <i class="material-icons">group_add</i> Créer un groupe
                            </a>
                        </li>
                    <?php endif ?>
                </ul>
            </div>
        </li>
    </ul>
    <ul class="nav">
        <li>
            <a href="/group/create">
                <i class="ti-plus"></i>
                <p> Créer un Groupe
                </p>
            </a>
        </li>
    </ul>
</div>