<div class="sidebar-wrapper">
    <div class="user">
        <div class="info">
            <div class="photo">
                <img src="/img/default-avatar.png" />
            </div>
            <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                <span>
                    <?= (isset($user) && $user) ? $user->getFullName() : ''; ?>
                    <b class="caret"></b>
                </span>
            </a>
            <div class="clearfix"></div>

            <div class="collapse" id="collapseExample">
                <ul class="nav">
                    <li>
                        <a href="/user/params">
                            <span class="sidebar-mini">Mp</span>
                            <span class="sidebar-normal">Mon Profil</span>
                        </a>
                    </li>
                    <li>
                        <a href="/holiday/create">
                            <span class="sidebar-mini">Ab</span>
                            <span class="sidebar-normal">Absences</span>
                        </a>
                    </li>
                    <li>
                        <a href="/auth/signout">
                            <span class="sidebar-mini">Dé</span>
                            <span class="sidebar-normal">Déconnexion</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <ul class="nav">
        <li>
            <a href="/group/create">
                <i class="ti-plus"></i>
                <p> Créer un Groupe
                </p>
            </a>
        </li>
    </ul>
    <?php if ($this->groups): ?>
        <ul class="nav">
            <?php foreach ($this->groups as $group): ?>
                <li>
                    <a href="<?= $group->getPublicLink() ?>">
                        <i><?= substr($group->name, 0, 2) ?></i>
                        <p><?= $group->name ?></p>
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
    <?php endif ?>
</div>