<!-- Sart login Modal -->
<div class="modal fade" id="modale-signin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="row">
                <div class="card card-signup">
                    <?php  $signInForm->setAttribute('action', $this->url('auth', ['action' => 'signin'])); ?>
                    <?= $this->form()->openTag($signInForm); ?>
                        <div class="header header-primary text-center">
                            <h4>Se connecter</h4>
                        </div>
                        <div class="content">
                            <div class="form-group label-floating is-empty">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">email</i>
                                    </span>
                                    <label class="control-label" for="email">
                                        E-mail
                                    </label>
                                    <?= $this->formElement($signInForm->get('email')); ?>
                                </div>
                            </div>
                            <div class="form-group label-floating is-empty">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">lock_outline</i>
                                    </span>
                                    <label class="control-label" for="password">
                                        Mot de passe
                                    </label>
                                    <?= $this->formElement($signInForm->get('password')); ?>
                                </div>
                            </div>
                        </div>
                    <?= $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
</div>