<!-- Sart Signin Modal -->
<div class="modal fade" id="modale-signup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="row">
                <div class="card card-signup">
                    <?php  $signUpForm->setAttribute('action', $this->url('auth', ['action' => 'signup'])); ?>
                    <?php echo $this->form()->openTag($signUpForm); ?>
                        <div class="header header-primary text-center">
                            <h4>Créer un compte</h4>
                        </div>
                        <div class="content">

                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">fingerprint</i>
                                </span>
                                <?php echo $this->formElement($signUpForm->get('firstname')); ?>
                            </div>

                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">face</i>
                                </span>
                                <?php echo $this->formElement($signUpForm->get('lastname')); ?>
                            </div>

                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">email</i>
                                </span>
                                <?php echo $this->formElement($signUpForm->get('email')); ?>
                            </div>

                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">lock_outline</i>
                                </span>
                                <?php echo $this->formElement($signUpForm->get('password')); ?>
                            </div>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">lock_outline</i>
                                </span>
                                <?php echo $this->formElement($signUpForm->get('repassword')); ?>
                            </div>
                        </div>
                        <div class="footer text-center">
                            <?php echo $this->formElement($signUpForm->get('submit')); ?>
                        </div>
                    <?php echo $this->form()->closeTag(); ?>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>