<?php 
    switch ($guest->response) {
        case Application\Model\Guest::RESP_OK:
            $class = 'header-success';
            $txt = 'text-success';
            break;
        case Application\Model\Guest::RESP_NO:
            $class = 'header-danger';
            $txt = 'text-danger';
            break;
        case Application\Model\Guest::RESP_INCERTAIN:
            $class = 'header-warning';
            $txt = 'text-warning';
            break;
        
        default:
            $class = 'header-primary';
            $txt = '';
            break;
    }
?>
<div class="col-md-4 col-sm-6 event-card" data-brand="<?= $group->brand ?>">
    <div class="card-container">
        <div class="card">
            <div class="front">
                <div class="cover">
                    <img src="/img/rotating_card_thumb2.png"/>
                </div>
                <div class="user card text-center">
                    <div class="agenda">
                        <div class="agenda-header">
                            <b><?= \Application\Service\Date::toFr($date->format("F")) ?></b>
                        </div>
                        <div class="agenda-content">
                            <p><?= \Application\Service\Date::toFr($date->format("l")) ?></p>
                            <p class="day"><?= $date->format("d") ?><p>
                        </div>
                    </div>
                </div>
                <div class="content">
                    <div class="main">
                        <h3 id="title-<?= $event->id ?>" class="name <?= $txt ?>"><?= $event->name ?></h3>
                        <p class="profession"><?= $group->name ?></p>
                        <p class="text-center">Le RDV est à <b><?= $date->format("H\hi") ?></b></p>
                        <p class="text-center">
                            <?= $event->place ?><br/>
                            <?= $event->address ?><br/>
                            <?= $event->zipCode ?>, <?= $event->city ?>
                        </p>
                    </div>
                    <div class="footer visible-xs visible-sm">
                        <button class="btn btn-simple" onclick="rotateCard(this)">
                            <i class="fa fa-mail-forward"></i> Rotation
                        </button>
                    </div>
                </div>
            </div> <!-- end front panel -->
            <div class="back">
                <div id="header-<?= $event->id ?>" class="header <?= $class ?>">
                    <h5 class="motto">Vous êtes noté <b id="presence-<?= $event->id ?>"><?= Application\Model\Guest::$literalDisponbility[$guest->response] ?></b> à cet évènement</h5>
                </div>
                <div class="content">
                    <div class="main">
                        <h3 class="name"><?= $event->name ?></h3>
                        <p class="profession"><?= $group->name ?></p>
                        <p class="text-center">
                            <a href="/event/detail/<?= $event->id ?>"> <i class="material-icons">search</i>Voir les Détails</a>
                        </p>
                        <div class="stats-container">
                            <div class="stats">
                                <h4 id="resp-<?= $event->id ?>-<?= Application\Model\Guest::RESP_OK ?>"><?= $ok ?></h4>
                                <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_OK ?>" 
                                   class="text-success response" 
                                   data-event="<?= $event->id ?>" 
                                   data-response="<?= Application\Model\Guest::RESP_OK ?>">
                                        Présent
                                </a>
                            </div>
                            <div class="stats">
                                <h4 id="resp-<?= $event->id ?>-<?= Application\Model\Guest::RESP_NO ?>"><?= $no ?></h4>
                                <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_NO ?>"
                                   class="text-danger response"
                                   data-event="<?= $event->id ?>" 
                                   data-response="<?= Application\Model\Guest::RESP_NO ?>">
                                        Absent
                                </a>
                            </div>
                            <div class="stats">
                                <h4 id="resp-<?= $event->id ?>-<?= Application\Model\Guest::RESP_INCERTAIN ?>"><?= $perhaps ?></h4>
                                <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_INCERTAIN ?>"
                                   class="text-warning response"
                                   data-event="<?= $event->id ?>" 
                                   data-response="<?= Application\Model\Guest::RESP_INCERTAIN ?>">
                                        Incertain
                                </a>
                            </div>
                        </div>

                    </div>
                    <div class="text-center">
                        <a href="https://www.google.fr/maps/search/<?= urlencode($event->getFullAddress()) ?>"><i class="material-icons">place</i>Google Maps</a>
                    </div>
                    <div class="footer visible-xs visible-sm">
                        <button class="btn btn-simple" onclick="rotateCard(this)">
                            <i class="fa fa-mail-forward"></i> Retour
                        </button>
                    </div>
                </div>
            </div> <!-- end back panel -->
        </div> <!-- end card -->
    </div> <!-- end card-container -->
</div> <!-- end col sm 3 -->