<?php
    switch ($guest->response) {
        case Application\Model\Guest::RESP_OK:
            $class = 'success';
            break;
        case Application\Model\Guest::RESP_NO:
            $class = 'danger';
            break;
        case Application\Model\Guest::RESP_INCERTAIN:
            $class = 'warning';
            break;
        default:
            $class = 'primary';
            break;
    }
?>

<tr class="text-left <?= $class ?>">
    <td><?= $event->name ?></td>
    <td><?= $group->name ?></td>
    <td><?= \Application\Service\Date::toFr($date->format('l d F Y')) ?></td>
    <td>
        <a href="/event/detail/<?= $event->id ?>" data-eventId="<?= $event->id?>" class="badge-comment">
            <i class="material-icons">search</i>
        </a>
    </td>
</tr>