<div class="header header-filter" style="background-image: url('/img/bg-recep-ori.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="brand">
                    <h1>Volley-ball.eu</h1>
                    <h3>Gestion de groupes, entrainements, matchs.</h3>
                </div>
            </div>
        </div>

    </div>
</div>

<?php if (isset($form)): ?>
    <div class="main main-raised">
        <div class="section section-basic">
            <div class="container">
                <div class="title">
                    <h2><b><?= $group->name ?></b> - Nouvelle Adresse</h2>
                </div>

                <div class="row">
                    <?php echo $this->form()->openTag($form); ?>

                    <div class="col-md-12">
                        <div class="form-group label-floating is-empty">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">account_balance</i>
                                </span>
                                <label class="control-label" for="name">
                                    Nom de l'évènement
                                </label>
                                <?php echo $this->formInput($form->get('name')); ?>
                            </div>
                        </div>

                        <div class="form-group label-floating is-empty">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">local_post_office</i>
                                </span>
                                <label class="control-label" for="date">
                                    Date
                                </label>
                                <?php echo $this->formInput($form->get('date')); ?>
                            </div>
                        </div>

                        <div class="form-group label-floating is-empty">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">language</i>
                                </span>
                                <label class="control-label" for="comment">
                                    Commentaire
                                </label>
                                <?php echo $this->formInput($form->get('comment')); ?>
                            </div>
                        </div>

                        <div class="title">
                            <h5>Adresse</h5>
                        </div>
                        L'adresse n'est pas dans la liste ? <a href="/place/create/<?= $group->id ?>">Créez en une</a>

                        <?php foreach ($places as $id => $address): ?>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="address" value="<?= $id ?>">
                                    <?= $address ?>
                                </label>
                            </div>
                        <?php endforeach ?>

                    </div>

                    <div class="col-md-12 footer text-center">
                        <?php echo $this->formElement($form->get('submit')); ?>
                    </div>

                    <?php echo $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
<?php endif ?>
