<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="card card-wizard wow fadeInUp" id="wizardCard">
            <?= $this->form()->openTag($form); ?>
                <div class="card-header text-center">
                    <h4 class="card-title">Création d'évènement</h4>
                    <p class="category">Créer un évènement pour ce groupe.</p>
                </div>
                <div class="card-content">
                    <ul class="nav">
                        <li><a href="#tab1" data-toggle="tab">Détails</a></li>
                        <li><a href="#tab2" data-toggle="tab">Adresse</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane" id="tab1">
                            <h5 class="text-center">Information sur l'évènement</h5>
                            <div class="row">
                                <div class="col-md-10 col-md-offset-1">
                                    <div class="form-group">
                                        <label class="control-label">
                                            Nom de l'évènement<star>*</star>
                                        </label>
                                        <?= $this->formElement($form->get('name')); ?>
                                    </div>
                                </div>
                                <div class="col-md-10 col-md-offset-1">
                                    <div class="form-group">
                                        <label class="control-label">
                                            Date<star>*</star>
                                        </label>
                                        <?= $this->formElement($form->get('date')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-10 col-md-offset-1">
                                    <div class="form-group">
                                        <label class="control-label">
                                            Commentaire
                                        </label>
                                        <?= $this->formElement($form->get('comment')); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane" id="tab2">
                            <h5 class="text-center">Adresse de l'évènement</h5>
                            <div class="row">
                                <div class="col-md-10 col-md-offset-1">
                                    <div class="form-group">
                                        <label class="control-label">Nom du gymnase<star>*</star></label>
                                        <?= $this->formElement($form->get('place')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-10 col-md-offset-1">
                                    <div class="form-group">
                                        <label class="control-label">Adresse de l'évènement<star>*</star></label>
                                        <?= $this->formElement($form->get('address')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-5 col-md-offset-1">
                                    <div class="form-group">
                                        <label class="control-label">Code Postal<star>*</star></label>
                                        <?= $this->formElement($form->get('zipCode')); ?>
                                    </div>
                                </div>
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <label class="control-label">Ville<star>*</star></label>
                                        <?= $this->formElement($form->get('city')); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="button" class="btn btn-default btn-fill btn-wd btn-back pull-left">Back</button>
                    <button type="button" class="btn btn-info btn-fill btn-wd btn-next pull-right">Next</button>
                    <?= $this->formElement($form->get('submit')); ?>
                    <div class="clearfix"></div>
                </div>
            </form>
        </div>
    </div>
</div>