<div id="map" class="header-filter header" data-lat="48.870364" data-long="2.4234589">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="brand">
                    <h1>Volley-ball.eu</h1>
                    <h3>Gestion de groupes, entrainements, matchs.</h3>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="main main-raised">
    <div class="section section-basic">
        <div class="container">
            <div class="title">
                <h2>Basic Elements</h2>
            </div>
        </div>
    </div>
    <div class="container">
        
    </div>

</div>