<div id="map" class="header-map" data-lat="<?= $event->lat ?>" data-long="<?= $event->long ?>">
</div>

<div class="main main-raised">

    <div class="section section-basic">
        <div class="container text-center">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <h2><?= $event->name ?></h2>
                    <?php if ($event->comment): ?>
                        <?= $event->comment ?>
                    <?php else: ?>
                        <h4>Aucune description n'est associée à cet évènement.</h4>
                    <?php endif ?>
                </div>
            </div>
        </div>
    </div>

    <div class="section section-basic">
        <div class="container text-center">
            <div class="row">
                <div class="col-xs-6 col-md-3" style="margin-bottom:20px;">
                    <p class="number" style="font-size:4em;" id="resp-<?= $event->id ?>-<?= Application\Model\Guest::RESP_OK ?>">
                        <?= $counters[Application\Model\Guest::RESP_OK]?>
                    </p>
                    Présents
                </div>
                <div class="col-xs-6 col-md-3" style="margin-bottom:20px;">
                    <p class="number" style="font-size:4em" id="resp-<?= $event->id ?>-<?= Application\Model\Guest::RESP_NO ?>">
                        <?= $counters[Application\Model\Guest::RESP_NO]?>
                    </p>
                    Absents
                </div>
                <div class="col-xs-6 col-md-3" style="margin-bottom:20px;">
                    <p class="number" style="font-size:4em" id="resp-<?= $event->id ?>-<?= Application\Model\Guest::RESP_INCERTAIN ?>">
                        <?= $counters[Application\Model\Guest::RESP_INCERTAIN]?>
                    </p>
                    Incertains
                </div>
                <div class="col-xs-6 col-md-3" style="margin-bottom:20px;">
                    <p class="number" style="font-size:4em"  id="resp-<?= $event->id ?>-<?= Application\Model\Guest::RESP_NO_ANSWER ?>">
                        <?= $counters[Application\Model\Guest::RESP_NO_ANSWER]?>
                    </p>
                    Sans réponse
                </div>
            </div>
        </div>
    </div>

    <div class="section section-signup" style="background-image: url('/img/cover_4_blur.jpg'); background-size: cover; background-position: top center; min-height: 300px;">
        <div class="container">
            <div class="row">
                <?php if (!$match || !$match->set1Team1): ?>
                    <div class="col-md-6 col-md-offset-3">
                <?php else: ?>
                    <div class="col-md-6">
                <?php endif ?>
                        <div class="card card-signup">
                            <div class="header header-primary text-center">
                                <h4>Description</h4>
                            </div>
                            <div class="content">
                                <div class="main">
                                    <h3 class="name"><?= $event->name ?></h3>
                                    <p class="profession"><?= $group->name ?></p>
                                    <h2 class="name"><?= \Application\Service\Date::toFr($date->format('l d F Y')) ?></h2>
                                    <p class="profession">Le RDV est à <b><?= $date->format("H\hi") ?></b></p>
                                    <p class="text-center">
                                        <b><?= $event->place ?></b><br/>
                                        <?= $event->address ?><br/>
                                        <?= $event->zipCode ?>, <?= $event->city ?>
                                    </p>
                                    <p class="text-center"><a href="https://www.google.fr/maps/search/70+rue+de+Dunois+75013+Paris"><i class="material-icons">place</i>Afficher la carte dans google maps</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php if ($match && $match->set1Team1): ?>
                    <div class="col-md-6">
                        <div class="card card-signup">
                            <div class="header header-primary text-center">
                                <h4>Résultats</h4>
                            </div>
                            <div class="col-md-10 col-md-offset-1">
                                <div class="main">
                                    <h3 class="name"><?= $match->victory ? 'Victoire' : 'Défaite'; ?></h3>
                                    <p class="profession"><?= $match->sets ?></p>
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <td>Équipes</td>
                                                <td>Set1</td>
                                                <td>Set2</td>
                                                <td>Set3</td>
                                                <td>Set4</td>
                                                <td>Set5</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td><?= $group->name ?></td>
                                                <td><?= $match->set1Team1 ?></td>
                                                <td><?= $match->set2Team1 ?></td>
                                                <td><?= $match->set3Team1 ?></td>
                                                <td><?= $match->set4Team1 ?></td>
                                                <td><?= $match->set5Team1 ?></td>
                                            </tr>
                                            <tr>
                                                <td>Adv.</td>
                                                <td><?= $match->set1Team2 ?></td>
                                                <td><?= $match->set2Team2 ?></td>
                                                <td><?= $match->set3Team2 ?></td>
                                                <td><?= $match->set4Team2 ?></td>
                                                <td><?= $match->set5Team2 ?></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif ?>
            </div>
            <?php if ($match && $match->debrief): ?>
                <div class="row debrief">
                    <div class="col-md-12">
                        <div class="card card-signup">
                            <div class="header header-primary text-center">
                                <h4>Débrief</h4>
                            </div>
                            <div class="col-md-10 col-md-offset-1">
                                <div class="content">
                                    <div class="main">
                                        <p>
                                            <?= nl2br($match->debrief) ?>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif ?>
        </div>
    </div>

    <div class="section section-basic">
        <div class="container">
            <div class="title text-center">
                <h2>Disponibilités</h2>
            </div>

            <div class="owl-carousel owl-theme">
                <div class="text-center item">
                    <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_OK ?>"
                        class="text-success response"
                        data-event="<?= $event->id ?>" 
                        data-response="<?= Application\Model\Guest::RESP_OK ?>">
                        <i class="material-icons green-text large">event_available</i>
                    </a>
                    <p><u><b>personnes</b></u></p>
                    <div id="list-<?= Application\Model\Guest::RESP_OK ?>">
                        <?php foreach ($users[Application\Model\Guest::RESP_OK] as $user) : ?>
                            <p class="classic"><?= $user->getFullname() ?></p>
                        <?php endforeach; ?>
                    </div>
                </div>
                <div class="text-center item">
                    <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_NO ?>"
                        class="text-danger response"
                        data-event="<?= $event->id ?>" 
                        data-response="<?= Application\Model\Guest::RESP_NO ?>">
                        <i class="material-icons large">event_busy</i>
                    </a>
                    <p><u><b>personnes</b></u></p>
                    <div id="list-<?= Application\Model\Guest::RESP_NO ?>">
                        <?php foreach ($users[Application\Model\Guest::RESP_NO] as $user) : ?>
                            <p class="classic"><?= $user->getFullname() ?></p>
                        <?php endforeach; ?>
                    </div>
                </div>
                <div class="text-center item">
                    <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_INCERTAIN ?>"
                        class="text-warning response"
                        data-event="<?= $event->id ?>" 
                        data-response="<?= Application\Model\Guest::RESP_INCERTAIN ?>">
                            <i class="material-icons large">date_range</i>
                    </a>
                    <p><u><b>personnes</b></u></p>
                    <div id="list-<?= Application\Model\Guest::RESP_INCERTAIN ?>">
                        <?php foreach ($users[Application\Model\Guest::RESP_INCERTAIN] as $user) : ?>
                            <p class="classic"><?= $user->getFullname() ?></p>
                        <?php endforeach; ?>
                    </div>
                </div>
                <div class="text-center item">
                    <i class="material-icons large">hourglass_empty</i>
                    <p><u><b>personnes</b></u></p>
                    <div id="list-<?= Application\Model\Guest::RESP_NO_ANSWER ?>">
                        <?php foreach ($users[Application\Model\Guest::RESP_NO_ANSWER] as $user) : ?>
                            <p class="classic"><?= $user->getFullname() ?></p>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.container -->
    </div>

    <div class="section section-tabs">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="title comment-title">
                        <h3>Commentaires</h3>
                    </div>
                    <?php if (empty($comments)): ?>
                        <p class="no-comment">Il n'y a actuellement aucun commentaire pour cet évènement.</p>
                    <?php endif ?>

                    <?php foreach ($comments as $comment): ?>
                        <div class="card card-nav-tabs">
                            <div class="content">
                                <div class="tab-content">
                                    <div class="tab-pane active" id="profile">
                                        <blockquote class="comment">
                                            <p>
                                                <?= nl2br($comment['comment']); ?>
                                            </p>
                                            <small>
                                                <?= $comment['author']->getFullName(); ?> - <i><?= \Application\Service\Date::toFr($comment['date']); ?></i>
                                            </small>
                                        </blockquote>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach ?>
                    <!-- End Tabs with icons on Card -->
                </div>
            </div>
        </div>
    </div>
    <!-- End Section Tabs -->
</div>

<?php echo $this->partial('partial/fab/event.phtml') ?>

<div class="modal fade" id="modale-comment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="row">
                <div class="card card-signup">
                    <?php echo $this->form()->openTag($form); ?>
                        <div class="header header-primary text-center">
                            <h4>Commenter</h4>
                        </div>
                        <div class="content">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">comment</i>
                                </span>
                                <?php echo $this->formElement($form->get('comment')); ?>
                            </div>
                        </div>
                        <div class="text-center">
                            <input id="submit-comment" data-eventId="<?= $event->id ?>" data-groupId="<?= $group->id ?>" type="submit" name="submit" class="btn btn-primary" value="Enregistrer">
                        </div>
                    <?php echo $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
</div>
