<div class="row">
    <form method="POST">
    <div class="col-md-10 col-md-offset-1">
        <div class="card">
            <div class="card-content">
                <div class="col-xs-12">
                    <div class="col-xs-4">
                        <div class="row">
                            <div class="stats-score text-center">
                                <?= $scoreUs ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-4">
                        <div class="row">
                            <div class=" text-center">
                                <?php if ($set == 1): ?>
                                    <?= $set ?>er Set
                                <?php else: ?>
                                    <?= $set ?>ième Set
                                <?php endif ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-4">
                        <div class="row">
                            <div class="stats-score text-center">
                                <?= $scoreThem ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12">
                    <hr>
                </div>
                <h5 style="margin-bottom:0;" class="text-center">Point pour<star>*</star></h5>
                <div class="col-xs-6">
                    <div class="row">
                        <div class="funkyradio">
                            <div class="funkyradio-primary">
                                <input type="radio" name="point-for" id="point-for" value="<?= \Application\Model\Stats::POINT_US ?>" required/>
                                <label for="point-for">Nous</label>
                                <input type="hidden" name="score-us" value="<?= $scoreUs ?>">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-6">
                    <div class="row">
                        <div class="funkyradio">
                            <div class="funkyradio-primary">
                                <input type="radio" name="point-for" id="point-against" value="<?= \Application\Model\Stats::POINT_THEM ?>"/>
                                <label for="point-against">Eux</label>
                                <input type="hidden" name="score-them" value="<?= $scoreThem ?>">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12">
                    <hr>
                </div>
                <h5 style="margin-bottom:0;" class="text-center">Raison<star>*</star></h5>
                <div class="col-xs-6">
                    <h5 style="margin-bottom:0;" class="text-center">Point</h5>
                    <div class="row">
                        <div class="funkyradio">
                            <div class="funkyradio-success">
                                <input type="radio" name="reason" id="sercive-point" value="<?= \Application\Model\Stats::POINT_SERVE ?>" required />
                                <label for="sercive-point">Service</label>
                            </div>
                            <div class="funkyradio-success">
                                <input type="radio" name="reason" id="Attack-point" value="<?= \Application\Model\Stats::POINT_ATTACK ?>"/>
                                <label for="Attack-point">Attaque</label>
                            </div>
                            <div class="funkyradio-success">
                                <input type="radio" name="reason" id="block-point" value="<?= \Application\Model\Stats::POINT_BLOCK ?>"/>
                                <label for="block-point">Block</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-6">
                    <h5 style="margin-bottom:0;" class="text-center">Fautes</h5>
                    <div class="row">
                        <div class="funkyradio">
                            <div class="funkyradio-danger">
                                <input type="radio" name="reason" id="serve-fault" value="<?= \Application\Model\Stats::FAULT_SERVE ?>"/>
                                <label for="serve-fault">Service</label>
                            </div>
                            <div class="funkyradio-danger">
                                <input type="radio" name="reason" id="attack-fault" value="<?= \Application\Model\Stats::FAULT_ATTACK ?>"/>
                                <label for="attack-fault">Attaque</label>
                            </div>
                            <div class="funkyradio-danger">
                                <input type="radio" name="reason" id="defence-fault" value="<?= \Application\Model\Stats::FAULT_DEFENCE ?>"/>
                                <label for="defence-fault">Défensive</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <hr>
                    </div>
                    <div class="col-xs-6 text-left">
                        <a href="/event/detail/<?= $event->id ?>" type="button" class="btn btn-default" value="Évènement">Évènement</a>
                    </div>
                    <div class="col-xs-6 text-right">
                        <input type="submit" class="btn btn-primary" value="Valider">
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
</div>