<h4><?= $event->name ?></h4>

<?php
$setFor = $setAgainst = 0;
$lastFor = $lastThem = 0;
foreach ($setsLastScore as $scores) {
	if ($scores) {
		$lastUs = $scores[0];
		$lastThem = $scores[1];
		if (($lastUs >= 25 || $lastThem >= 25) && (abs(
                $lastUs - $lastThem) >= 2)) {
			if ($lastUs >= $lastThem) {
				$setFor ++;
			} else {
				$setAgainst++;
			}
		}
	}
}
?>

<div class="row">
	<div class="col-md-4">
		<div class="col-xs-4  col-md-12">
		    <div class="card">
		        <div class="card-content">
		            <div class="numbers-center">
		            	<p>Nous</p>
		            	<?= $lastUs ?>
		            </div>
		        </div>
		    </div>
		</div>
		<div class="col-xs-4 col-md-12">
		    <div class="card">
		        <div class="card-content">
		            <div class="text-center">
		            	<p>Sets</p>
		            	<?= $setFor ?> - <?= $setAgainst ?>
		            </div>
		        </div>
		    </div>
		</div>
		<div class="col-xs-4 col-md-12">
		    <div class="card">
		        <div class="card-content">
		            <div class="numbers-center">
		            	<p>Eux</p>
		            	<?= $lastThem ?>
		            </div>
		        </div>
		    </div>
		</div>
	</div>
	<?php if ($overallStats): ?>
        <div class="col-xs-12 col-md-8">
            <div class="card">
                <div class="card-content">
                    <h4 class="card-title">Statistiques du match</h4>
                    <div class="overall-stats-chart" style="width:100%" data-stats-us="<?= $overallStats['us'] ?>" data-stats-them="<?= $overallStats['them'] ?>"></div>
                </div>
            </div>
        </div>
	<?php endif ?>
</div>

<?= $this->partial('partial/stats.phtml') ?>
