<div class="row">
  <div class="col-xs-4 text-center">
      <div class="card">
          <div class="card-content">
              <div class="row">
                  <div class="col-xs-12">
                      <div class="numbers-center">
                          <p>Nous</p>
                          20
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <div class="col-xs-4">
      <div class="card">
            <div class="card-content">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <div class="numbers-center">
                            <p>Sets</p>
                            2-0
                        </div>
                    </div>
                </div>
            </div>
      </div>
    </div>
    <div class="col-xs-4">
        <div class="card">
            <div class="card-content">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <div class="numbers-center">
                            <p>Eux</p>
                            20
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <form method="POST">
        <div class="<?= (!$setsStats[$set]) ? 'col-md-8 col-md-offset-2' : 'col-md-8' ; ?>">
            <div class="card">
                <div class="card-content">
                    <h5 class="text-center">Durant le point</h5>
                    <div class='col-xs-12'>
                        <div class="col-xs-6">
                            <div class="text-center">Nous</div>
                            <button class="btn btn-success col-xs-12">Block (<span>0</span>)</button>
                            <div class="col-xs-12" style="height: 20px;"></div>
                            <button class="btn btn-success col-xs-12">Défense (<span>0</span>)</button>
                        </div>
                        <div class="col-xs-6">
                            <div class="text-center">Eux</div>
                            <button class="btn btn-warning col-xs-12">Block (<span>0</span>)</button>
                            <div class="col-xs-12" style="height: 20px;"></div>
                            <button class="btn btn-warning col-xs-12">Défense (<span class="value">0</span>)</button>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <hr>
                    </div>

                    <h5 style="margin-bottom:0;" class="text-center">Point pour<star>*</star></h5>
                    <div class="col-xs-6">
                        <div class="row">
                            <div class="funkyradio">
                                <div class="funkyradio-success">
                                    <input type="radio" name="point-for" id="point-for" value="<?= \Application\Model\Stats::POINT_US ?>" required/>
                                    <label for="point-for">Nous</label>
                                    <input type="hidden" name="score-us" value="<?= $scoreUs ?>">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="row">
                            <div class="funkyradio">
                                <div class="funkyradio-danger">
                                    <input type="radio" name="point-for" id="point-against" value="<?= \Application\Model\Stats::POINT_THEM ?>"/>
                                    <label for="point-against">Eux</label>
                                    <input type="hidden" name="score-them" value="<?= $scoreThem ?>">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <hr>
                    </div>
                    <h5 class="text-center">Fin du point<star>*</star></h5>
                    <div class='col-xs-6 text-center'>
                        <button class="btn btn-success btn-fill col-xs-12">Service</button>
                        <div class="col-xs-12" style="height: 10px;"></div>
                        <button class="btn btn-success btn-fill col-xs-12" data-toggle="modal" data-target="#attaque">Attaque</button>
                        <div class="col-xs-12" style="height: 10px;"></div>
                        <button class="btn btn-success btn-fill col-xs-12">Block</button>
                    </div>
                    <div class='col-xs-6 text-center'>
                        <button class="btn btn-danger btn-fill col-xs-12">Service</button>
                        <div class="col-xs-12" style="height: 10px;"></div>
                        <button class="btn btn-danger btn-fill col-xs-12" data-toggle="modal" data-target="#attaque">Attaque</button>
                        <div class="col-xs-12" style="height: 10px;"></div>
                        <button class="btn btn-danger btn-fill col-xs-12">Block</button>
                    </div>
                    <div class="col-xs-12">
                        <hr>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <?php if ($deleteLink): ?>
                                <button class="btn btn-danger" onclick="demo.showSwal('warning-message-and-confirmation', '<?= $deleteLink ?>')"><i class="fa fa-undo"></i></button>
                            <?php endif ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="attaque" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span> <span class="sr-only">close</span></button>
                        <h4 class="modal-title">Point à l'attaque</h4>
                    </div>
                    <div class="modal-body">
                        <div class="col-md-12">
                            <p class="category">
                                <h5>Poste de l'attaque</h5>
                                <div class="btn-group text-center" data-toggle="buttons">
                                  <label class="btn btn-primary">
                                    <input type="radio" name="options" id="option1" autocomplete="off"> R4
                                  </label>
                                  <label class="btn btn-primary">
                                    <input type="radio" name="options" id="option2" autocomplete="off"> Pointe
                                  </label>
                                  <label class="btn btn-primary">
                                    <input type="radio" name="options" id="option3" autocomplete="off"> Fix
                                  </label>
                                  <label class="btn btn-primary">
                                    <input type="radio" name="options" id="option3" autocomplete="off"> 3m
                                  </label>
                                </div>
                            </p>
                        </div>
                        <div class="col-md-12">
                            <p class="category">
                                <h5>Précision</h5>
                                <div class="radio">
                                    <input type="radio" name="radio1" id="line" value="option1" checked="">
                                    <label for="line">
                                        Ligne
                                    </label>
                                </div>
                                <div class="radio">
                                    <input type="radio" name="radio1" id="diagonal" value="option1" checked="">
                                    <label for="diagonal">
                                        Diagonale
                                    </label>
                                </div>
                                <div class="radio">
                                    <input type="radio" name="radio1" id="small-diagonal" value="option1" checked="">
                                    <label for="small-diagonal">
                                        Petite Diagonale
                                    </label>
                                </div>
                                <div class="radio">
                                    <input type="radio" name="radio1" id="block-out" value="option1" checked="">
                                    <label for="block-out">
                                        Block Out
                                    </label>
                                </div>
                                <div class="radio">
                                    <input type="radio" name="radio1" id="placed" value="option1" checked="">
                                    <label for="placed">
                                        Balle Placée
                                    </label>
                                </div>
                            </p>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">valider</button>
                    </div>
                </div>
            </div>
        </div>

        <?= $this->partial('partial/stats.phtml') ?>
    </form>
</div>
