<div class="row">
    <div class="content">
        <div class="container-fluid">
            <form method="POST">
                <div class="row">
                    <div class="col-md-6">
                        <div class="card card-wizard" id="wizardCard">
                            <form id="wizardForm" method="" action="">
                                <div class="card-header text-center">
                                    <h4 class="card-title">Set <?= $set ?></h4>
                                </div>
                                <div class="card-content">
                                    <ul class="nav">
                                        <li><a href="#tab1" data-toggle="tab">Point</a></li>
                                        <li><a href="#tab2" data-toggle="tab">Raison</a></li>
                                        <li><a href="#tab3" data-toggle="tab">Détails</a></li>
                                    </ul>
                                    <div class="tab-content">
                                        <div class="tab-pane" id="tab1">
                                            <h5 class="text-center">Le point est pour</h5>
                                            <div class="row">
                                                <div class="col-md-12" data-toggle="buttons">
                                                  <label class="btn btn-success btn-next col-xs-5 text-center">
                                                    <input type="radio" name="point-for">
                                                    <div class="numbers-center">
                                                        <p>Nous</p>
                                                        <?= isset($setsLastScore[$set][0]) ? $setsLastScore[$set][0] : 0; ?>
                                                    </div>
                                                  </label>
                                                  <label class="btn btn-danger btn-next pull-right col-xs-5 col-xs-offset-1">
                                                    <input type="radio" name="point-against">
                                                    <div class="numbers-center">
                                                        <p>Eux</p>
                                                        <?= isset($setsLastScore[$set][1]) ? $setsLastScore[$set][1] : 0; ?>
                                                    </div>
                                                  </label>
                                                </div>
                                            </div>
                                            <hr>
                                            <div class="row">
                                                <div class="col-md-12" data-toggle="buttons">
                                                  <p class="category text-center" style="margin-bottom: 5px">Durant le point</p>
                                                  <div class="btn btn-default col-xs-5 text-center">
                                                    <input type="hidden" name="block-for" value="0">
                                                    <div class="numbers-center">
                                                        <p>Block +1</p>
                                                        <span class="counter">0</span>
                                                    </div>
                                                  </div>
                                                  <div class="btn btn-default pull-right col-xs-5 col-xs-offset-1">
                                                    <input type="hidden" name="block-against" value="0">
                                                    <div class="numbers-center">
                                                        <p>Block +1</p>
                                                        <span class="counter">0</span>
                                                    </div>
                                                  </div>
                                                </div>
                                                <div class="col-xs-12" style="height: 10px"></div>
                                                <div class="col-md-12" data-toggle="buttons">
                                                  <div class="btn btn-default col-xs-5 text-center">
                                                    <input type="hidden" name="def-for" value="0">
                                                    <div class="numbers-center">
                                                        <p>Défense +1</p>
                                                        <span class="counter">0</span>
                                                    </div>
                                                  </div>
                                                  <div class="btn btn-default pull-right col-xs-5 col-xs-offset-1">
                                                    <input type="hidden" name="def-against" value="0">
                                                    <div class="numbers-center">
                                                        <p>Défense +1</p>
                                                        <span class="counter">0</span>
                                                    </div>
                                                  </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="tab-pane" id="tab2">
                                            <div class="row">
                                                <div class='col-xs-6 text-center'>
                                                    <h5 class="text-center">Point</h5>
                                                    <button value="1" name="reason" class="btn btn-success col-xs-12">Service</button>
                                                    <div class="col-xs-12" style="height: 10px;"></div>
                                                    <button type="button" class="btn btn-success btn-next col-xs-12" >Attaque</button>
                                                    <div class="col-xs-12" style="height: 10px;"></div>
                                                    <button value="3" name="reason" class="btn btn-success col-xs-12">Block</button>
                                                </div>
                                                <div class='col-xs-6 text-center'>
                                                    <h5>Faute</h5>
                                                    <button value="4" name="reason" class="btn btn-danger col-xs-12">Service</button>
                                                    <div class="col-xs-12" style="height: 10px;"></div>
                                                    <button value="5" name="reason" class="btn btn-danger col-xs-12" data-toggle="modal" data-target="#attaque">Attaque</button>
                                                    <div class="col-xs-12" style="height: 10px;"></div>
                                                    <button value="6" name="reason" class="btn btn-danger col-xs-12">Défensive</button>
                                                </div>
                                            </div>
                                            <hr>
                                        </div>
                                        <div class="tab-pane" id="tab3">
                                            <div class="row">
                                                <div class='col-xs-12 text-center'>
                                                    <h5>Poste Attaque</h5>
                                                    <div class="" data-toggle="buttons">
                                                        <label class="btn btn-primary col-xs-4">
                                                            <input type="radio" name="post" id="option1" autocomplete="off"> 4
                                                        </label>
                                                        <label class="btn btn-primary col-xs-4">
                                                            <input type="radio" name="post" id="option3" autocomplete="off"> Fix
                                                        </label>
                                                        <label class="btn btn-primary col-xs-4">
                                                            <input type="radio" name="post" id="option2" autocomplete="off"> 2
                                                        </label>
                                                        <div class="col-xs-12" style="height: 10px"></div>
                                                        <label class="btn btn-primary col-xs-4 col-xs-offset-2">
                                                            <input type="radio" name="post" id="option1" autocomplete="off"> 3m
                                                        </label>
                                                        <label class="btn btn-primary col-xs-4 col-xs-offset-1">
                                                            <input type="radio" name="post" id="option3" autocomplete="off"> Passeur
                                                        </label>
                                                    </div>
                                                </div>
                                                <div class='col-xs-12 text-center'>
                                                    <h5>Zone</h5>
                                                    <div class="" data-toggle="buttons">
                                                        <label class="btn btn-primary col-xs-12">
                                                            <input type="radio" name="post" id="option3" autocomplete="off"> Ligne
                                                        </label>
                                                        <div class="col-xs-12" style="height: 10px"></div>
                                                        <label class="btn btn-primary col-xs-6">
                                                            <input type="radio" name="post" id="option3" autocomplete="off"> Grande Diag.
                                                        </label>
                                                        <label class="btn btn-primary col-xs-6">
                                                            <input type="radio" name="post" id="option3" autocomplete="off"> Petite Diag.
                                                        </label>
                                                        <div class="col-xs-12" style="height: 10px"></div>
                                                        <label class="btn btn-primary col-xs-6">
                                                            <input type="radio" name="post" id="option2" autocomplete="off"> Block Out
                                                        </label>
                                                        <label class="btn btn-primary col-xs-6">
                                                            <input type="radio" name="post" id="option1" autocomplete="off"> Bidouille
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                            <hr>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button type="button" class="btn btn-default btn-fill btn-back pull-left"><i class="fa fa-arrow-left"></i></button>
                                    <button class="btn btn-success btn-fill btn-wd btn-finish pull-right">Valider</button>
                                    <div class="clearfix"></div>
                                </div>
                            </form>
                        </div>
                        <div class="row text-center">
                            <?php if ($deleteLink): ?>
                                <button class="btn btn-danger btn-fill col-xs-6 col-xs-offset-3" type="button" onclick="demo.showSwal('warning-message-and-confirmation', '<?= $deleteLink ?>')"><i class="fa fa-undo"></i> Correction</button>
                            <?php endif ?>
                        </div>
                    </div>
                    <?= $this->partial('partial/stats.phtml') ?>
                </div>
            </form>
        </div>
    </div>
    <hr class="visible-xs">
</div>
