<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large red">
      <i class="large material-icons md-48">add</i>
    </a>

    <ul>
        <li>
            <span class="mobile-fab-tip">Commenter</span>
            <a href="#" class="btn-floating indigo tooltipped" data-position="left" data-tooltip="Commenter" data-toggle="modal" data-target="#modale-comment">
                  <i class="material-icons submenu">comment</i>
            </a>
        </li>
        <?php if ($isAdmin): ?>
            <li>
                <span class="mobile-fab-tip">Modifier l'évènement</span>
                <a href="/event/edit/<?= $event->id ?>" class="btn-floating blue tooltipped" data-position="left" data-tooltip="Édition">
                      <i class="material-icons submenu">edit</i>
                </a>
            </li>
            <?php if (!$match || ($match && $match->set1Team1)): ?>
                <li>
                    <span class="mobile-fab-tip">Résultat de la rencontre</span>
                    <a href="/match/create/<?= $event->id ?>" class="btn-floating pink tooltipped" data-position="left" data-tooltip="Résultat">
                          <i class="material-icons submenu">content_paste</i>
                    </a>
                </li>
            <?php else: ?>
            	<li>
            	    <span class="mobile-fab-tip">Résultat de la rencontre</span>
            	    <a href="/match/edit/<?= $match->id ?>" class="btn-floating pink tooltipped" data-position="left" data-tooltip="Résultat">
            	          <i class="material-icons submenu">content_paste</i>
            	    </a>
            	</li>
            <?php endif ?>
        <?php endif ?>
        <li>
            <span class="mobile-fab-tip">Incertain</span>
            <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_INCERTAIN ?>" class="btn-floating amber tooltipped" data-position="left" data-tooltip="Incertain">
                  <i class="material-icons submenu">date_range</i>
            </a>
        </li>
        <li>
            <span class="mobile-fab-tip">Absent</span>
            <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_NO ?>" class="btn-floating red tooltipped" data-position="left" data-tooltip="Absent">
                  <i class="material-icons submenu">event_busy</i>
            </a>
        </li>
        <li>
            <span class="mobile-fab-tip">Présent</span>
            <a href="/guest/response/<?= $event->id ?>/<?= Application\Model\Guest::RESP_OK ?>" class="btn-floating green tooltipped" data-position="left" data-tooltip="Présent">
                  <i class="material-icons submenu">event_available</i>
            </a>
        </li>
    </ul>
</div>
