<?php if ($user && $isAdmin): ?>
    <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
        <a class="btn-floating btn-large red">
          <i class="large material-icons md-48">add</i>
        </a>

        <ul>
            <li>
                <span class="mobile-fab-tip">Supprimer le groupe</span>
                <a href="/group/delete/<?= $group->id ?>" class="btn-floating red tooltipped" data-position="left" data-tooltip="Éditer">
                      <i class="material-icons submenu">delete_forever</i>
                </a>
            </li>
<!--             <li>
                <span class="mobile-fab-tip">Inviter des membres</span>
                <a href="#" class="btn-floating indigo tooltipped" data-position="left" data-tooltip="Share" data-toggle="modal" data-target="#modale-share">
                <i class="material-icons submenu">share</i>
                </a>
            </li> -->
            <li>
                <span class="mobile-fab-tip">Membres</span>
                <a href="/group/users/<?= $group->id ?>" class="btn-floating indigo tooltipped"   data-position="left" data-tooltip="Membres">
                      <i class="material-icons submenu">group</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Éditer le groupe</span>
                <a href="/group/edit/<?= $group->id ?>" class="btn-floating dark-green tooltipped" data-position="left" data-tooltip="Éditer">
                      <i class="material-icons submenu">edit</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Évènement récurrent</span>
                <a href="/recurent/all/<?= $group->id ?>" class="btn-floating amber tooltipped" data-position="left" data-tooltip="Évènement récurrent">
                      <i class="material-icons submenu">repeat</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Évènement ponctuel</span>
                <a href="/event/create/<?= $group->id ?>" class="btn-floating pink tooltipped" data-position="left" data-tooltip="Évènement ponctuel">
                      <i class="material-icons submenu">event</i>
                </a>
            </li>
        </ul>
    </div>
<?php endif ?>