<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large red">
      <i class="large material-icons md-48">add</i>
    </a>

    <ul>
        <li>
            <span class="mobile-fab-tip">Page publique</span>
            <a href="<?= $group->getPublicLink() ?>" class="btn-floating indigo tooltipped"   data-position="left" data-tooltip="Partager">
                  <i class="material-icons submenu">share</i>
            </a>
        </li>
        <li>
            <span class="mobile-fab-tip">Historic</span>
            <a href="/group/history/<?= $group->id ?>" class="btn-floating blue tooltipped"   data-position="left" data-tooltip="Partager">
                  <i class="material-icons">history</i>
            </a>
        </li>
        <?php if ($isAdmin): ?>
            <li>
                <span class="mobile-fab-tip">Membres</span>
                <a href="/group/users/<?= $group->id ?>" class="btn-floating orange tooltipped"   data-position="left" data-tooltip="Membres">
                      <i class="material-icons submenu">group</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Éditer</span>
                <a href="/group/edit/<?= $group->id ?>" class="btn-floating dark-green tooltipped" data-position="left" data-tooltip="Éditer">
                      <i class="material-icons submenu">edit</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Évènement récurrent</span>
                <a href="/recurent/create/<?= $group->id ?>" class="btn-floating amber tooltipped" data-position="left" data-tooltip="Évènement récurrent">
                      <i class="material-icons submenu">repeat</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Évènement ponctuel</span>
                <a href="/event/create/<?= $group->id ?>" class="btn-floating pink tooltipped" data-position="left" data-tooltip="Évènement ponctuel">
                      <i class="material-icons submenu">event</i>
                </a>
            </li>
	    <?php endif ?>
    </ul>
</div>