<div class="row">
    <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
        <?= $this->form()->openTag($form); ?>
            <div class="card" data-background="color" data-color="blue">
                <div class="card-header">
                    <h3 class="card-title">Mot de passe oublié</h3>
                </div>
                <div class="card-content">
                    <div class="form-group">
                        <label>E-mail</label>
                        <?= $this->formElement($this->form->get('email')); ?>
                    </div>
                </div>
                <div class="card-footer text-center">
                    <button type="submit" class="btn btn-fill btn-wd ">Let's go</button>
                </div>
            </div>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>