<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="header-text">
            <h2>Volley-Ball.eu</h2>
            <h4>Gestion d'entrainement et match</h4>
            <hr>
        </div>
    </div>
    <div class="col-md-4 col-md-offset-2">
        <div class="media">
            <div class="media-left">
                <div class="icon icon-danger">
                    <i class="ti ti-user"></i>
                </div>
            </div>
            <div class="media-body">
                <h5>Gérez votre groupe</h5>
                Créez un groupe et invitez vos partenaires. Commencez à créer des entrainements et des matchs. Tout le monde sera notifié et pourra donner ses disponibilités en 1 click.
            </div>
        </div>
        <div class="media">
            <div class="media-left">
                <div class="icon icon-warning">
                    <i class="ti-bar-chart-alt"></i>
                </div>
            </div>
            <div class="media-body">
                <h5>Simple et intuitif</h5>
                Commentez, débriefer, voir les statistiques du groupe. Tout est rapide et simple d'utilisation. A tout moment vous pourrez savoir combien et qui sera disponible pour un évènement.
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <?= $this->form()->openTag($signUpForm); ?>
            <div class="card card-plain">
                <div class="content">
                    <div class="form-group">
                        <?= $this->formElement($signUpForm->get('firstname')); ?>
                    </div>
                    <div class="form-group">
                        <?= $this->formElement($signUpForm->get('lastname')); ?>
                    </div>
                    <div class="form-group">
                        <?= $this->formElement($signUpForm->get('email')); ?>
                    </div>
                    <div class="form-group">
                        <?= $this->formElement($signUpForm->get('password')); ?>
                    </div>
                    <div class="form-group">
                        <?= $this->formElement($signUpForm->get('repassword')); ?>
                    </div>
                </div>
                <div class="footer text-center">
                    <button type="submit" class="btn btn-fill btn-danger btn-wd">Créer mon compte</button>
                </div>
            </div>
        <?= $this->form()->closeTag($signUpForm); ?>
    </div>
</div>