<div class="row">
    <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
        <?= $this->form()->openTag($signInForm); ?>
            <div class="card" data-background="color" data-color="blue">
                <div class="card-header">
                    <h3 class="card-title">Login</h3>
                </div>
                <div class="card-content">
                    <div class="form-group">
                        <label>Email address</label>
                        <?= $this->formElement($this->signInForm->get('email')); ?>
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <?= $this->formElement($this->signInForm->get('password')); ?>
                    </div>
                </div>
                <div class="card-footer text-center">
                    <button type="submit" class="btn btn-fill btn-wd ">Let's go</button>
                    <div class="forgot">
                        <a href="/auth/email">Mot de passe oublié ?</a>
                    </div>
                </div>
            </div>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>