<div class="header header-filter" style="background-image: url('/img/bg-recep-ori.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="brand">
                    <h1>Volley-ball.eu</h1>
                    <h3>Gestion de groupes, entrainements, matchs.</h3>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="main main-raised">
    <div class="section section-basic">
        <div class="container text-center">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <h2><?= $group->name ?> - Suppression</h2>
                    <h4>Vous êtes sur le point de supprimer ce groupe. Tous les évènements, commentaires, historiques seront définitivement supprimer.</h4>
                    <div class="col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-4">
                        <a href="/group/delete/<?= $group->id?>?delete=true" class="btn btn-danger btn-lg">
                            <i class="material-icons">delete_forever</i>  Supprimer le groupe
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->partial('partial/fab/group.phtml') ?>