<!-- Gray semi-transparent overlay
If you don't want the overlay, don't include this div.
If you do want it, include this div above all your content
-->
<!-- <div class="overlay"></div> -->

<div class="header header-filter" style="background-image: url('/img/bg-recep-ori.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="brand">
                    <h1>Volley-ball.eu</h1>
                    <h3>Gestion de groupes, entrainements, matchs.</h3>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="main main-raised">
    <div class="section section-basic">
        <div class="container text-center">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <h2><?= $group->name ?> - Vos évènements</h2>
                    <h4>Bienvenue sur votre page pour le group <b><?= $group->name ?></b>. Ici seront répertoriés tous vos évènements liés à ce groupe.</h4>
                </div>
                <div class="col-md-3 col-md-offset-5">
                    <ul class="nav nav-pills" role="tablist">
                        <li class="<?= ($this->user->display == Application\Model\User::DISPLAY_LARGE) ? 'active' : ''; ?>">
                            <a href="#" class="display" data-user="<?= $this->user->id ?>" data-display="<?= Application\Model\User::DISPLAY_LARGE ?>">
                                <i class="material-icons">view_module</i>
                                Vue étendue
                            </a>
                        </li>
                        <li class="<?= ($this->user->display == Application\Model\User::DISPLAY_SMALL) ? 'active' : ''; ?>">
                            <a class="display" href="#" data-user="<?= $this->user->id ?>" data-display="<?= Application\Model\User::DISPLAY_SMALL ?>">
                                <i class="material-icons">view_list</i>
                                Vue minimale
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="section section-tabs">
        <div class="container">
            <div class="row">
                <?php if ($this->user->display == Application\Model\User::DISPLAY_LARGE): ?>
                    <div class="col-sm-12">
                        <?php foreach ($events as $event): ?>
                            <?php echo $this->partial('partial/dashboard-events.phtml', $event) ?>
                        <?php endforeach ?>
                    </div>
                <?php else: ?>
                    <table class="table-striped"
                    data-toggle="table"
                           data-pagination="true"
                           data-locale="fr-FR"
                           data-search="true"
                           data-page-size="10"
                           data-page-list="[10,25,50,100]">
                        <thead>
                            <th data-field="date" data-sortable="true">Date</th>
                            <th data-field="name" data-sortable="true">Nom</th>
                            <th data-field="action"></th>
                        </thead>
                        <tbody>
                            <?php foreach ($events as $event): ?>
                                <?php echo $this->partial('partial/list-events.phtml', $event) ?>
                            <?php endforeach ?>
                        </tbody>
                    </table>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>


<?php if ($this->user): ?>
    <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
        <a class="btn-floating btn-large red">
          <i class="large material-icons md-48">add</i>
        </a>

        <ul>
            <li>
                <span class="mobile-fab-tip">Page publique</span>
                <a href="<?= $group->getPublicLink() ?>" class="btn-floating indigo tooltipped"   data-position="left" data-tooltip="Partager">
                      <i class="material-icons submenu">share</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Historic</span>
                <a href="/group/history/<?= $group->id ?>" class="btn-floating blue tooltipped"   data-position="left" data-tooltip="Partager">
                      <i class="material-icons">history</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Membres</span>
                <a href="/members/all/<?= $group->id ?>" class="btn-floating orange tooltipped"   data-position="left" data-tooltip="Membres">
                      <i class="material-icons submenu">group</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Éditer</span>
                <a href="/group/edit/<?= $group->id ?>" class="btn-floating dark-green tooltipped" data-position="left" data-tooltip="Éditer">
                      <i class="material-icons submenu">edit</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Évènement récurrent</span>
                <a href="/recurent/create/<?= $group->id ?>" class="btn-floating amber tooltipped" data-position="left" data-tooltip="Évènement récurrent">
                      <i class="material-icons submenu">repeat</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Évènement ponctuel</span>
                <a href="/event/create/<?= $group->id ?>" class="btn-floating pink tooltipped" data-position="left" data-tooltip="Évènement ponctuel">
                      <i class="material-icons submenu">event</i>
                </a>
            </li>
        </ul>
    </div>
<?php endif ?>