<div class="header header-filter" style="background-image: url('/img/bg-recep-ori.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="brand">
                    <h1>Volley-ball.eu</h1>
                    <h3>Gestion de groupes, entrainements, matchs.</h3>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="main main-raised">
    <div class="section section-basic">
        <div class="container">
            <div class="title">
                <h2>Basic Elements</h2>
            </div>
        </div>
    </div>

    <div class="section section-tabs">
        <div class="container">
            <div class="row">
                <div>
                    <div class="title col-md-8">
                        <h2>Évènements à venir</h2>
                    </div>
                    <div class="col-md-4">
                        <ul class="nav nav-pills" role="tablist">
                            <li class="active">
                                <a href="#dashboard" role="tab" data-toggle="tab">
                                    <i class="material-icons">view_module</i>
                                    Vue étendue
                                </a>
                            </li>
                            <li>
                                <a href="#tasks" role="tab" data-toggle="tab">
                                    <i class="material-icons">view_list</i>
                                    Vue minimale
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-12">
                    <?php foreach ($events as $event): ?>
                        <?php echo $this->partial('partial/dashboard-events.phtml', $event) ?>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    </div>
</div>

<?php if ($this->user): ?>
    <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
        <a class="btn-floating btn-large red">
            <i class="material-icons md-48">add</i>
        </a>

        <ul>
            <li>
                <a class="btn-floating indigo btn-tooltip" data-toggle="tooltip" data-placement="left" title="Partager" href="/group/share/<?= $group->id ?>">
                    <i class="material-icons submenu">share</i>
                </a>
            </li>
            <li>
                <a class="btn-floating orange btn-tooltip" data-toggle="tooltip" data-placement="left" title="Membres" href="/group/share/<?= $group->id ?>">
                    <i class="material-icons submenu">group</i>
                </a>
            </li>
            <li>
                <a class="btn-floating dark-green btn-tooltip" data-toggle="tooltip" data-placement="left" title="Éditer" href="/group/edit/<?= $group->id ?>">
                    <i class="material-icons submenu">edit</i>
                </a>
            </li>
            <li>
                <a class="btn-floating amber btn-tooltip" data-toggle="tooltip" data-placement="left" title="Évèn. Récurent" href="/recurent/create/<?= $group->id ?>">
                    <i class="material-icons submenu">repeat</i>
                </a>
            </li>
            <li>
                <a class="btn-floating pink btn-tooltip" data-toggle="tooltip" data-placement="left" title="Évèn. Ponctuel" href="/event/create/<?= $group->id ?>">
                    <i class="material-icons submenu">event</i>
                </a>
            </li>
        </ul>
    </div>
<?php endif ?>