<div class="header header-filter" style="background-image: url('/img/bg-recep-ori.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="brand">
                    <h1>Volley-ball.eu</h1>
                    <h3>Gestion de groupes, entrainements, matchs.</h3>
                </div>
            </div>
        </div>

    </div>
</div>

<?php if (isset($form)): ?>
    <div class="main main-raised">
        <div class="section section-basic">
            <div class="container">
                <div class="title">
                    <h2>Création d'un groupe</h2>
                </div>

                <div class="row">
                    <?php echo $this->form()->openTag($form); ?>

                    <div class="col-md-12">
                        <div class="col-md-6">

                            <div class="title">
                                <h4>Informations</h4>
                            </div>

                            <div class="form-group label-floating is-filed">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">group</i>
                                    </span>
                                    <label class="control-label" for="name">
                                        Nom du groupe
                                    </label>
                                    <?php echo $this->formInput($form->get('name')); ?>
                                </div>
                            </div>

                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">description</i>
                                </span>
                                <?php echo $this->formElement($form->get('description')); ?>
                            </div>

                            <div class="form-group label-floating is-filed">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">group</i>
                                    </span>
                                    <label class="control-label" for="long">
                                        Longitude
                                    </label>
                                    <?php echo $this->formInput($form->get('long')); ?>
                                </div>
                            </div>

                            <div class="form-group label-floating is-filed">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">group</i>
                                    </span>
                                    <label class="control-label" for="lat">
                                        Lattitude
                                    </label>
                                    <?php echo $this->formInput($form->get('lat')); ?>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="title">
                                <h4>Adresse et horraire</h4>
                            </div>
                            <div class="form-group label-floating is-filed">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">account_balance</i>
                                    </span>
                                    <label class="control-label" for="gymnasium">
                                        Nom du Gymnase
                                    </label>
                                    <?php echo $this->formInput($form->get('gymnasium')); ?>
                                </div>
                            </div>

                            <div class="form-group label-floating is-filed">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="material-icons">local_post_office</i>
                                    </span>
                                    <label class="control-label" for="address">
                                        Adresse
                                    </label>
                                    <?php echo $this->formInput($form->get('address')); ?>
                                </div>
                            </div>

                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">schedule</i>
                                </span>
                                <?php echo $this->formElement($form->get('schedule')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-12 footer text-center">
                        <?php echo $this->formElement($form->get('submit')); ?>
                    </div>

                    <?php echo $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
<?php endif ?>

<?php echo $this->partial('partial/fab/group.phtml') ?>