<div class="header header-filter" style="background-image: url('/img/bg-recep-ori.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="brand">
                    <h1>Volley-ball.eu</h1>
                    <h3>Gestion de groupes, entrainements, matchs.</h3>
                </div>
            </div>
        </div>

    </div>
</div>

<?php if (isset($form)): ?>
    <div class="main main-raised">
            <div class="section section-basic">
                <div class="container text-center">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2 text-center">
                            <h2>Editez votre groupe</h2>
                            <h4>Aucune description n'est associée à cet évènement.</h4>
                        </div>
                    </div>
                </div>
            </div>

            <div class="section" style="background-image: url('/img/cover_4_blur.jpg'); background-size: cover; background-position: top center; min-height: 300px;">
                <!--   Big container   -->
                <div id="wizard" class="container">
                    <div class="row">
                        <div class="col-sm-8 col-sm-offset-2">

                            <!--      Wizard container        -->
                            <div class="wizard-container">
                                <div class="card wizard-card" data-color="azure" id="wizard">
                                    <?php echo $this->form()->openTag($form); ?>

                                        <div class="wizard-header">
                                            <h3 class="wizard-title">Création de groupe</h3>
                                            <!-- <p class="category">Book from thousands of unique work and meeting spaces.</p> -->
                                        </div>

                                        <div class="wizard-navigation">
                                            <div class="progress-with-circle">
                                                 <div class="progress-bar" role="progressbar" aria-valuenow="1" aria-valuemin="1" aria-valuemax="3" style="width: 21%;"></div>
                                            </div>
                                            <ul>
                                                <li>
                                                    <a href="#details" data-toggle="tab">
                                                        <div class="icon-circle">
                                                            <i class="ti-list"></i>
                                                        </div>
                                                        Details
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#captain" data-toggle="tab">
                                                        <div class="icon-circle">
                                                            <i class="ti-map"></i>
                                                        </div>
                                                        Adresse
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                        <div class="tab-content">
                                            <div class="tab-pane" id="details">
                                                <div class="row">
                                                    <div class="col-sm-12">
                                                    </div>
                                                    <div class="col-sm-10 col-sm-offset-1">
                                                        <div class="form-group label-floating is-filed">
                                                            <div class="input-group">
                                                                <span class="input-group-addon">
                                                                    <i class="material-icons">group</i>
                                                                </span>
                                                                <label class="control-label" for="name">
                                                                    Nom du groupe
                                                                </label>
                                                                <?php echo $this->formInput($form->get('name')); ?>
                                                            </div>
                                                        </div>
                                                        <div class="form-group label-floating is-filed">
                                                            <div class="input-group">
                                                                <span class="input-group-addon">
                                                                    <i class="material-icons">description</i>
                                                                </span>
                                                                <label class="control-label" for="description">
                                                                    Description du club, équipe etc.
                                                                </label>
                                                                <?php echo $this->formElement($form->get('description')); ?>
                                                            </div>
                                                        </div>
                                                        <div class="form-group label-floating is-filed">
                                                            <div class="input-group">
                                                                <span class="input-group-addon">
                                                                    <i class="material-icons">schedule</i>
                                                                </span>
                                                                <label class="control-label" for="schedule">
                                                                    Jour et heure des entrainements
                                                                </label>
                                                                <?php echo $this->formElement($form->get('schedule')); ?>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane" id="captain">
                                                    <div class="row">
                                                        <div class="col-sm-10 col-sm-offset-1">
                                                            <div class="form-group label-floating is-filed">
                                                                <div class="input-group">
                                                                    <span class="input-group-addon">
                                                                        <i class="material-icons">account_balance</i>
                                                                    </span>
                                                                    <label class="control-label" for="gymnasium">
                                                                        Nom du Gymnase
                                                                    </label>
                                                                    <?php echo $this->formElement($form->get('gymnasium')); ?>
                                                                </div>
                                                            </div>

                                                            <div class="form-group label-floating is-filed">
                                                                <div class="input-group">
                                                                    <span class="input-group-addon">
                                                                        <i class="material-icons">local_post_office</i>
                                                                    </span>
                                                                    <label class="control-label" for="address">
                                                                        Adresse (ex: 70 rue de Dunois, 75013 Paris)
                                                                    </label>
                                                                    <?php echo $this->formElement($form->get('address')); ?>
                                                                </div>
                                                            </div>

                                                            <div class="form-group label-floating is-filed">
                                                                <div class="input-group">
                                                                    <span class="input-group-addon">
                                                                        <i class="material-icons">group</i>
                                                                    </span>
                                                                    <label class="control-label" for="long">
                                                                        Longitude
                                                                    </label>
                                                                    <?php echo $this->formInput($form->get('long')); ?>
                                                                </div>
                                                            </div>
                                                            <div class="form-group label-floating is-filed">
                                                                <div class="input-group">
                                                                    <span class="input-group-addon">
                                                                        <i class="material-icons">group</i>
                                                                    </span>
                                                                    <label class="control-label" for="lat">
                                                                        Lattitude
                                                                    </label>
                                                                    <?php echo $this->formInput($form->get('lat')); ?>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        <div class="wizard-footer">
                                            <div class="pull-right">
                                                <input type='button' class='btn btn-next btn-fill btn-primary' name='next' value='Suivant' />
                                                <?php echo $this->formElement($form->get('submit')); ?>
                                            </div>

                                            <div class="pull-left">
                                                <input type='button' class='btn btn-previous btn-default btn-wd' name='previous' value='Précédent' />
                                            </div>
                                            <div class="clearfix"></div>
                                        </div>
                                    <?php echo $this->form()->closeTag($form); ?>
                                </div>
                            </div> <!-- wizard container -->
                        </div>
                    </div> <!-- row -->
                </div> <!--  big container -->
            </div>
    </div>
<?php endif ?>