<div class="header header-filter" style="background-image: url('/img/bg-recep-ori.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="brand">
                    <h1>Volley-ball.eu</h1>
                    <h3>Gestion de groupes, entrainements, matchs.</h3>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="main main-raised">
    <div class="section section-basic">
        <div class="container text-center">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <h2>Les évènements</h2>
                    <h4>Vous trouverez ici tous les évènements passés et à venir de votre groupe</h4>
                </div>
            </div>
        </div>

        <div class="section">
            <div class="container">
                <div class="row">
                    <table class="table-striped"
                           data-toggle="table"
                           data-pagination="true"
                           data-locale="fr-FR"
                           data-search="true"
                           data-page-size="10"
                           data-page-list="[10,25,50,100]">
                        <thead>
                            <th data-field="name" data-sortable="true">Nom</th>
                            <th data-field="date" data-sortable="true">Date</th>
                            <th data-field="action"></th>
                        </thead>
                        </thead>
                        <tbody>
                        <?php if (count($events)): ?>
                            <?php foreach ($events as $event): ?>
                                <tr>
                                    <td><?= $event->name ?></td>
                                    <td><?= $event->date ?></td>
                                    <td class="text-right">
                                        <a href="/event/detail/<?= $event->id ?>"><i class="material-icons">search</i> Détails</a>
                                    </td>
                                </tr>
                            <?php endforeach ?>
                        <?php else: ?>
                            <tr>
                                <td colspan="3">Aucun résultat pour le nom de groupe</td>
                            </tr>
                        <?php endif ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>