<div class="header header-filter" style="background-image: url('/img/bg-recep-ori.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="brand">
                    <h1>Volley-ball.eu</h1>
                    <h3>Gestion de groupes, entrainements, matchs.</h3>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="main main-raised">
    <div class="section section-basic">
        <div class="container text-center">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <h2>Les Membres</h2>
                    <h4>Ici sont listé tous les membres du groupe ainsi que les personnes voulant rejoindre le groupe.</h4>
                </div>
            </div>
        </div>

        <div class="section">
            <div class="container">
                <div class="row">
                    <table class="table table-striped col-md-12">
                        <thead>
                            <th>Nom</th>
                            <th class="text-right">Admin</th>
                            <th></th>
                        </thead>
                        <tbody>
                        <?php if (count($users)): ?>
                            <?php foreach ($users as $user): ?>
                                <tr>
                                    <td>
                                        <?= $user->getFullname() ?>
                                    </td>
                                    <td class="text-right">
                                        <span class="togglebutton">
                                            <label>
                                                <input name="users" data-group="<?php echo $group->id ?>" data-user="<?php echo $user->id ?>" 
                                                <?php if (in_array($user->id, $adminIds)): ?>
                                                    checked=""
                                                    value="0"
                                                <?php else: ?>
                                                    value="1"
                                                <?php endif ?>
                                                type="checkbox">
                                            </label>
                                        </span>
                                    </td>
                                    <td class="text-right">
                                        <a href="#">
                                            <i class="material-icons">delete_forever</i>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach ?>
                        <?php else: ?>
                            <tr>
                                <td colspan="3">Aucun résultat pour vos évènements</td>
                            </tr>
                        <?php endif ?>
                        </tbody>
                    </table>
                </div>

                <?php if (count($join)): ?>
                    <div class="row">
                        <h2>Demande à rejoindre le groupe</h2>
                        <table class="table-striped" data-toggle="table"
                               data-pagination="true"
                               data-search="false"
                               data-page-size="10"
                               data-page-list="[10,25,50,100]">
                            <thead>
                                <th data-field="name" data-sortable="true">Nom</th>
                                <th data-field="date">Admin</th>
                            </thead>
                            <tbody>
                                <?php foreach ($join as $userJoin): ?>
                                    <tr>
                                        <td>
                                            <?= $userJoin->getFullname() ?>
                                        </td>
                                        <td class="text-right">
                                            <a href="Nop#">
                                                <i class="material-icons">done</i>
                                            </a>
                                            <a href="#">
                                                <i class="material-icons">highlight_off</i>
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach ?>
                            </tbody>
                        </table>
                    </div>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>