<div class="row">
    <div class="col-lg-4">
        <div class="card">
            <div class="card-content">
                <div class="row">
                    <div class="col-xs-5">
                        <div class="icon-big icon-warning text-center">
                            <i class="ti-user"></i>
                        </div>
                    </div>
                    <div class="col-xs-7">
                        <div class="numbers">
                            <p>Membres</p>
                            <?= count($users) ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <hr />
                <div class="pull-right">
                    <a href="#" class="btn btn-info btn-fill btn-icon btn-sm">
                        <i class="ti-plus"></i>
                    </a>
                </div>
                <div class="stats">
                    <a href="#"> Gérer les membres</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card">
            <div class="card-content">
                <div class="row">
                    <div class="col-xs-5">
                        <div class="icon-big icon-success text-center">
                            <i class="ti-calendar"></i>
                        </div>
                    </div>
                    <div class="col-xs-7">
                        <div class="numbers">
                            <p>Évènements</p>
                            <?= $eventsCount ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <hr />
                <div class="pull-right">
                    <a href="#" class="btn btn-info btn-fill btn-icon btn-sm">
                        <i class="ti-plus"></i>
                    </a>
                </div>
                <div class="stats">
                    <a href="/event/create/<?= $group->id ?>"> Nouvel Évènement</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card">
            <div class="card-content">
                <div class="row">
                    <div class="col-xs-5">
                        <div class="icon-big icon-danger text-center">
                            <i class="ti-map"></i>
                        </div>
                    </div>
                    <div class="col-xs-7 text-right">
                        <b><?= $group->name ?></b><br/>
                        <?= $group->gymnasium ?><br/>
                        <?= $group->address ?>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <hr />
                <div class="pull-right">
                    <a href="#" class="btn btn-info btn-fill btn-icon btn-sm">
                        <i class="ti-plus"></i>
                    </a>
                </div>
                <div class="stats">
                    <a href="#"> Éditer le groupe</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card ">
            <div class="card-header">
                <h4 class="card-title">Présences</h4>
                <p class="category">Moyenne des présences par mois</p>
            </div>
            <div class="card-content">
                <div id="chart-disponibility" class="ct-chart" data-last-season="<?= $lastDisp ?>" data-current-season="<?= $currentDisp ?>"></div>
            </div>
            <div class="card-footer">
                <div class="chart-legend">
                    <i class="fa fa-circle text-info"></i> Saison précédente
                    <i class="fa fa-circle text-warning"></i> Saison actuelle
                </div>
            </div>
        </div>
    </div>
</div>

<?php if ($matches): ?>
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Matchs</h4>
                    <p class="category">Derniers matchs de la saison</p>
                </div>
                <div class="card-content">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="table-responsive">
                                <table class="table">
                                    <tbody>
                                        <?php foreach ($matches as $match): ?>
                                            <tr>
                                                <td><a href="/event/detail/<?= $match['eventId'] ?>"><?= $events[$match['eventId']]->name ?></a></td>
                                                <td><?= $events[$match['eventId']]->date ?></td>
                                                <td class="text-right">
                                                    <?php if ($match['victory']): ?>
                                                        <i class='text-success fa fa-check'></i> <?= $match['sets'] ?>
                                                    <?php else: ?>
                                                        <i class='text-danger fa fa-times'></i> <?= $match['sets'] ?>
                                                    <?php endif ?>
                                                </td>
                                            </tr>
                                        <?php endforeach ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Score</h4>
                    <p class="category">Comparatif des scores avec la saison précédente</p>
                </div>
                <div class="card-content">
                    <div class="row">
                        <div class="col-md-12">
                            <div id="chart-matches" data-last-season="<?= $scoresLast ?>" data-current-season="<?= $scoresCurrent ?>"></div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="chart-legend">
                        <i class="fa fa-circle text-info"></i> Saison précédente
                        <i class="fa fa-circle text-warning"></i> Saison actuelle
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Dernier Débrief</h4>
                </div>
                <div class="card-content">
                    <div class="row">
                        <div class="col-md-12">
                            <p class="category">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif ?>

<div class="row">
    <div class="col-md-12">
        <div class="card ">
            <div class="card-header">
                <h4 class="card-title">Membres</h4>
                <p class="category">Informations des membres</p>
            </div>
            <div class="card-content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <?php foreach ($users as $user): ?>
                                        <tr>
                                            <td><?= $user->getFullName() ?></td>
                                            <td><?= $user->email ?></td>
                                            <td><?= $user->phone ?></td>
                                        </tr>
                                    <?php endforeach ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Entrainements</h4>
                <p class="category">Évènements récurrent, création automatique</p>
            </div>
            <div class="card-content">
                <div class="table table-tasks">
                    <table class="table">
                        <tbody>
                            <tr>
                                <td>Entrainement le <b>mardi</b> à <b>20h</b></td>
                                <td class="td-actions text-right">
                                    <div class="table-icons">
                                        <div class="col-md-4">
                                            <input type="checkbox" class="switch-icon" checked>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Entrainement le <b>jeudi</b> à <b>20h</b></td>
                                <td class="td-actions text-right">
                                    <div class="table-icons">
                                        <div class="col-md-4">
                                            <input type="checkbox" class="switch-icon" checked>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <hr>
                <div class="pull-right">
                    <a href="#" class="btn btn-info btn-fill btn-icon btn-sm">
                        <i class="ti-plus"></i>
                    </a>
                </div>
                <div class="stats">
                    <a href=""></i> Ajouter un entrainement</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- <div class="row">
    <div class="col-md-12">
        <div class="card card-calendar">
            <div class="card-content">
                <div id="fullCalendar"></div>
            </div>
        </div>
    </div>
</div> -->