<div id="map" class="header-map" data-lat="<?= $group->lat ?>" data-long="<?= $group->long ?>">
</div>

<div class="main main-raised">

    <div class="section section-basic">
        <div class="container text-center">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <h2><?= $group->name ?></h2>
                    <div class="row">
                        <h4 class="text-center">
                        <?php if (!$user): ?>
                            <div class="col-xs-offset-2 col-sm-8 col-sm-offset-2">
                                Il semblerai que vous ne soyez pas connecté au site. Peut-être n'avez pas encore créé de compte. Afin de rejoindre le group <b><?= $group->name ?></b> vous devez avoir un compte actif.
                            </div>
                        <?php elseif ($member): ?>
                            <div class="col-xs-offset-2 col-sm-8 col-sm-offset-2">
                                Vous faites déjà parti du groupe <b><?= $group->name ?></b>
                            </div>
                        <?php elseif ($isJoining): ?>
                            <div class="col-xs-offset-2 col-sm-8 col-sm-offset-2">
                                Votre demande pour rejoindre le groupe <b><?= $group->name ?></b> est en cours de traitement. Merci de bien vouloir patienter.
                            </div>
                        <?php else: ?>
                            <div class="col-xs-offset-2 col-sm-8 col-sm-offset-2">
                                Pour rejoindre le groupe <b><?= $group->name ?></b> il vous suffit de cliquer sur le bouton ci-dessous.
                            </div>
                            <div class="col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-4">
                                <a href="/welcome-to/<?= $group->brand?>?subscribe=true" class="btn btn-primary btn-lg">
                                    <i class="material-icons">group_add</i>  Rejoindre le groupe
                                </a>
                            </div>
                        <?php endif ?>
                        </h4>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="section section-signup" style="background-image: url('/img/cover_4_blur.jpg'); background-size: cover; background-position: top center; min-height: 300px;">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="card card-signup">
                        <div class="header header-primary text-center">
                            <h4>Description</h4>
                        </div>
                        <div class="content">
                            <div class="main">
                                <h3 class="name">Information</h3>
                                <p class="profession">
                                    <?= $group->description ?>
                                </p>
                                <h3 class="name">Adresse</h3>
                                <p class="profession">
                                    <?= $group->address ?>
                                </p>
                                <h2 class="name">Horaires</h2>
                                <p class="profession">
                                    <?= nl2br($group->schedule) ?>
                                </p>
                                <p class="text-center"><a href="https://www.google.fr/maps/search/<?= urlencode($group->address) ?>"><i class="material-icons">place</i>Afficher la carte dans google maps</a></p>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<?php if ($this->user): ?>
    <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
        <a class="btn-floating btn-large red">
          <i class="large material-icons md-48">add</i>
        </a>

        <ul>
            <li>
                <span class="mobile-fab-tip">Historic</span>
                <a href="/group/history/<?= $group->id ?>" class="btn-floating blue tooltipped"   data-position="left" data-tooltip="Partager">
                      <i class="material-icons">history</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Membres</span>
                <a href="/members/all/<?= $group->id ?>" class="btn-floating orange tooltipped"   data-position="left" data-tooltip="Membres">
                      <i class="material-icons submenu">group</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Éditer</span>
                <a href="/group/edit/<?= $group->id ?>" class="btn-floating dark-green tooltipped" data-position="left" data-tooltip="Éditer">
                      <i class="material-icons submenu">edit</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Évènement récurent</span>
                <a href="/recurent/create/<?= $group->id ?>" class="btn-floating amber tooltipped" data-position="left" data-tooltip="Évènement récurent">
                      <i class="material-icons submenu">repeat</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Évènement ponctuel</span>
                <a href="/event/create/<?= $group->id ?>" class="btn-floating pink tooltipped" data-position="left" data-tooltip="Évènement ponctuel">
                      <i class="material-icons submenu">event</i>
                </a>
            </li>
        </ul>
    </div>
<?php endif ?>

<?php if (!$user): ?>
    <?php echo $this->partial('partial/signin.phtml') ?>
    <?php echo $this->partial('partial/signup.phtml') ?>
<?php endif ?>