<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>

    <link rel="apple-touch-icon" sizes="76x76" href="/img/apple-icon.png">
    <link rel="icon" type="image/png" href="/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>Volley-ball.eu Gestion de scéances.</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

    <!--     Fonts and icons     -->
<!--     <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
 -->    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300,500' rel='stylesheet' type='text/css'>
    <link href='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.css' rel='stylesheet' type='text/css'>
    <link href='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.print.css' rel='stylesheet' media="print" type='text/css'>

    <!-- CSS Files -->
    <link href="/css/bootstrap.min.css?v=<?= $this->vCss ?>" rel="stylesheet" />
    <link href="/css/font-awesome.min.css?v=<?= $this->vCss ?>" rel="stylesheet">
    <link href="/css/bootstrap-table.min.css?v=<?= $this->vCss ?>" rel="stylesheet">
    <link href="/css/animate.min.css?v=<?= $this->vCss ?>" rel="stylesheet">
    <link href="/css/materialize-test.css?v=<?= $this->vCss ?>" rel="stylesheet"/>
    <link href="/css/material-kit.css?v=<?= $this->vCss ?>" rel="stylesheet"/>
    <link href="/css/easy-autocomplete.min.css?v=<?= $this->vCss ?>" rel="stylesheet"/>
    <link href="/css/easy-autocomplete.themes.css?v=<?= $this->vCss ?>" rel="stylesheet"/>
    <link href="/css/rotating-card.css?v=<?= $this->vCss ?>" rel="stylesheet"/>
    <link href="/css/owl.carousel.css?v=<?= $this->vCss ?>" rel="stylesheet">
    <link href="/css/owl.theme.css?v=<?= $this->vCss ?>" rel="stylesheet">
    <link href="/css/bootstrap-material-datetimepicker.css?v=<?= $this->vCss ?>" rel="stylesheet"/>
    <link href="/css/demo.css?v=<?= $this->vCss ?>" rel="stylesheet" />
    <link href="/css/paper-bootstrap-wizard.css?v=<?= $this->vCss ?>" rel="stylesheet" />
    <link href="/css/themify-icons.css?v=<?= $this->vCss ?>" rel="stylesheet">
    <link href="/css/fresh-bootstrap-table.css?v=<?= $this->vCss ?>" rel="stylesheet">
    <link rel="stylesheet" href="/css/material-dashboard.css">


</head>

<body class="index-page">
    <div class="wrapper">
        <div class="sidebar" data-color="purple" data-image="/img/sidebar-1.jpg">
            <nav class="navbar navbar-transparent navbar-absolute navbar-fixed-top">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" aria-expanded="false" aria-controls="navbar">
                            <?php if (isset($badges['count']) && $badges['count']): ?>
                                <span class="badge"><?= $badges['count'] ?></span>
                            <?php endif ?>
                          <span class="sr-only">Toggle navigation</span>
                          <span class="icon-bar top-bar"></span>
                          <span class="icon-bar middle-bar"></span>
                          <span class="icon-bar bottom-bar"></span>
                        </button>
                    </div>
                </div>
            </nav>
            <div class="logo">
                <a href="http://volley-ball.eu" class="simple-text">
                    Volley-ball.eu
                </a>
            </div>

            <div class="sidebar-wrapper">
                <ul class="nav navmenu-nav">
                    <?php if (!$this->user): ?>
                        <li>
                            <a title="Créer un compte" href="#" data-toggle="modal" data-target="#modale-signup">
                                <i class="material-icons">account_circle</i> Créer un compte
                            </a>
                        </li>
                        <li>
                            <a title="Se connecter" href="#" data-toggle="modal" data-target="#modale-signin">
                                <i class="material-icons">power_settings_new</i> Connexion
                            </a>
                        </li>
                        <li>
                            <a title="Se connecter" href="#" data-toggle="modal" data-target="#modale-password">
                                <i class="material-icons">error_outline</i> oublié
                            </a>
                        </li>
                    <?php else: ?>
                        <li class="sidebar-title">Mon Compte</li>
                        <li>
                            <a href="/user/params">
                                <i class="material-icons">settings</i>
                                <p>Paramètres</p>
                            </a>
                        </li>
                        <li>
                            <a href="/absent">
                                <i class="material-icons">sentiment_dissatisfied</i>
                                <p>Absences</p>
                            </a>
                        </li>
                        <li>
                            <a title="Déconnexion" href="/auth/signout">
                                <i class="material-icons" style="color:#F00;">power_settings_new</i> 
                                <p>Déconnexion</p>
                            </a>
                        </li>
                        <li class="sidebar-title">Mes Groupes</li>
                        <?php if ($this->groups): ?>
                            <?php foreach ($this->groups as $group): ?>
                                <li>
                                    <a href="<?= $group->getPublicLink() ?>">
                                        <?= $group->name ?>
                                    </a>
                                </li>
                            <?php endforeach ?>
                        <?php else: ?>
                            <li>
                                <a href="/group/create">
                                   <i class="material-icons">group_add</i> Créer un groupe
                                </a>
                            </li>
                        <?php endif ?>
                        <?php if ($badges['count']): ?>
                            <li class="sidebar-title">Notifications</li>
                            <?php if (isset($badges['comments'])): ?>
                                <p class="sidebar-submenu">Commentaires</p>
                                <?php foreach ($badges['comments'] as $id => $values): ?>
                                    <li><a href="/event/detail/<?= $values['id'] ?>#comments" class="badge-comment" data-eventId="<?= $values['id'] ?>"><?= $values['label'] ?></a></li>
                                <?php endforeach ?>
                            <?php endif ?>
                        <?php endif ?>
                        <!-- <li><a href="/user/password">Mot de Passe</a></li> -->
                    <?php endif ?>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <div class="wrapper">
                <?php echo $this->content ?>
                <footer class="footer">
                    <div class="container">
                        <div class="copyright pull-right">
                            &copy; 2016, made with <i class="material-icons">favorite</i> by Benoit Duval.
                        </div>
                    </div>
                </footer>
            </div>
        </div>
    </div>

    <?php if (!isset($this->noFabMenu)): ?>
        <?php if (isset($this->event)): ?>
            <?php echo $this->partial('partial/fab/event.phtml') ?>
        <?php elseif (isset($this->group)): ?>
            <?php echo $this->partial('partial/fab/group.phtml') ?>
        <?php elseif ($this->user): ?>
            <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
                <a class="btn-floating btn-large red">
                  <i class="large material-icons md-48">add</i>
                </a>
                <ul>
                    <li>
                        <span class="mobile-fab-tip">Créer un groupe</span>
                        <a href="/group/create" class="btn-floating amber tooltipped" data-position="left" data-tooltip="Créer un groupe">
                            <i class="material-icons submenu">group_add</i>
                        </a>
                    </li>
                    <li>
                        <span class="mobile-fab-tip">Export calendrier</span>
                        <a href="/api/export/events" class="btn-floating orange tooltipped" data-position="left" data-tooltip="Export calendrier">
                            <i class="material-icons submenu">file_download</i>
                        </a>
                    </li>
                    <li>
                        <span class="mobile-fab-tip">Vue étendue</span>
                        <a href="javascript:void();" class="btn-floating display blue tooltipped display" data-user="<?= $this->user->id ?>" data-display="<?= Application\Model\User::DISPLAY_LARGE ?>">
                            <i class="material-icons submenu">dashboard</i>
                        </a>
                    </li>
                    <li>
                        <span class="mobile-fab-tip">Vue minimale</span>
                        <a href="javascript:void();" class="btn-floating display pink tooltipped display" data-user="<?= $this->user->id ?>" data-display="<?= Application\Model\User::DISPLAY_SMALL ?>">
                            <i class="material-icons submenu">view_module</i>
                        </a>
                    </li>
                    <li>
                        <span class="mobile-fab-tip">Vue calendrier</span>
                        <a href="javascript:void();" class="btn-floating display green tooltipped display" data-user="<?= $this->user->id ?>" data-display="<?= Application\Model\User::DISPLAY_TABLE ?>">
                            <i class="material-icons submenu">event</i>
                        </a>
                    </li>
                </ul>
            </div>
        <?php endif ?>
    <?php endif ?>

    <?php echo $this->partial('partial/modal.phtml') ?>
    <?php echo $this->partial('partial/reset.phtml') ?>

</body>
<!--   Core JS Files   -->
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="/js/jquery.easy-autocomplete.min.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="/js/jquery.validate.min.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="/js/bootstrap.min.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="/js/bootstrap-notify.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="/js/jquery.bootstrap.wizard.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="/js/paper-bootstrap-wizard.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="/js/owl.carousel.js?v=<?= $this->vJs ?>"></script>
<script src="/js/materialize-test.js?v=<?= $this->vJs ?>"></script>
<script src="/js/script.js?v=<?= $this->vJs ?>"></script>
<script src="/js/search.js?v=<?= $this->vJs ?>"></script>
<script src="/js/material.min.js?v=<?= $this->vJs ?>"></script>
<script src="/js/gmaps.js?v=<?= $this->vJs ?>"></script>
<script src="/js/moment.js?v=<?= $this->vJs ?>"></script>
<script src="/js/bootstrap-material-datetimepicker.js?v=<?= $this->vJs ?>"></script>
<script src="/js/bootstrap-table.min.js?v=<?= $this->vJs ?>"></script>
<script src="/js/bootstrap-table-fr-FR.js?v=<?= $this->vJs ?>"></script>
<script src="/js/material-kit.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="/js/jquery.ns-autogrow.min.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.js" type="text/javascript"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.js" type="text/javascript"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/locale-all.js" type="text/javascript"></script>
<script src="/js/awesome-landing-page.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="/js/material-dashboard.js"></script>
<script type="text/javascript">

    $().ready(function(){
        // the body of this function is in /material-kit.js
        // materialKit.initSliders();
        window_width = $(window).width();

        if (window_width >= 992){
            big_image = $('.wrapper > .header');

            $(window).on('scroll', materialKitDemo.checkScrollForParallax);
        }

    });

</script>

</html>

