<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>

    <link rel="apple-touch-icon" sizes="76x76" href="/img/apple-icon.png">
    <link rel="icon" type="image/png" href="/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>Volley-ball.eu Gestion de scéances.</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

    <!--     Fonts and icons     -->
<!--     <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
 -->    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300,500' rel='stylesheet' type='text/css'>


    <!-- CSS Files -->
    <link href="/css/bootstrap.min.css?v=<?= $this->vCss ?>" rel="stylesheet" />
    <link href="/css/font-awesome.min.css?v=<?= $this->vCss ?>" rel="stylesheet">
    <link href="/css/bootstrap-table.min.css?v=<?= $this->vCss ?>" rel="stylesheet">
    <link href="/css/animate.min.css?v=<?= $this->vCss ?>" rel="stylesheet">
    <link href="/css/materialize-test.css?v=<?= $this->vCss ?>" rel="stylesheet"/>
    <link href="/css/material-kit.css?v=<?= $this->vCss ?>" rel="stylesheet"/>
    <link href="/css/rotating-card.css?v=<?= $this->vCss ?>" rel="stylesheet"/>
    <link href="/css/owl.carousel.css?v=<?= $this->vCss ?>" rel="stylesheet">
    <link href="/css/owl.theme.css?v=<?= $this->vCss ?>" rel="stylesheet">
    <link href="/css/bootstrap-material-datetimepicker.css?v=<?= $this->vCss ?>" rel="stylesheet"/>
    <link href="/css/demo.css?v=<?= $this->vCss ?>" rel="stylesheet" />
    <link href="/css/paper-bootstrap-wizard.css?v=<?= $this->vCss ?>" rel="stylesheet" />
    <link href="/css/themify-icons.css?v=<?= $this->vCss ?>" rel="stylesheet">
    <link href="/css/fresh-bootstrap-table.css?v=<?= $this->vCss ?>" rel="stylesheet">


</head>

<body class="index-page">
<!-- Navbar -->
<?php $class = isset($opacity) ? 'opacity' : '' ; ?>
<nav class="navbar navbar-transparent navbar-fixed-top <?= $class ?> navbar-color-on-scroll">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-index">
                <?php if ($badges['count']): ?>
                    <span class="badge"><?= $badges['count'] ?></span>
                <?php endif ?>
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/">
                <div class="logo-container">
                    <div class="logo">
                        <img src="/img/logo.png" alt="volley-ball.eu" rel="tooltip" title="<b>Volley-ball.eu</b>, une gestion facile des disponibilités" data-placement="bottom" data-html="true">
                    </div>
                    <div class="brand">
                        Volley-ball.eu
                    </div>
                </div>
            </a>
        </div>

        <div class="collapse navbar-collapse" id="navigation-index">
            <ul class="nav navbar-nav navbar-right">
                <?php if (!$this->user): ?>
                    <li>
                        <a title="Créer un compte" href="#" data-toggle="modal" data-target="#modale-signup">
                            <i class="material-icons">account_circle</i> Créer un compte
                        </a>
                    </li>
                    <li>
                        <a title="Se connecter" href="#" data-toggle="modal" data-target="#modale-signin">
                            <i class="material-icons">power_settings_new</i> Connexion
                        </a>
                    </li>
                    <li>
                        <a title="Se connecter" href="#" data-toggle="modal" data-target="#modale-password">
                            <i class="material-icons">error_outline</i> oublié
                        </a>
                    </li>
                <?php else: ?>
                    <?php if ($badges['count']): ?>
                        <li class="dropdown">
                            <a title="Notifications" href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="material-icons">notifications_none</i> Notifications <span class="badge" style="background-color: #f44336;"><?= $badges['count'] ?></span> <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <?php if (isset($badges['comments'])): ?>
                                    <li class="dropdown-header">Commentaires</li>
                                    <?php foreach ($badges['comments'] as $id => $values): ?>
                                        <li><a href="/event/detail/<?= $values['id'] ?>#comments" class="badge-comment" data-eventId="<?= $values['id'] ?>"><?= $values['label'] ?></a></li>
                                    <?php endforeach ?>
                                <?php endif ?>
                                <?php if (isset($badges['events'])): ?>
                                    <li class="dropdown-header">Évènements sans réponse</li>
                                    <?php foreach ($badges['events'] as $values): ?>
                                        <li><a href="<?= $values['link'] ?>"><?= $values['label'] ?></a></li>
                                    <?php endforeach ?>
                                <?php endif ?>
                            </ul>
                        </li>
                    <?php endif ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->user->getFullname() ?> <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li class="dropdown-header">Mon Compte</li>
                            <li><a href="/user/params">Paramètres</a></li>
                            <li><a href="/absent">Absences</a></li>
                            <!-- <li><a href="/password">Mot de passe</a></li> -->
                            <li class="divider"></li>
                            <li class="dropdown-header">Mes Groupes</li>
                            <?php if ($this->groups): ?>
                                <?php foreach ($this->groups as $group): ?>
                                    <li>
                                        <a href="<?= $group->getPublicLink() ?>">
                                            <?= $group->name ?>
                                        </a>
                                    </li>
                                <?php endforeach ?>
                            <?php else: ?>
                                <li>
                                    <a href="/group/create">
                                        Créer un groupe
                                    </a>
                                </li>
                            <?php endif ?>
                            <!-- <li><a href="/user/password">Mot de Passe</a></li> -->
                        </ul>
                    </li>
                    <li>
                        <a title="Déconnexion" href="/auth/signout">
                            <i class="material-icons">power_settings_new</i> Déconnexion
                        </a>
                    </li>
                <?php endif ?>
            </ul>
             <form class="navbar-form navbar-right navbar-search-form" role="search" method="GET" action="/search">
               <div class="form-group">
                    <input type="text" value="" class="form-control" placeholder="Recherche..." name="q">
               </div>
            </form>
        </div>
    </div>
</nav>

<!-- End Navbar -->
<div class="wrapper">
    <?php echo $this->content ?>
    <footer class="footer">
        <div class="container">
<!--             <nav class="pull-left">
                <ul>
                    <li>
                        <a href="http://www.creative-tim.com">
                            Creative Tim
                        </a>
                    </li>
                    <li>
                        <a href="http://presentation.creative-tim.com">
                           About Us
                        </a>
                    </li>
                    <li>
                        <a href="http://blog.creative-tim.com">
                           Blog
                        </a>
                    </li>
                    <li>
                        <a href="http://www.creative-tim.com/license">
                            Licenses
                        </a>
                    </li>
                </ul>
            </nav> -->
            <div class="copyright pull-right">
                &copy; 2016, made with <i class="material-icons">favorite</i> by Benoit Duval.
            </div>
        </div>
    </footer>
</div>

<?php echo $this->partial('partial/modal.phtml') ?>
<?php echo $this->partial('partial/reset.phtml') ?>

</body>
<!--   Core JS Files   -->
<script src="/js/jquery.min.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="/js/jquery.validate.min.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="/js/jquery-ui-1.10.4.custom.min.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="/js/bootstrap.min.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="/js/bootstrap-notify.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="/js/jquery.bootstrap.wizard.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="/js/paper-bootstrap-wizard.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="/js/owl.carousel.js?v=<?= $this->vJs ?>"></script>
<script src="/js/materialize-test.js?v=<?= $this->vJs ?>"></script>
<script src="/js/script.js?v=<?= $this->vJs ?>"></script>
<script src="/js/material.min.js?v=<?= $this->vJs ?>"></script>
<script src="/js/gmaps.js?v=<?= $this->vJs ?>"></script>
<script src="/js/moment.js?v=<?= $this->vJs ?>"></script>
<script src="/js/bootstrap-material-datetimepicker.js?v=<?= $this->vJs ?>"></script>
<script src="/js/bootstrap-table.min.js?v=<?= $this->vJs ?>"></script>
<script src="/js/bootstrap-table-fr-FR.js?v=<?= $this->vJs ?>"></script>
<script src="/js/material-kit.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="/js/jquery.ns-autogrow.min.js?v=<?= $this->vJs ?>" type="text/javascript"></script>
<script src="/js/awesome-landing-page.js?v=<?= $this->vJs ?>" type="text/javascript"></script>

<script type="text/javascript">

    $().ready(function(){
        // the body of this function is in /material-kit.js
        // materialKit.initSliders();
        window_width = $(window).width();

        if (window_width >= 992){
            big_image = $('.wrapper > .header');

            $(window).on('scroll', materialKitDemo.checkScrollForParallax);
        }

    });

</script>

</html>

