<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <link rel="icon" type="image/png" href="/img/favicon.png">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <title>Volley-ball.eu</title>
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
        <meta name="viewport" content="width=device-width" />

        <link href="/css/bootstrap.css" rel="stylesheet" />
        <link href="/css/landing-page.css" rel="stylesheet"/>

        <!--     Fonts and icons     -->
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300,500' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,300' rel='stylesheet' type='text/css'>
        <link href="/css/pe-icon-7-stroke.css" rel="stylesheet" />

    </head>
    <body class="landing-page landing-page1">
        <nav class="navbar navbar-transparent navbar-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button id="menu-toggle" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                    </button>
                    <a href="/">
                        <div class="logo-container">
                            <div class="logo">
                                <img src="/img/logo.png" alt="volley-ball.eu" rel="tooltip" title="<b>Volley-ball.eu</b>, une gestion facile des disponibilités" data-placement="bottom" data-html="true">
                            </div>
                            <div class="brand">
                                Volley-ball.eu
                            </div>
                        </div>
                    </a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="example" >
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a title="Créer un compte" href="#" data-toggle="modal" data-target="#modale-signup">
                                <i class="material-icons">account_circle</i> Créer un compte
                            </a>
                        </li>
                        <li>
                            <a title="Se connecter" href="#" data-toggle="modal" data-target="#modale-signin">
                                <i class="material-icons">power_settings_new</i> Connexion
                            </a>
                        </li>
                        <li>
                            <a title="Mot de passe oublié" href="#" data-toggle="modal" data-target="#modale-password">
                                <i class="material-icons">warning</i> Oublié
                            </a>
                        </li>
                    </ul>
                     <form class="navbar-form navbar-right navbar-search-form" role="search" method="GET" action="/search">
                       <div class="form-group">
                            <input type="text" value="" class="form-control" placeholder="Recherche..." name="q">
                       </div>
                    </form>
                </div>
                <!-- /.navbar-collapse -->
            </div>
        </nav>
        <div class="wrapper">
            <div class="parallax filter-gradient blue" data-color="blue">
                <div class="parallax-background">
                    <img class="parallax-background-image" src="/img/bg-recep-ori.jpg">
                </div>
                <div class= "container">
                    <div class="row">
<!--                         <div class="col-md-5 hidden-xs">
                            <div class="parallax-image">
                                <img class="phone" src="/img/template/iphone3.png" style="margin-top: 20px"/>
                            </div>
                        </div> -->
                        <div class="col-md-8 col-md-offset-2">
                            <div class="description">
                                <h1 class="text-center">Volley-ball.eu</h1>
                                <br>
                                <h4 class="text-center">La gestion d'entrainement, de match et de présence en toute simplicité! </h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section section-testimonial">
                <div class="container">
                    <div id="carousel-example-generic" class="carousel fade" data-ride="carousel">
                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <div class="carousel-testimonial-caption">
                                    <h3>1. Créez un compte</h3>
                                    <p>Quelques secondes suffisent pour créer votre compte, tout est gratuit.</p>
                                </div>
                            </div>
                            <div class="item">
                                <div class="carousel-testimonial-caption">
                                    <h3>2. Créez un groupe</h3>
                                    <p>Créez un groupe pour commencer votre expérience avec <b>volley-ball.eu</b>.</p>
                                </div>
                            </div>
                            <div class="item">
                                <div class="carousel-testimonial-caption">
                                    <h3>3. Partagez votre groupe</h3>
                                    <p>Partagez l'adresse de votre groupe afin d'y ajouter des membres.</p>
                                </div>
                            </div>
                            <div class="item">
                                <div class="carousel-testimonial-caption">
                                    <h3>4. Créez vos évènements</h3>
                                    <p>C'est parti, il ne vous reste qu'à créer des évènements (entrainement, match etc).</p>
                                </div>
                            </div>
                        </div>
                        <ol class="carousel-indicators carousel-indicators-blue">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                        </ol>
                    </div>
                </div>
            </div>
            <div class="section section-gray section-clients">
                <div class="container text-center">
                    <h4 class="header-text">Gérez votre équipe</h4>
                    <p>
                        <b>Volley-ball.eu</b> vous permet de connaître à tout instant les disponibilités des membres d'un groupe. Pouvoir adapter au mieux les exercices aux entrainements, préparer dans les meilleurs conditions les matchs à venir suivant les présences etc.<br>
                    </p>
                </div>
            </div>
            <div class="section section-presentation">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="description">
                                <h4 class="header-text">Partout, tout le temps</h4>
                                <p>
                                    <b>Volley-ball.eu</b> s'adapte à tout type d'écran.
                                    Passez de votre ordinateur à votre téléphone ou tablette sans aucun problème de lisibilité. Vous y aurez accès partout et n'importe quand.
                                </p>
                            </div>
                        </div>
                        <div class="col-md-5 col-md-offset-1 hidden-xs">
                            <img src="/img/template/mac.png"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section section-gray section-demo">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <div id="description-carousel" class="carousel fade" data-ride="carousel">
                                <div class="carousel-inner">
                                    <div class="item">
                                        <img src="/img/template/examples/home_33.jpg" alt="">
                                    </div>
                                    <div class="item active">
                                        <img src="/img/template/examples/home_22.jpg" alt="">
                                    </div>
                                    <div class="item">
                                        <img src="/img/template/examples/home_11.jpg" alt="">
                                    </div>
                                </div>
                                <ol class="carousel-indicators carousel-indicators-blue">
                                    <li data-target="#description-carousel" data-slide-to="0" class="active"></li>
                                    <li data-target="#description-carousel" data-slide-to="1" class=""></li>
                                    <li data-target="#description-carousel" data-slide-to="2" class=""></li>
                                </ol>
                            </div>
                        </div>
                        <div class="col-md-5 col-md-offset-1">
                            <h4 class="header-text">Monitorez votre espace</h4>
                            <p>
                                Vous pouvez monitorer votre groupe, voir les détails des évènements, ajouter des membres, laisser des commentaires et bien d'autres choses encore. Un outil puissant en toute simplicité.
                            </p>
                            <!-- <a href="http://www.creative-tim.com/product/awesome-landing-page" id="Demo3" class="btn btn-fill btn-info" data-button="info">Get Free Demo</a> -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="section section-features">
                <div class="container">
                    <h4 class="header-text text-center">Fontionnalités</h4>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="card card-blue">
                                <div class="icon">
                                    <i class="pe-7s-date"></i>
                                </div>
                                <div class="text">
                                    <h4>Evènements ponctuels</h4>
                                    <p>Un match à venir ce weekend ? Créez un évènement ponctuel en donnant une heure et un lieu de RDV, les invitations, la page de détail, la carte seront automatiquement générées.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card card-blue">
                                <div class="icon">
                                    <i class="pe-7s-repeat"></i>
                                </div>
                                <h4>Évènements récurrents</h4>
                                <p>Vos entrainements sont tous les jeudi ? définissez une seul fois cet évènement récurrent, il sera automatiquement créé chaque semaine, le jour souhaité. Vous pourrez à tout moment suspendre ce processus.</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card card-blue">
                                <div class="icon">
                                    <i class="pe-7s-bell"></i>
                                </div>
                                <h4>Notification intelligente</h4>
                                <p>Chaque membre de votre groupe sera notifié par email à chaque évènement, commentaire... Il pourra donner sa disponibilité à un évènement par un simple clic dans l'email.</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card card-blue">
                                <div class="icon">
                                    <i class="pe-7s-note2"></i>
                                </div>
                                <h4>Score et débriefing</h4>
                                <p>Pour un match, vous pouvez à postériori indiquer le résultat de la rencontre ainsi qu'un débriefing.</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card card-blue">
                                <div class="icon">
                                    <i class="pe-7s-notebook"></i>
                                </div>
                                <h4>Historique</h4>
                                <p>Nous ne supprimons rien! Vous pourrez à tout instant retrouver un évènement passé pour y voir toutes ses informations.</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card card-blue">
                                <div class="icon">
                                    <i class="pe-7s-tools"></i>
                                </div>
                                <h4>Vos paramètres</h4>
                                <p>En tant que membre, vous pouvez définir à l'avance vos période d'absence. Tous les évènéments (créés ou futur) seront automatiquement mis à jour.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section section-no-padding">
                <div class="parallax filter-gradient blue" data-color="blue">
                    <div class="parallax-background">
                        <img class ="parallax-background-image" src="/img/dig.jpg"/>
                    </div>
                    <div class="info">
                        <h1>N'attendez plus, essayez!</h1>
                        <a href="javascript:void(0);" data-toggle="modal" data-target="#modale-signup" class="btn btn-neutral btn-lg btn-fill">Créer un compte</a>
                        <a href="javascript:void(0);" data-toggle="modal" data-target="#modale-signin" class="btn btn-info btn-lg btn-fill">Se connecter</a>
                    </div>
                </div>
            </div>
            <footer class="footer">
                <div class="container">
                    <div class="copyright">
                        &copy; 2016, made with love by Benoit Duval
                    </div>
                </div>
            </footer>
        </div>

        <div class="modal fade" id="modale-signin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="wrapper" style="padding:30px;">
                        <?php  $signInForm->setAttribute('action', $this->url('auth', ['action' => 'signin'])); ?>
                        <?= $this->form()->openTag($signInForm); ?>
                            <div class="header header-primary text-center">
                                <h4>Se connecter</h4>
                            </div>
                                <div class="form-group">
                                    <label class="control-label" for="email">
                                        E-mail
                                    </label>
                                    <?= $this->formElement($signInForm->get('email')); ?>
                                </div>
                                <div class="form-group">
                                        <!-- <span class="input-group-addon">
                                            <i class="material-icons">lock_outline</i>
                                        </span> -->
                                        <label class="control-label" for="password">
                                            Mot de passe
                                        </label>
                                        <?= $this->formElement($signInForm->get('password')); ?>
                                    </div>
                                </div>
                            <div class="text-center" style="margin-bottom: 30px">
                                <!-- <a href="#">Mot de passe oublié</a> -->
                                <input type="submit" name="submit" class="btn btn-info btn-lg btn-fill" value="Connexion">
                            </div>
                        <?= $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="modale-signup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="wrapper" style="padding:30px;">
                            <?php  $signUpForm->setAttribute('action', $this->url('auth', ['action' => 'signup'])); ?>
                            <?php echo $this->form()->openTag($signUpForm); ?>
                                <div class="header header-primary text-center">
                                    <h4>Créer un compte</h4>
                                </div>

                                    <div class="form-group">
                                        <label class="control-label" for="firstname">
                                            Prénom
                                        </label>
                                        <?= $this->formElement($signUpForm->get('firstname')); ?>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label" for="lastname">
                                            Nom
                                        </label>
                                        <?= $this->formElement($signUpForm->get('lastname')); ?>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label" for="email">
                                            E-mail
                                        </label>
                                        <?= $this->formElement($signUpForm->get('email')); ?>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label" for="password">
                                            Mot de passe
                                        </label>
                                        <?= $this->formElement($signUpForm->get('password')); ?>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label" for="password">
                                            Confirmation de mot de passe
                                        </label>
                                        <?= $this->formElement($signUpForm->get('repassword')); ?>
                                    </div>

                                </div>
                                <div class="text-center">
                                    <div class="text-center" style="margin-bottom: 30px">
                                        <!-- <a href="#">Mot de passe oublié</a> -->
                                        <input type="submit" name="submit" class="btn btn-info btn-lg btn-fill" value="Valider">
                                    </div>
                                </div>
                            <?php echo $this->form()->closeTag(); ?>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="modale-password" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="wrapper" style="padding:30px;">
                        <form method="POST" name="signup" action="/auth/email" id="signup">  
                                <div class="header header-primary text-center">
                                    <h4>Mot de passe oublié</h4>
                                </div>
                                    <p class="center">Merci d'indiquer votre adresse email, un lien vous sera envoyé pour changer votre mot de passe.</p>
                                    <div class="form-group">
                                        <label class="control-label" for="email">
                                            Email
                                        </label>
                                        <input type="email" name="email" class="form-control" required="required" value="">
                                    </div>
                                </div>
                                <div class="text-center">
                                    <div class="text-center" style="margin-bottom: 30px">
                                        <!-- <a href="#">Mot de passe oublié</a> -->
                                        <input type="submit" name="submit" class="btn btn-info btn-lg btn-fill" value="Valider">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </body>
    <script src="/js/jquery-2.2.4.min.js" type="text/javascript"></script>
    <script src="/js/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>
    <script src="/js/bootstrap.js" type="text/javascript"></script>
    <script src="/js/awesome-landing-page.js" type="text/javascript"></script>
</html>
