<div class="header header-filter" style="background-image: url('/img/bg-recep-ori.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="brand">
                    <h1>Volley-ball.eu</h1>
                    <h3>Gestion de groupes, entrainements, matchs.</h3>
                </div>
            </div>
        </div>

    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="delete-user" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Êtes-vous sûr?</h4>
            </div>
            <div class="modal-body">
                Voulez-vous supprimer cette personne du groupe ? 
            </div>
            <div class="modal-footer">
                <a id="delete-url" href="" class="btn btn-primary" type="button"><i class="fa fa-trash-o"></i> Supprimer</a>
                <button class="btn btn-inverse" type="button" data-dismiss="modal"><i class="icon icon-times icon-lg"></i> Annuler</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="main main-raised">
    <div class="section section-basic">
        <div class="container text-center">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <h2>Vos évènements récurrents</h2>
                    <h4>Sur cette page vous pourrez gérer vos entrainements. Créer un évènement récursif revient à lancer automatique des invitations aux membres du groupes toutes les semaines en créant des évènements à la volée.</h4>
                    <div class="col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-4">
                        <a href="/recurent/create/<?= $group->id ?>" class="btn btn-primary btn-lg">
                            <i class="material-icons">repeat</i>  Créer un évènement récurrent
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="section">
            <div class="container">
                <div class="row">
                    <table class="table table-striped col-md-12">
                        <thead>
                            <th class="hidden-xs">Nom</th>
                            <th>Jour</th>
                            <th>Heure</th>
                            <th class="hidden-xs">Envoi</th>
                            <th class="hidden-xs">Gymnase</th>
                            <th class="text-right">Actif</th>
                            <th></th>
                        </thead>
                        <tbody>
                        <?php if (count($recurents)): ?>
                            <?php foreach ($recurents as $recurent): ?>
                                <tr>
                                    <td class="hidden-xs">
                                        <?= $recurent->name ?>
                                    </td>
                                    <td>
                                        <?= \Application\Service\Date::toFr($recurent->eventDay) ?>
                                    </td>
                                    <td>
                                        <?= $recurent->time ?>
                                    </td>
                                    <td class="hidden-xs">
                                        <?= \Application\Service\Date::toFr($recurent->emailDay) ?>
                                    </td>
                                    <td class="hidden-xs">
                                        <?= $recurent->place ?>
                                    </td>
                                    <td class="text-right">
                                        <span class="togglebutton">
                                            <label>
                                                <input name="users" data-group="<?php echo $group->id ?>" data-user="<?php echo $user->id ?>" 
                                                <?php if ($recurent->status == \Application\Model\Recurent::ACTIVE): ?>
                                                    checked=""
                                                    value="0"
                                                <?php else: ?>
                                                    value="1"
                                                <?php endif ?>
                                                type="checkbox">
                                            </label>
                                        </span>
                                    </td>
                                    <td class="text-right">
                                        <a href="/recurent/edit/<?= $group->id ?>/<?= $recurent->id ?>"><i class="material-icons text-success">edit</i></a>
                                        <a href="javascrip:void(0)" class="open-delete-modal" data-toggle="modal" data-url="/recurent/delete/<?= $group->id; ?>/<?= $recurent->id; ?>" data-target="#delete-user" style="background-color: transparent;border:0;">
                                            <i class="material-icons text-danger">delete_forever</i>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach ?>
                        <?php else: ?>
                            <tr>
                                <td colspan="3">Aucun résultat pour vos évènements</td>
                            </tr>
                        <?php endif ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->partial('partial/fab/group.phtml') ?>