<div class="header header-filter" style="background-image: url('/img/bg-recep-ori.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="brand">
                    <h1>Volley-ball.eu</h1>
                    <h3>Gestion de groupes, entrainements, matchs.</h3>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="main main-raised">
    <div class="section section-basic">
    <div class="container text-center">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
                <h2>Paramètres de votre compte</h2>
                <h4>Vous pouvez choisir d'être avertis ou non suivant les cas de figures.</h4>
            </div>
        </div>
    </div>
    </div>
    <div class="section">
        <div class="container">
            <div class="row">
                <table class="table table-striped col-md-12">
                    <thead>
                        <th></th>
                        <th class="text-right">Actif</th>
                    </thead>
                    <tbody>
                        <?php foreach ($notifications as $notification): ?>
                            <tr>
                                <td>
                                    <?= $notification->getLabel() ?>
                                </td>
                                <td class="text-right">
                                    <span class="togglebutton">
                                        <label>
                                            <input name="notification" data-notif="<?= $notification->id ?>" 
                                            <?php if ($notification->status == \Application\Model\Notification::ACTIVE): ?>
                                                checked="checked"
                                                value="2"
                                            <?php else: ?>
                                                value="1"
                                            <?php endif ?>
                                            type="checkbox">
                                        </label>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>