<div class="header header-filter" style="background-image: url('/img/bg-recep-ori.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="brand">
                    <h1>Volley-ball.eu</h1>
                    <h3>Gestion de groupes, entrainements, matchs.</h3>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="main main-raised">
    <div class="section section-basic">
        <div class="container">
            <div class="title">
                <h2><b><?= $event->name ?></b></h2>
            </div>

            <div class="row">
                <?php echo $this->form()->openTag($form); ?>

                <div class="col-md-12">
                    <div class="col-md-6">
                        <div class="col-xs-6">
                            <div class="title">
                                <h4>Vous</h4>
                            </div>
                            <div class="form-group label-floating is-empty">
                                <div class="input-group">
                                    <label class="control-label" for="set1Team1">
                                        Set1
                                    </label>
                                    <?php echo $this->formElement($form->get('set1Team1')); ?>
                                </div>
                            </div>
                            <div class="form-group label-floating is-empty">
                                <div class="input-group">
                                    <label class="control-label" for="set2Team1">
                                        Set2
                                    </label>
                                    <?php echo $this->formElement($form->get('set2Team1')); ?>
                                </div>
                            </div>
                            <div class="form-group label-floating is-empty">
                                <div class="input-group">
                                    <label class="control-label" for="set3Team1">
                                        Set3
                                    </label>
                                    <?php echo $this->formElement($form->get('set3Team1')); ?>
                                </div>
                            </div>
                            <div class="form-group label-floating is-empty">
                                <div class="input-group">
                                    <label class="control-label" for="set4Team1">
                                        Set4
                                    </label>
                                    <?php echo $this->formElement($form->get('set4Team1')); ?>
                                </div>
                            </div>
                            <div class="form-group label-floating is-empty">
                                <div class="input-group">
                                    <label class="control-label" for="set5Team1">
                                        Set5
                                    </label>
                                    <?php echo $this->formElement($form->get('set5Team1')); ?>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-6">
                            <div class="title">
                                <h4>Adversaire</h4>
                            </div>
                            <div class="form-group label-floating is-empty">
                                <div class="input-group">
                                    <label class="control-label" for="set1Team2">
                                        Set1
                                    </label>
                                    <?php echo $this->formElement($form->get('set1Team2')); ?>
                                </div>
                            </div>
                            <div class="form-group label-floating is-empty">
                                <div class="input-group">
                                    <label class="control-label" for="set2Team2">
                                        Set2
                                    </label>
                                    <?php echo $this->formElement($form->get('set2Team2')); ?>
                                </div>
                            </div>
                            <div class="form-group label-floating is-empty">
                                <div class="input-group">
                                    <label class="control-label" for="set3Team2">
                                        Set3
                                    </label>
                                    <?php echo $this->formElement($form->get('set3Team2')); ?>
                                </div>
                            </div>
                            <div class="form-group label-floating is-empty">
                                <div class="input-group">
                                    <label class="control-label" for="set4Team2">
                                        Set4
                                    </label>
                                    <?php echo $this->formElement($form->get('set4Team2')); ?>
                                </div>
                            </div>
                            <div class="form-group label-floating is-empty">
                                <div class="input-group">
                                    <label class="control-label" for="set5Team2">
                                        Set5
                                    </label>
                                    <?php echo $this->formElement($form->get('set5Team2')); ?>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="col-md-6">
                        <h3>Résumé</h3>
                        <div class="form-group label-floating is-empty">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">comment</i>
                                </span>
                                <label class="control-label" for="debrief">
                                    Débriefing
                                </label>
                                <?php echo $this->formElement($form->get('debrief')); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12 footer text-center">
                    <?php echo $this->formElement($form->get('submit')); ?>
                </div>

                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
