<div class="header header-filter" style="background-image: url('/img/bg-recep-ori.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="brand">
                    <h1>Volley-ball.eu</h1>
                    <h3>Gestion de groupes, entrainements, matchs.</h3>
                </div>
            </div>
        </div>

    </div>
</div>

<?php if (isset($form)): ?>
    <div class="main main-raised">
       <div class="section section-basic">
           <div class="container text-center">
               <div class="row">
                   <div class="col-md-8 col-md-offset-2 text-center">
                       <h2>Éditez votre absence</h2>
                       <h4>Lorsque vous aurez enregistré votre période d'absence, chaque évènement (créé ou qui va être créé), dont la date est dans cette période, sera automatiquement mis à jour.</h4>
                   </div>
               </div>
           </div>
       </div>

       <div class="section" style="background-image: url('/img/cover_4_blur.jpg'); background-size: cover; background-position: top center; min-height: 300px;">
           <!--   Big container   -->
           <div id="wizard" class="container">
               <div class="row">
                   <div class="col-sm-8 col-sm-offset-2">

                       <!--      Wizard container        -->
                       <div class="wizard-container">
                           <div class="card wizard-card" data-color="azure" id="wizard">
                               <?php echo $this->form()->openTag($form); ?>

                                   <div class="wizard-header">
                                       <h3 class="wizard-title">Éditez votre absence</h3>
                                   </div>

                                   <div class="wizard-navigation">
                                       <div class="progress-with-circle">
                                            <div class="progress-bar" role="progressbar" aria-valuenow="1" aria-valuemin="1" aria-valuemax="3" style="width: 21%;"></div>
                                       </div>
                                       <ul>
                                           <li>
                                               <a href="#details" data-toggle="tab">
                                                   <div class="icon-circle">
                                                       <i class="ti-list"></i>
                                                   </div>
                                                   Dates
                                               </a>
                                           </li>
                                       </ul>
                                   </div>
                                   <div class="tab-content">
                                       <div class="tab-pane" id="details">
                                           <div class="row">
                                                <div class="col-sm-10 col-sm-offset-1">
                                                   <div class="form-group label-floating is-filed">
                                                       <div class="input-group">
                                                           <span class="input-group-addon">
                                                               <i class="material-icons">account_balance</i>
                                                           </span>
                                                           <label class="control-label" for="from">
                                                               Date de début
                                                           </label>
                                                           <?php echo $this->formInput($form->get('from')); ?>
                                                       </div>
                                                   </div>
                                                   <div class="form-group label-floating is-filed">
                                                       <div class="input-group">
                                                           <span class="input-group-addon">
                                                               <i class="material-icons">local_post_office</i>
                                                           </span>
                                                           <label class="control-label" for="to">
                                                               Date de fin
                                                           </label>
                                                           <?php echo $this->formElement($form->get('to')); ?>
                                                       </div>
                                                   </div>
                                                </div>
                                           </div>
                                       </div>
                                   </div>
                                   <div class="wizard-footer">
                                       <div class="pull-right">
                                           <input type='button' class='btn btn-next btn-fill btn-primary' name='next' value='Suivant' />
                                           <?php echo $this->formElement($form->get('submit')); ?>
                                       </div>

                                       <div class="pull-left">
                                           <input type='button' class='btn btn-previous btn-default btn-wd' name='previous' value='Précédent' />
                                       </div>
                                       <div class="clearfix"></div>
                                   </div>
                               <?php echo $this->form()->closeTag($form); ?>
                           </div>
                       </div> <!-- wizard container -->
                   </div>
               </div> <!-- row -->
           </div> <!--  big container -->
       </div>
    </div>
<?php endif ?>
