<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png" />
    <link rel="icon" type="image/png" href="../assets/img/favicon.png" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>Volley-ball.eu Administration</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!-- Bootstrap core CSS     -->
    <link href="/css/bootstrap.min.css" rel="stylesheet" />

    <!--  Material Dashboard CSS    -->
    <link href="/css/material-dashboard.css" rel="stylesheet"/>

    <link href="/css/font-awesome.min.css" rel="stylesheet">
    <link href="/css/bootstrap-table.min.css" rel="stylesheet">
    <link href="/css/bootstrap-material-datetimepicker.css" rel="stylesheet"/>
    <!-- <link href="/css/demo.css" rel="stylesheet" /> -->
    <link href="/css/fresh-bootstrap-table.css" rel="stylesheet">

    <!--     Fonts and icons     -->
    <!-- <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet"> -->
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>
</head>

<body>

    <div class="wrapper">

        <div class="sidebar" data-color="purple" data-image="/img/sidebar-1.jpg">
            <!--
                Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

                Tip 2: you can also add an image using data-image tag
            -->

            <div class="logo">
                <a href="http://volley-ball.eu" class="simple-text">
                    Volley-ball.eu
                </a>
            </div>

            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li class="active">
                        <a href="/admin">
                            <i class="material-icons">search</i>
                            <p>Search</p>
                        </a>
                    </li>
                    <li>
                        <a href="/admin/user">
                            <i class="material-icons">person</i>
                            <p>Utilisateurs</p>
                        </a>
                    </li>
                    <li>
                        <a href="/admin/group">
                            <i class="material-icons">dashboard</i>
                            <p>Groupes</p>
                        </a>
                    </li>
                    <li>
                        <a href="/admin/event">
                            <i class="material-icons">content_paste</i>
                            <p>Évènements</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                </div>
            </nav>
            <!-- content -->
            <?= $this->content ?>
        </div>

    </div>

</body>

    <!--   Core JS Files   -->
    <script src="/js/jquery-2.2.4.min.js" type="text/javascript"></script>
    <script src="/js/jquery.validate.min.js" type="text/javascript"></script>
    <script src="/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/js/material.min.js" type="text/javascript"></script>

    <script src="/js/admin.js"></script>
    <script src="/js/moment.js"></script>
    <script src="/js/bootstrap-material-datetimepicker.js"></script>
    <script src="/js/bootstrap-table.min.js"></script>
    <script src="/js/bootstrap-table-fr-FR.js"></script>
    <script src="/js/material-kit.js" type="text/javascript"></script>
    <script src="/js/jquery.ns-autogrow.min.js" type="text/javascript"></script>

    <!--  Charts Plugin -->
    <script src="/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="/js/bootstrap-notify.js"></script>

    <!-- Material Dashboard javascript methods -->
    <script src="/js/material-dashboard.js"></script>

    <script src="/js/script.js"></script>

<!--     <script type="text/javascript">
        $(document).ready(function(){

            // Javascript method's body can be found in assets/js/demos.js
            demo.initDashboardPageCharts();

        });
    </script> -->

</html>
