<div style="height:100%;margin:0;padding:0;width:100%;background-color:#ffffff">

	<center>
		<table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="m_6276084880465470621bodyTable" style="border-collapse:collapse;height:100%;margin:0;padding:0;width:100%;background-color:#ffffff">
			<tbody>
				<tr>
					<td align="center" valign="top" id="m_6276084880465470621bodyCell" style="height:100%;margin:0;padding:0;width:100%;border-top:0">

						<table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
							<tbody>
								<tr>
									<td align="center" valign="top" id="m_6276084880465470621templateHeader" style="background:#e6a56a url(&quot;https://ci6.googleusercontent.com/proxy/mWJz19HvLjH2NN1J5NdPO8op324uRTuxTUc75zX2DupK2-GgsDWZl8-QZlw2IZeOJv2vCEF7byae0uU2AybMLUnFL5KnaqDb75LEFVWZkr8LHILn7yFS-ty6xEdNdPvQEjvHKNaoJ4yWsckxUMx-KLw_JOQL9a4HE5SQL-E=s0-d-e1-ft#https://gallery.mailchimp.com/c294e5e6fcd7996580bb94ded/images/a3fc15e8-885e-4073-a134-951d2273d71d.jpg&quot;) no-repeat top/cover;background-color:#e6a56a;background-image:url(https://ci6.googleusercontent.com/proxy/mWJz19HvLjH2NN1J5NdPO8op324uRTuxTUc75zX2DupK2-GgsDWZl8-QZlw2IZeOJv2vCEF7byae0uU2AybMLUnFL5KnaqDb75LEFVWZkr8LHILn7yFS-ty6xEdNdPvQEjvHKNaoJ4yWsckxUMx-KLw_JOQL9a4HE5SQL-E=s0-d-e1-ft#https://gallery.mailchimp.com/c294e5e6fcd7996580bb94ded/images/a3fc15e8-885e-4073-a134-951d2273d71d.jpg);background-repeat:no-repeat;background-position:top;background-size:cover;border-top:0;border-bottom:0;padding-top:80px;padding-bottom:80px">

										<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621templateContainer" style="border-collapse:collapse;max-width:600px!important">
											<tbody>
												<tr>
													<td valign="top" class="m_6276084880465470621headerContainer">
														<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnTextBlock" style="min-width:100%;border-collapse:collapse">
															<tbody class="m_6276084880465470621mcnTextBlockOuter">
																<tr>
																	<td valign="top" class="m_6276084880465470621mcnTextBlockInner" style="padding-top:9px">



																		<table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%" class="m_6276084880465470621mcnTextContentContainer">
																			<tbody>
																				<tr>

																					<td valign="top" class="m_6276084880465470621mcnTextContent" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#ffffff;font-family:Helvetica;font-size:20px;line-height:150%;text-align:center">

																						<h1 style="display:block;margin:0;padding:0;color:#ffffff;font-family:Georgia;font-size:60px;font-style:normal;font-weight:normal;line-height:200%;letter-spacing:normal;text-align:center">
																							<span style="font-family:arial,helvetica neue,helvetica,sans-serif">Volley-Ball.eu</span>
																						</h1>

																						<h2 class="m_6276084880465470621mc-toc-title" style="text-align:center;display:block;margin:0;padding:0;color:#ffffff;font-family:Helvetica;font-size:30px;font-style:normal;font-weight:bold;line-height:125%;letter-spacing:normal">
																							<span style="font-family:arial,helvetica neue,helvetica,sans-serif">
																								<span style="font-size:24px">Gestion d'entrainements,<br>
																								&nbsp;matchs et statistiques</span>
																							</span>
																						</h2>

																						<p style="margin:10px 0;padding:0;color:#ffffff;font-family:Helvetica;font-size:20px;line-height:150%;text-align:center">&nbsp;</p>

																					</td>
																				</tr>
																			</tbody>
																		</table>



																	</td>
																</tr>
															</tbody>
														</table>
														<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnDividerBlock" style="min-width:100%;border-collapse:collapse;table-layout:fixed!important">
															<tbody class="m_6276084880465470621mcnDividerBlockOuter">
																<tr>
																	<td class="m_6276084880465470621mcnDividerBlockInner" style="min-width:100%;padding:20px 18px 0px">
																		<table class="m_6276084880465470621mcnDividerContent" border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
																			<tbody>
																				<tr>
																					<td>
																						<span>
																						</span>
																					</td>
																				</tr>
																			</tbody>
																		</table>

																	</td>
																</tr>
															</tbody>
														</table>
														<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnButtonBlock" style="min-width:100%;border-collapse:collapse">
															<tbody class="m_6276084880465470621mcnButtonBlockOuter">
																<tr>
																	<td style="padding-top:0;padding-right:18px;padding-bottom:18px;padding-left:18px" valign="top" align="center" class="m_6276084880465470621mcnButtonBlockInner">
																		<table border="0" cellpadding="0" cellspacing="0" class="m_6276084880465470621mcnButtonContentContainer" style="border-collapse:separate!important;border-radius:3px;background-color:#68b3c8">
																			<tbody>
																				<tr>
																					<td align="center" valign="middle" class="m_6276084880465470621mcnButtonContent" style="font-family:Arial;font-size:16px;padding:20px">
																						<a class="m_6276084880465470621mcnButton" title="Aller au site" href="http://volley-ball.eu" style="font-weight:bold;letter-spacing:normal;line-height:100%;text-align:center;text-decoration:none;color:#ffffff;display:block" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://volley-ball.eu&amp;source=gmail&amp;ust=1524169316102000&amp;usg=AFQjCNHXUA5yv-kL0f_Rnf0RsoQvh0rN2w">Aller au site</a>
																					</td>
																				</tr>
																			</tbody>
																		</table>
																	</td>
																</tr>
															</tbody>
														</table>
													</td>
												</tr>
											</tbody>
										</table>

									</td>
								</tr>
								<tr>
									<td align="center" valign="top" id="m_6276084880465470621templateBody" style="background:#ffffff none no-repeat center/cover;background-color:#ffffff;background-image:none;background-repeat:no-repeat;background-position:center;background-size:cover;border-top:0;border-bottom:0;padding-top:80px;padding-bottom:0">

										<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621templateContainer" style="border-collapse:collapse;max-width:600px!important">
											<tbody>
												<tr>
													<td valign="top" class="m_6276084880465470621bodyContainer">
														<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnTextBlock" style="min-width:100%;border-collapse:collapse">
															<tbody class="m_6276084880465470621mcnTextBlockOuter">
																<tr>
																	<td valign="top" class="m_6276084880465470621mcnTextBlockInner" style="padding-top:9px">

																		<a href="https://maps.google.com/?q=Dunois+%0D%0A+%0D%0A+%0D%0A%0970+rue+de+Dunois%0D%0A%09+%0D%0A%0975013+Paris&amp;entry=gmail&amp;source=g" data-saferedirecturl="https://www.google.com/url?q=https://maps.google.com/?q%3DDunois%2B%250D%250A%2B%250D%250A%2B%250D%250A%250970%2Brue%2Bde%2BDunois%250D%250A%2509%2B%250D%250A%250975013%2BParis%26entry%3Dgmail%26source%3Dg&amp;source=gmail&amp;ust=1524169316102000&amp;usg=AFQjCNGc0NDnafjMWex7JMpUbPnDLd4TJg">
																		</a>				<a href="https://maps.google.com/?q=Dunois+%0D%0A+%0D%0A+%0D%0A%0970+rue+de+Dunois%0D%0A%09+%0D%0A%0975013+Paris&amp;entry=gmail&amp;source=g" data-saferedirecturl="https://www.google.com/url?q=https://maps.google.com/?q%3DDunois%2B%250D%250A%2B%250D%250A%2B%250D%250A%250970%2Brue%2Bde%2BDunois%250D%250A%2509%2B%250D%250A%250975013%2BParis%26entry%3Dgmail%26source%3Dg&amp;source=gmail&amp;ust=1524169316102000&amp;usg=AFQjCNGc0NDnafjMWex7JMpUbPnDLd4TJg">
																		</a>                <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:390px;border-collapse:collapse" width="100%" class="m_6276084880465470621mcnTextContentContainer">
																			<tbody>
																				<tr>

																					<td valign="top" class="m_6276084880465470621mcnTextContent" style="padding:0px 18px 9px;color:#323232;word-break:break-word;font-family:Helvetica;font-size:18px;line-height:150%;text-align:center">

																						<p style="color:#323232;margin:10px 0;padding:0;font-family:Helvetica;font-size:18px;line-height:150%;text-align:center">
																							<a href="http://volley-ball.eu" style="color:#68b3c8;font-size:24px;font-family:arial,helvetica neue,helvetica,sans-serif;font-weight:normal;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://volley-ball.eu&amp;source=gmail&amp;ust=1524169316102000&amp;usg=AFQjCNHXUA5yv-kL0f_Rnf0RsoQvh0rN2w">
																								MATCH DUNOIS / LOGNES 2
																							</a>
																							<br>
																							<br>
																							<strong style="color:#808080;font-weight:bold">Gymnase <a href="https://maps.google.com/?q=Dunois+%0D%0A+%0D%0A+%0D%0A%0970+rue+de+Dunois%0D%0A%09+%0D%0A%0975013+Paris&amp;entry=gmail&amp;source=g" data-saferedirecturl="https://www.google.com/url?q=https://maps.google.com/?q%3DDunois%2B%250D%250A%2B%250D%250A%2B%250D%250A%250970%2Brue%2Bde%2BDunois%250D%250A%2509%2B%250D%250A%250975013%2BParis%26entry%3Dgmail%26source%3Dg&amp;source=gmail&amp;ust=1524169316102000&amp;usg=AFQjCNGc0NDnafjMWex7JMpUbPnDLd4TJg">Dunois</a>
																							</strong>
																							<br>
																							<a href="http://google.com" style="color:#000000;font-weight:normal;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://google.com&amp;source=gmail&amp;ust=1524169316102000&amp;usg=AFQjCNHJcelO0XNCep7pvQTTa2P6ITiHzg">
																								70 rue de Dunois
																								<br>
																								75013 Paris
																							</a>
																						</p>

																					</td>
																				</tr>
																			</tbody>
																		</table>



																		<table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:210px;border-collapse:collapse" width="100%" class="m_6276084880465470621mcnTextContentContainer">
																			<tbody>
																				<tr>

																					<td valign="top" class="m_6276084880465470621mcnTextContent" style="padding:0px 18px 9px;color:#323232;word-break:break-word;font-family:Helvetica;font-size:18px;line-height:150%;text-align:center">

																						<table border="0" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border:1px solid #cccccc;border-collapse:collapse" width="160">
																							<tbody>
																								<tr>
																									<td align="left" style="padding:5px" valign="top">
																										<table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
																											<tbody>
																												<tr>
																													<td align="center" style="background-color:#fd9f1b;color:#ffffff;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:bold;padding-top:10px;padding-bottom:10px;text-align:center" valign="top">September</td>
																												</tr>
																												<tr>
																													<td align="center" style="color:#000;font-family:Helvetica,Arial,sans-serif;font-size:16px;line-height:100%;padding-top:5px;padding-bottom:5px;text-align:center" valign="top">Lundi</td>
																												</tr>
																												<tr>
																													<td align="center" style="color:#fd9f1b;font-family:Helvetica,Arial,sans-serif;font-size:60px;font-weight:bold;line-height:100%;text-align:center" valign="top">16</td>
																												</tr>
																												<tr>
																													<td align="center" style="color:#000;font-family:Helvetica,Arial,sans-serif;font-size:16px;line-height:100%;padding-top:5px;padding-bottom:5px;text-align:center" valign="top">20:00</td>
																												</tr>
																											</tbody>
																										</table>
																									</td>
																								</tr>
																							</tbody>
																						</table>

																					</td>
																				</tr>
																			</tbody>
																		</table>



																	</td>
																</tr>
															</tbody>
														</table>
														<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnDividerBlock" style="min-width:100%;border-collapse:collapse;table-layout:fixed!important">
															<tbody class="m_6276084880465470621mcnDividerBlockOuter">
																<tr>
																	<td class="m_6276084880465470621mcnDividerBlockInner" style="min-width:100%;padding:40px 18px 0px">
																		<table class="m_6276084880465470621mcnDividerContent" border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
																			<tbody>
																				<tr>
																					<td>
																						<span>
																						</span>
																					</td>
																				</tr>
																			</tbody>
																		</table>

																	</td>
																</tr>
															</tbody>
														</table>
														<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnTextBlock" style="min-width:100%;border-collapse:collapse">
															<tbody class="m_6276084880465470621mcnTextBlockOuter">
																<tr>
																	<td valign="top" class="m_6276084880465470621mcnTextBlockInner" style="padding-top:9px">



																		<table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%" class="m_6276084880465470621mcnTextContentContainer">
																			<tbody>
																				<tr>

																					<td valign="top" class="m_6276084880465470621mcnTextContent" style="padding:0px 18px 9px;line-height:150%;word-break:break-word;color:#202020;font-family:Helvetica;font-size:18px;text-align:center">

																						<h3 style="text-align:center!important;display:block;margin:0;padding:0;color:#393939;font-family:Helvetica;font-size:20px;font-style:normal;font-weight:bold;line-height:125%;letter-spacing:normal">Votre disponibilité pour l'événement ?</h3>

																					</td>
																				</tr>
																			</tbody>
																		</table>



																	</td>
																</tr>
															</tbody>
														</table>
													</td>
												</tr>
											</tbody>
										</table>

									</td>
								</tr>
								<tr>
									<td align="center" valign="top" id="m_6276084880465470621templateUpperColumns" style="background:#ffffff none no-repeat center/cover;background-color:#ffffff;background-image:none;background-repeat:no-repeat;background-position:center;background-size:cover;border-top:0;border-bottom:0;padding-top:0;padding-bottom:80px">
										<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621templateContainer" style="border-collapse:collapse;max-width:600px!important">
											<tbody>
												<tr>
													<td valign="top">

														<table align="left" border="0" cellpadding="0" cellspacing="0" width="200" class="m_6276084880465470621columnWrapper" style="border-collapse:collapse">
															<tbody>
																<tr>
																	<td valign="top" class="m_6276084880465470621columnContainer">
																		<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnButtonBlock" style="min-width:100%;border-collapse:collapse">
																			<tbody class="m_6276084880465470621mcnButtonBlockOuter">
																				<tr>
																					<td style="padding-top:0;padding-right:18px;padding-bottom:18px;padding-left:18px" valign="top" align="center" class="m_6276084880465470621mcnButtonBlockInner">
																						<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnButtonContentContainer" style="border-collapse:separate!important;border-radius:3px;background-color:#d5e5a3">
																							<tbody>
																								<tr>
																									<td align="center" valign="middle" class="m_6276084880465470621mcnButtonContent" style="font-family:Arial;font-size:16px;padding:15px">
																										<a class="m_6276084880465470621mcnButton" title="Présent" style="font-weight:bold;letter-spacing:normal;line-height:100%;text-align:center;text-decoration:none;color:#ffffff;display:block">Présent</a>
																									</td>
																								</tr>
																							</tbody>
																						</table>
																					</td>
																				</tr>
																			</tbody>
																		</table>
																	</td>
																</tr>
															</tbody>
														</table>

														<table align="left" border="0" cellpadding="0" cellspacing="0" width="200" class="m_6276084880465470621columnWrapper" style="border-collapse:collapse">
															<tbody>
																<tr>
																	<td valign="top" class="m_6276084880465470621columnContainer">
																		<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnButtonBlock" style="min-width:100%;border-collapse:collapse">
																			<tbody class="m_6276084880465470621mcnButtonBlockOuter">
																				<tr>
																					<td style="padding-top:0;padding-right:18px;padding-bottom:18px;padding-left:18px" valign="top" align="center" class="m_6276084880465470621mcnButtonBlockInner">
																						<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnButtonContentContainer" style="border-collapse:separate!important;border-radius:3px;background-color:#ff8f5e">
																							<tbody>
																								<tr>
																									<td align="center" valign="middle" class="m_6276084880465470621mcnButtonContent" style="font-family:Arial;font-size:16px;padding:15px">
																										<a class="m_6276084880465470621mcnButton" title="Absent" style="font-weight:bold;letter-spacing:normal;line-height:100%;text-align:center;text-decoration:none;color:#ffffff;display:block">Absent</a>
																									</td>
																								</tr>
																							</tbody>
																						</table>
																					</td>
																				</tr>
																			</tbody>
																		</table>
																	</td>
																</tr>
															</tbody>
														</table>

														<table align="left" border="0" cellpadding="0" cellspacing="0" width="200" class="m_6276084880465470621columnWrapper" style="border-collapse:collapse">
															<tbody>
																<tr>
																	<td valign="top" class="m_6276084880465470621columnContainer">
																		<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnButtonBlock" style="min-width:100%;border-collapse:collapse">
																			<tbody class="m_6276084880465470621mcnButtonBlockOuter">
																				<tr>
																					<td style="padding-top:0;padding-right:18px;padding-bottom:18px;padding-left:18px" valign="top" align="center" class="m_6276084880465470621mcnButtonBlockInner">
																						<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnButtonContentContainer" style="border-collapse:separate!important;border-radius:3px;background-color:#b8d8d8">
																							<tbody>
																								<tr>
																									<td align="center" valign="middle" class="m_6276084880465470621mcnButtonContent" style="font-family:Arial;font-size:16px;padding:15px">
																										<a class="m_6276084880465470621mcnButton" title="Incertain" style="font-weight:bold;letter-spacing:normal;line-height:100%;text-align:center;text-decoration:none;color:#ffffff;display:block">Incertain</a>
																									</td>
																								</tr>
																							</tbody>
																						</table>
																					</td>
																				</tr>
																			</tbody>
																		</table>
																	</td>
																</tr>
															</tbody>
														</table>

													</td>
												</tr>
											</tbody>
										</table>
									</td>
								</tr>
								<tr>
									<td align="center" valign="top" id="m_6276084880465470621templateLowerColumns" style="background:#eeeeee none no-repeat center/cover;background-color:#eeeeee;background-image:none;background-repeat:no-repeat;background-position:center;background-size:cover;border-top:0;border-bottom:2px solid #eaeaea;padding-top:80px;padding-bottom:80px">
										<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621templateContainer" style="border-collapse:collapse;max-width:600px!important">
											<tbody>
												<tr>
													<td valign="top">

														<table align="left" border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621columnWrapper" style="border-collapse:collapse">
															<tbody>
																<tr>
																	<td valign="top" class="m_6276084880465470621columnContainer">
																	</td>
																</tr>
															</tbody>
														</table>

													</td>
												</tr>
											</tbody>
										</table>
									</td>
								</tr>
								<tr>
									<td align="center" valign="top" id="m_6276084880465470621templateFooter" style="background:#ffffff none no-repeat center/cover;background-color:#ffffff;background-image:none;background-repeat:no-repeat;background-position:center;background-size:cover;border-top:0;border-bottom:0;padding-top:80px;padding-bottom:80px">

										<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621templateContainer" style="border-collapse:collapse;max-width:600px!important">
											<tbody>
												<tr>
													<td valign="top" class="m_6276084880465470621footerContainer">
														<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnFollowBlock" style="min-width:100%;border-collapse:collapse">
															<tbody class="m_6276084880465470621mcnFollowBlockOuter">
																<tr>
																	<td align="center" valign="top" style="padding:9px" class="m_6276084880465470621mcnFollowBlockInner">
																		<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnFollowContentContainer" style="min-width:100%;border-collapse:collapse">
																			<tbody>
																				<tr>
																					<td align="center" style="padding-left:9px;padding-right:9px">
																						<table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse" class="m_6276084880465470621mcnFollowContent">
																							<tbody>
																								<tr>
																									<td align="center" valign="top" style="padding-top:9px;padding-right:9px;padding-left:9px">
																										<table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse">
																											<tbody>
																												<tr>
																													<td align="center" valign="top">





																														<table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse">
																															<tbody>
																																<tr>
																																	<td valign="top" style="padding-right:10px;padding-bottom:9px" class="m_6276084880465470621mcnFollowContentItemContainer">
																																		<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnFollowContentItem" style="border-collapse:collapse">
																																			<tbody>
																																				<tr>
																																					<td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px">
																																						<table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse">
																																							<tbody>
																																								<tr>

																																									<td align="center" valign="middle" width="24" class="m_6276084880465470621mcnFollowIconContent">
																																										<a href="http://www.facebook.com" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://www.facebook.com&amp;source=gmail&amp;ust=1524169316103000&amp;usg=AFQjCNEpkdESoTbC3rGJG_2YtCsCmN6fRA">
																																											<img src="https://ci5.googleusercontent.com/proxy/THEfQ-zOr2AaMLVp_TKYp66Poy4XIPQHLLPvp3JqaDTShBZ9oZafDmhUm7hfcJbSG9vWeV4d9Esrao80PBgUGiMiifS3Dl-CqVUBIY1Qj6oJicgM-Vrdv4BVqtr98zDVKOE=s0-d-e1-ft#https://cdn-images.mailchimp.com/icons/social-block-v2/color-facebook-48.png" style="display:block;border:0;height:auto;outline:none;text-decoration:none" height="24" width="24">
																																										</a>
																																									</td>


																																								</tr>
																																							</tbody>
																																						</table>
																																					</td>
																																				</tr>
																																			</tbody>
																																		</table>
																																	</td>
																																</tr>
																															</tbody>
																														</table>






																														<table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse">
																															<tbody>
																																<tr>
																																	<td valign="top" style="padding-right:10px;padding-bottom:9px" class="m_6276084880465470621mcnFollowContentItemContainer">
																																		<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnFollowContentItem" style="border-collapse:collapse">
																																			<tbody>
																																				<tr>
																																					<td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px">
																																						<table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse">
																																							<tbody>
																																								<tr>

																																									<td align="center" valign="middle" width="24" class="m_6276084880465470621mcnFollowIconContent">
																																										<a href="http://www.twitter.com/" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://www.twitter.com/&amp;source=gmail&amp;ust=1524169316103000&amp;usg=AFQjCNGBrRgQ7eXU3lgCNLc-E6TFAKoRcA">
																																											<img src="https://ci5.googleusercontent.com/proxy/7Mkp5x7vnjoGT2ynGuzF3bII8G8nN9AZ8P94lSQK9u1YI3mtO9W7FJ47IvEXf-miKSuDyVsogoi3lN_ByGUbmgjPGjx-metceXGhlGdxbwFiNbGKmwGCzURgcLUOD4kCIw=s0-d-e1-ft#https://cdn-images.mailchimp.com/icons/social-block-v2/color-twitter-48.png" style="display:block;border:0;height:auto;outline:none;text-decoration:none" height="24" width="24">
																																										</a>
																																									</td>


																																								</tr>
																																							</tbody>
																																						</table>
																																					</td>
																																				</tr>
																																			</tbody>
																																		</table>
																																	</td>
																																</tr>
																															</tbody>
																														</table>






																														<table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse">
																															<tbody>
																																<tr>
																																	<td valign="top" style="padding-right:0;padding-bottom:9px" class="m_6276084880465470621mcnFollowContentItemContainer">
																																		<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnFollowContentItem" style="border-collapse:collapse">
																																			<tbody>
																																				<tr>
																																					<td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px">
																																						<table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse">
																																							<tbody>
																																								<tr>

																																									<td align="center" valign="middle" width="24" class="m_6276084880465470621mcnFollowIconContent">
																																										<a href="http://www.yourwebsite.com" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://www.yourwebsite.com&amp;source=gmail&amp;ust=1524169316103000&amp;usg=AFQjCNGMn5rjNhmXrLsq8uhma5geKnPKVg">
																																											<img src="https://ci4.googleusercontent.com/proxy/XGenZrmUcdiVbGsrNYCRgHNYNfacIjhuLbFebzTFb_97r7SkYv7ogFxlEPf2hCuN5Kk9p8x-3_ifj6nSGicK0tVj4vtdS4rtGr6b05PDLfKpkMu-ZN-ze73H72HWQg=s0-d-e1-ft#https://cdn-images.mailchimp.com/icons/social-block-v2/color-link-48.png" style="display:block;border:0;height:auto;outline:none;text-decoration:none" height="24" width="24">
																																										</a>
																																									</td>


																																								</tr>
																																							</tbody>
																																						</table>
																																					</td>
																																				</tr>
																																			</tbody>
																																		</table>
																																	</td>
																																</tr>
																															</tbody>
																														</table>




																													</td>
																												</tr>
																											</tbody>
																										</table>
																									</td>
																								</tr>
																							</tbody>
																						</table>
																					</td>
																				</tr>
																			</tbody>
																		</table>

																	</td>
																</tr>
															</tbody>
														</table>
														<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnTextBlock" style="min-width:100%;border-collapse:collapse">
															<tbody class="m_6276084880465470621mcnTextBlockOuter">
																<tr>
																	<td valign="top" class="m_6276084880465470621mcnTextBlockInner" style="padding-top:9px">



																		<table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%" class="m_6276084880465470621mcnTextContentContainer">
																			<tbody>
																				<tr>

																					<td valign="top" class="m_6276084880465470621mcnTextContent" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#656565;font-family:Helvetica;font-size:12px;line-height:150%;text-align:left">

																						<p style="font-size:16px!important;text-align:center!important;margin:10px 0;padding:0;color:#656565;font-family:Helvetica;line-height:150%">Cet email a été généré et envoyé automatiquement.<br>
																							<u>Merci de ne pas y répondre.</u>
																						</p>

																					</td>
																				</tr>
																			</tbody>
																		</table>



																	</td>
																</tr>
															</tbody>
														</table>
													</td>
												</tr>
											</tbody>
										</table>

									</td>
								</tr>
							</tbody>
						</table>

					</td>
				</tr>
			</tbody>
		</table>
	</center>
</div>