<div style="height:100%;margin:0;padding:0;width:100%;background-color:#FFFFFF">
  <center>
    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="bodyTable" style="height:100%;border-collapse:collapse;margin:0;padding:0;width:100%;background-color:#FFFFFF">
      <tbody><tr>
        <td align="center" valign="top" id="bodyCell" style="height:100%;margin:0;padding:0;width:100%;border-top:0">
          
          <table border="0" cellpadding="0" cellspacing="0" width="100%" class="templateContainer" style="border-collapse:collapse;max-width:600px;border:0">
            <tbody><tr>
              <td align="center" background="<?= $baseUrl . '/img/volley-back.jpg'?>" valign="top" id="templateHeader">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                  <tbody><tr>
                    <td align="center" valign="top">
                      
                      <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                        <tbody><tr>
                          <td align="center" bgcolor="#63ABAF" style="background-color:#63abaf;color:#93d3d6;font-family:Helvetica;font-size:30px;font-style:normal;font-weight:bold;letter-spacing:normal;line-height:100%;padding-bottom:20px;text-align:center" valign="bottom" id="ribbon">
                              <a href="http://volley-ball.eu" style="text-decoration:none;color:#95d3d5" target="_blank">VB<br><span style="font-size:12px">.eu</span>
                            </a>
                          </td>
                          <td align="left" valign="bottom" class="headerContainer" style="padding-top:10px">
                            <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width:100%;border-collapse:collapse">
                              <tbody class="mcnTextBlockOuter">
                                <tr>
                                  <td valign="top" class="mcnTextBlockInner" style="padding-top:9px">
                                    <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%" class="mcnTextContentContainer">
                                      <tbody>
                                        <tr>
                                          <td valign="top" class="mcnTextContent" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#ddd;font-family:Helvetica;font-size:16px;font-style:normal;font-weight:bold;line-height:150%;letter-spacing:normal;text-align:left">
                                            <h2 style="color:#66abae;display:block;margin:0;padding:0;font-family:Helvetica;font-size:30px;font-style:normal;font-weight:bold;line-height:150%;letter-spacing:normal;text-align:left">Volley-ball.eu<br>Rejoignez l'aventure !</h2>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                        <tr>
                          <td align="left" bgcolor="#1E1D1A" valign="bottom" width="60" class="ribbon" style="background-color:rgba(0,0,0,.25)">
                            <img src="https://cdn-images.mailchimp.com/template_images/gallery/ribbon_bottom.png" height="35" width="60" style="display:block;max-width:100%;border:0;height:auto;outline:none;text-decoration:none" class="ribbonTail" alt="ribbon_bottom.png">
                          </td>
                          <td align="left">&nbsp;</td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td align="center" valign="top" id="templateUpperBody">
                    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                      <tbody><tr>
                        <td align="left" bgcolor="#1E1D1A" valign="middle" width="60" class="opaqueLayer" style="background-color:rgba(0,0,0,.25);padding-top:20px;padding-bottom:20px">
                          <img src="https://cdn-images.mailchimp.com/template_images/gallery/icon_info2.gif" height="25" width="60" style="display:block;max-width:100%;border:0;height:auto;outline:none;text-decoration:none" alt="icon_info2.gif">
                        </td>
                        <td align="left" valign="middle" class="upperBodyContainer">
                          <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width:100%;border-collapse:collapse">
                            <tbody class="mcnTextBlockOuter">
                              <tr>
                                <td valign="top" class="mcnTextBlockInner" style="padding-top:9px">
                                  <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%" class="mcnTextContentContainer">
                                    <tbody>
                                      <tr>
                                        <td valign="top" class="mcnTextContent" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#FFFFFF;font-family:Helvetica;font-size:18px;font-style:normal;font-weight:normal;line-height:150%;letter-spacing:normal;text-align:left">
                                          <h4 style="display:block;margin:0;padding:0;color:#FFFFFF;font-family:Helvetica;font-size:24px;font-style:normal;font-weight:bold;line-height:100%;letter-spacing:normal;text-align:left"><?= $group->name ?></h4><br>
                                          <p>volley-ball.eu est un site de gestion d'entrainement et de match pour des équipes de volley. </p>
                                            <p>
                                            Vous avez été invité à rejoindre le groupe de volley <?= $group->name ?>. Cette invitation a été envoyé par <?= $fullname ?>.
                                            </p>
                                        </td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </td>
              </tr>
              <tr>
                <td align="center" valign="top">
                  <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateLocation" style="border-collapse:collapse;background-color:rgba(100,172,176,.64)">
                    <tbody><tr>
                      <td align="left" bgcolor="#1E1D1A" valign="middle" width="60" class="opaqueLayer" style="background-color:rgba(0,0,0,.25);padding-top:20px;padding-bottom:20px">
                        <img src="https://ci3.googleusercontent.com/proxy/TZpOo-iT6qYbU4Oa0dUJv5Uzp8e5KFtxqoQPvqj6s15n9qkvajqkK6ryF5dRIwUk5BK5w60l-xc1QoZy4Il_BTHWYihGV7s-f8QieoHJARuZvxnUcZCMbMxdE0idSFEC=s0-d-e1-ft#https://cdn-images.mailchimp.com/template_images/gallery/icon_locator2.gif" height="26" width="60" style="display:block;max-width:100%;border:0;height:auto;outline:none;text-decoration:none" alt="icon_locator2.gif">
                      </td>
                      <td align="left" valign="middle" class="locationContainer">
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width:100%;border-collapse:collapse">
                          <tbody class="mcnTextBlockOuter">
                            <tr>
                              <td valign="top" class="mcnTextBlockInner" style="padding-top:9px">
                                <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%" class="mcnTextContentContainer">
                                  <tbody>
                                    <tr>
                                      <td valign="top" class="mcnTextContent" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#FEFCD2;font-family:Helvetica;font-size:16px;font-style:normal;font-weight:bold;line-height:150%;letter-spacing:normal;text-align:left">
                                        <a href="<?= $shareUrl ?>">Je souhaite rejoindre le groupe !</a>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            <tr>
              <td align="center" bgcolor="#49514B" valign="top">
                  <tr>
                    <td align="center" valign="top" id="templateLowerFooter">
                      <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                        <tbody><tr>
                          <td align="left" bgcolor="#1E1D1A" valign="middle" width="60" class="opaqueLayer" style="background-color:rgba(0,0,0,.25);padding-top:20px;padding-bottom:20px">
                            <img src="https://cdn-images.mailchimp.com/template_images/gallery/icon_contact2.gif" height="15" width="60" style="display:block;max-width:100%;border:0;height:auto;outline:none;text-decoration:none" alt="icon_contact2.gif">
                          </td>
                          <td align="left" valign="middle" class="lowerFooterContainer">
                            <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width:100%;border-collapse:collapse">
                              <tbody class="mcnTextBlockOuter">
                                <tr>
                                  <td valign="top" class="mcnTextBlockInner" style="padding-top:9px">
                                    <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%" class="mcnTextContentContainer">
                                      <tbody>
                                        <tr>
                                          <td valign="top" class="mcnTextContent" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#838176;font-family:Helvetica;font-size:12px;line-height:150%;text-align:left">
                                            <p style="margin:10px 0;padding:0;color:#838176;font-family:Helvetica;font-size:12px;line-height:150%;text-align:left">Cet email a été envoyé automatiquement, merci de ne pas y répondre.<br>
                                              <!-- <a href="#_" style="color:#838176;font-weight:normal;text-decoration:underline">Paramètres d'email</a> -->
                                            </p>
                                            contact : <a href="mailto:volley-ball.eu@gmail.com" target="_blank" style="font-family:Helvetica,sans-serif;font-size:14px;text-decoration:none;color:#64acb0;font-weight:normal;line-height:180%;text-align:left">volley-ball.eu@gmail.com</a> <br>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                      </tbody></table>
                    </td>
                  </tr>
                </tbody></table>
              </td>
            </tr>
          </tbody></table>
        </td>
      </tr>
    </tbody></table>
  </center>
</div>