<div style="height:100%;margin:0;padding:0;width:100%;background-color:#fff">
  <center>
    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="bodyTable" style="height:100%;border-collapse:collapse;margin:0;padding:0;width:100%;background-color:#fff">
      <tbody><tr>
        <td align="center" valign="top" id="bodyCell" style="height:100%;margin:0;padding:0;width:100%;border-top:0">
          
          <table border="0" cellpadding="0" cellspacing="0" width="100%" class="templateContainer" style="border-collapse:collapse;max-width:600px;border:0">
            <tbody><tr>
              <td align="center" background="https://ci6.googleusercontent.com/proxy/C32U5YtdXhBepEGb3i7StcHyD707uLXx1i3t6k_N1UEapqReRGYchbw9qClGZCa-VyHjomAQTwjWesy0Fea4jBMAoUVlb2okzh2hhVENPqtX2dI1_p4xdtYRBlQN26GomXCGAImidjiF59cNuSVevSfw7o4aevjYX1tIlBw=s0-d-e1-ft#https://gallery.mailchimp.com/c294e5e6fcd7996580bb94ded/images/0145f403-eca3-4a00-abf7-904371561369.jpg" valign="top" id="templateHeader">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                  <tbody><tr>
                    <td align="center" valign="top">
                      
                      <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                        <tbody><tr>
                          <td align="center" bgcolor="#63ABAF" style="background-color:#63abaf;color:#93d3d6;font-family:Helvetica;font-size:30px;font-style:normal;font-weight:bold;letter-spacing:normal;line-height:100%;padding-bottom:20px;text-align:center" valign="bottom" id="ribbon">
                            <a href="http://volley-ball.eu" style="text-decoration:none;color:#95d3d5" target="_blank">.eu</span>
                            </a>
                          </td>
                          <td align="left" valign="bottom" class="headerContainer" style="padding-top:10px">
                            <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width:100%;border-collapse:collapse">
                              <tbody class="mcnTextBlockOuter">
                                <tr>
                                  <td valign="top" class="mcnTextBlockInner" style="padding-top:9px">
                                    <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%" class="mcnTextContentContainer">
                                      <tbody>
                                        <tr>
                                          <td valign="top" class="mcnTextContent" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#ddd;font-family:Helvetica;font-size:16px;font-style:normal;font-weight:bold;line-height:150%;letter-spacing:normal;text-align:left">
                                            <h2 style="color:#66abae;display:block;margin:0;padding:0;font-family:Helvetica;font-size:30px;font-style:normal;font-weight:bold;line-height:150%;letter-spacing:normal;text-align:left">Entrainement Jeudi<br>Dunois REM</h2>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                        <tr>
                          <td align="left" bgcolor="#1E1D1A" valign="bottom" width="60" class="ribbon" style="background-color:rgba(0,0,0,.25)">
                            <img src="https://cdn-images.mailchimp.com/template_images/gallery/ribbon_bottom.png" height="35" width="60" style="display:block;max-width:100%;border:0;height:auto;outline:none;text-decoration:none" class="ribbonTail" alt="ribbon_bottom.png">
                          </td>
                          <td align="left">&nbsp;</td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td align="center" valign="top" id="templateUpperBody">
                    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                      <tbody><tr>
                        <td align="left" bgcolor="#1E1D1A" valign="middle" width="60" class="opaqueLayer" style="background-color:rgba(0,0,0,.25);padding-top:20px;padding-bottom:20px">
                          <img src="https://cdn-images.mailchimp.com/template_images/gallery/icon_clock2.gif" height="25" width="60" style="display:block;max-width:100%;border:0;height:auto;outline:none;text-decoration:none" alt="icon_clock2.gif">
                        </td>
                        <td align="left" valign="middle" class="upperBodyContainer">
                          <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width:100%;border-collapse:collapse">
                            <tbody class="mcnTextBlockOuter">
                              <tr>
                                <td valign="top" class="mcnTextBlockInner" style="padding-top:9px">
                                  <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%" class="mcnTextContentContainer">
                                    <tbody>
                                      <tr>
                                        <td valign="top" class="mcnTextContent" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#c2c2b4;font-family:Helvetica;font-size:18px;font-style:normal;font-weight:normal;line-height:150%;letter-spacing:normal;text-align:left">
                                          
                                          <h3 style="display:block;margin:0;padding:0;color:#ddd;font-family:Helvetica;font-size:14px;font-style:normal;font-weight:normal;line-height:100%;letter-spacing:normal;text-align:left;text-transform:uppercase">Thursday</h3>
                                          <h2 style="display:block;margin:0;padding:0;color:#ddd;font-family:Helvetica;font-size:30px;font-style:normal;font-weight:bold;line-height:150%;letter-spacing:normal;text-align:left">September 7, 2010 - 20h30</h2>
                                        </td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </td>
              </tr>
              <tr>
                <td align="center" valign="top">
                  <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateLocation" style="border-collapse:collapse;background-color:rgba(100,172,176,.64)">
                    <tbody><tr>
                      <td align="left" bgcolor="#1E1D1A" valign="middle" width="60" class="opaqueLayer" style="background-color:rgba(0,0,0,.25);padding-top:20px;padding-bottom:20px">
                        <img src="https://ci3.googleusercontent.com/proxy/TZpOo-iT6qYbU4Oa0dUJv5Uzp8e5KFtxqoQPvqj6s15n9qkvajqkK6ryF5dRIwUk5BK5w60l-xc1QoZy4Il_BTHWYihGV7s-f8QieoHJARuZvxnUcZCMbMxdE0idSFEC=s0-d-e1-ft#https://cdn-images.mailchimp.com/template_images/gallery/icon_locator2.gif" height="26" width="60" style="display:block;max-width:100%;border:0;height:auto;outline:none;text-decoration:none" alt="icon_locator2.gif">
                      </td>
                      <td align="left" valign="middle" class="locationContainer">
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width:100%;border-collapse:collapse">
                          <tbody class="mcnTextBlockOuter">
                            <tr>
                              <td valign="top" class="mcnTextBlockInner" style="padding-top:9px">
                                <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%" class="mcnTextContentContainer">
                                  <tbody>
                                    <tr>
                                      <td valign="top" class="mcnTextContent" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#ddd;font-family:Helvetica;font-size:16px;font-style:normal;font-weight:bold;line-height:150%;letter-spacing:normal;text-align:left">
                                        <h4 style="display:block;margin:0;padding:0;color:#ddd;font-family:Helvetica;font-size:24px;font-style:normal;font-weight:bold;line-height:100%;letter-spacing:normal;text-align:left">Gymnase Dunois</h4>
                                        <a href="https://maps.google.com/?q=70+rue+de+Dunois+%0D+75013+Paris&amp;entry=gmail&amp;source=g">
                                        75013 Paris</a>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            <tr>
              <td align="center" bgcolor="#49514B" valign="top">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateSocial" style="border-collapse:collapse;background-color:rgba(0,0,0,.20)">
                  <tbody><tr>
                    <td align="left" bgcolor="#2A2F2B" valign="middle" width="60" class="opaqueLayer" style="background-color:rgba(0,0,0,.25);padding-top:20px;padding-bottom:20px">
                      <img src="https://ci5.googleusercontent.com/proxy/HRJzTAS0A6ldv9VC_2ZvHmW44xndR-TAg8lmYAUekzo5ynR8Fz1Y39bzz9pk-M5NzZKKONEWfaC9iuyaG73n_geHVxX0n4hy7Vh1j6oc2OS6QFGnqwfPWD1VAPq5vA=s0-d-e1-ft#https://cdn-images.mailchimp.com/template_images/gallery/icon_share2.png" height="29" width="60" style="display:block;max-width:100%;border:0;height:auto;outline:none;text-decoration:none" alt="icon_share2.png">
                    </td>
                    <td align="left" valign="middle" class="socialContainer">
                      <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowBlock" style="min-width:100%;border-collapse:collapse">
                        <tbody class="mcnFollowBlockOuter">
                          <tr>
                            <td align="center" valign="top" style="padding:9px" class="mcnFollowBlockInner">
                              <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentContainer" style="min-width:100%;border-collapse:collapse">
                                <tbody>
                                  <tr>
                                    <td align="left" style="padding-left:9px;padding-right:9px">
                                      <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse" class="mcnFollowContent">
                                        <tbody>
                                          <tr>
                                            <td align="left" valign="top" style="padding-top:9px;padding-right:9px;padding-left:9px">
                                              <table align="left" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse">
                                                <tbody>
                                                  <tr>
                                                    <td align="left" valign="top">
                                                      <table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse">
                                                        <tbody>
                                                          <tr>
                                                            <td valign="top" style="padding-right:10px;padding-bottom:9px" class="mcnFollowContentItemContainer">
                                                              <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse:collapse">
                                                                <tbody>
                                                                  <tr>
                                                                    <td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px">
                                                                      <table align="left" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse">
                                                                        <tbody>
                                                                          <tr>
                                                                            <td align="center" valign="middle" width="24" class="mcnFollowIconContent">
                                                                              <a href="http://www.facebook.com" target="_blank">
                                                                                <img src="https://cdn-images.mailchimp.com/icons/social-block-v2/light-facebook-48.png" style="display:block;border:0;height:auto;outline:none;text-decoration:none" height="24" width="24" alt="light-facebook-48.png"></a>
                                                                              </td>
                                                                              <td align="left" valign="middle" class="mcnFollowTextContent" style="padding-left:5px">
                                                                                <a href="http://www.facebook.com" style="font-family:Helvetica,sans-serif;font-size:14px;text-decoration:none;color:#64acb0;font-weight:normal;line-height:180%;text-align:left" target="_blank">Présent</a>
                                                                              </td>
                                                                            </tr>
                                                                          </tbody>
                                                                        </table>
                                                                      </td>
                                                                    </tr>
                                                                  </tbody>
                                                                </table>
                                                              </td>
                                                            </tr>
                                                          </tbody>
                                                        </table>
                                                        <table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse">
                                                          <tbody>
                                                            <tr>
                                                              <td valign="top" style="padding-right:10px;padding-bottom:9px" class="mcnFollowContentItemContainer">
                                                                <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse:collapse">
                                                                  <tbody>
                                                                    <tr>
                                                                      <td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px">
                                                                        <table align="left" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse">
                                                                          <tbody>
                                                                            <tr>
                                                                              <td align="center" valign="middle" width="24" class="mcnFollowIconContent">
                                                                                <a href="http://www.twitter.com/" target="_blank">
                                                                                  <img src="https://cdn-images.mailchimp.com/icons/social-block-v2/light-twitter-48.png" style="display:block;border:0;height:auto;outline:none;text-decoration:none" height="24" width="24" alt="light-twitter-48.png"></a>
                                                                                </td>
                                                                                <td align="left" valign="middle" class="mcnFollowTextContent" style="padding-left:5px">
                                                                                  <a href="http://www.twitter.com/" style="font-family:Helvetica,sans-serif;font-size:14px;text-decoration:none;color:#64acb0;font-weight:normal;line-height:180%;text-align:left" target="_blank">Absent</a>
                                                                                </td>
                                                                              </tr>
                                                                            </tbody>
                                                                          </table>
                                                                        </td>
                                                                      </tr>
                                                                    </tbody>
                                                                  </table>
                                                                </td>
                                                              </tr>
                                                            </tbody>
                                                          </table>
                                                          <table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse">
                                                            <tbody>
                                                              <tr>
                                                                <td valign="top" style="padding-right:0;padding-bottom:9px" class="mcnFollowContentItemContainer">
                                                                  <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse:collapse">
                                                                    <tbody>
                                                                      <tr>
                                                                        <td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px">
                                                                          <table align="left" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse">
                                                                            <tbody>
                                                                              <tr>
                                                                                <td align="center" valign="middle" width="24" class="mcnFollowIconContent">
                                                                                  <a href="http://www.instagram.com/" target="_blank">
                                                                                    <img src="https://ci4.googleusercontent.com/proxy/EdTPKl7_iK0bh0_3xZSRLGjKcjNJ5g4_q076LqwLvoTo36PV_pCmSrFbN1Kb_pmyBviArt8q_wluJJ_OfGH9kwMyOTTYzaNQ_eB-1gWbSlqfEcNtAyqwzZbHbq3fSrpCQFbi=s0-d-e1-ft#https://cdn-images.mailchimp.com/icons/social-block-v2/light-instagram-48.png" style="display:block;text-align:center;border:0;height:auto;outline:none;text-decoration:none" height="24" width="24" alt="light-instagram-48.png"></a>
                                                                                  </td>
                                                                                  <td align="left" valign="middle" class="mcnFollowTextContent" style="padding-left:5px">
                                                                                    <a href="http://www.instagram.com/" style="font-family:Helvetica,sans-serif;font-size:14px;text-decoration:none;color:#64acb0;font-weight:normal;line-height:180%;text-align:left" target="_blank">Incertain</a>
                                                                                  </td>
                                                                                </tr>
                                                                              </tbody>
                                                                            </table>
                                                                          </td>
                                                                        </tr>
                                                                      </tbody>
                                                                    </table>
                                                                  </td>
                                                                </tr>
                                                              </tbody>
                                                            </table>
                                                          </td>
                                                        </tr>
                                                      </tbody>
                                                    </table>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                      </tbody></table>
                    </td>
                  </tr>
                  <tr>
                    <td align="center" valign="top" id="templateLowerFooter">
                      <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                        <tbody><tr>
                          <td align="left" bgcolor="#1E1D1A" valign="middle" width="60" class="opaqueLayer" style="background-color:rgba(0,0,0,.25);padding-top:20px;padding-bottom:20px">
                            <img src="https://cdn-images.mailchimp.com/template_images/gallery/icon_contact2.gif" height="15" width="60" style="display:block;max-width:100%;border:0;height:auto;outline:none;text-decoration:none" alt="icon_contact2.gif">
                          </td>
                          <td align="left" valign="middle" class="lowerFooterContainer">
                            <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width:100%;border-collapse:collapse">
                              <tbody class="mcnTextBlockOuter">
                                <tr>
                                  <td valign="top" class="mcnTextBlockInner" style="padding-top:9px">
                                    <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%" class="mcnTextContentContainer">
                                      <tbody>
                                        <tr>
                                          <td valign="top" class="mcnTextContent" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#838176;font-family:Helvetica;font-size:12px;line-height:150%;text-align:left">
                                            <p style="margin:10px 0;padding:0;color:#838176;font-family:Helvetica;font-size:12px;line-height:150%;text-align:left">Cet email a été envoyé automatiquement, merci de ne pas y répondre.<br><a href="#_" style="color:#838176;font-weight:normal;text-decoration:underline">Paramètres d\'email</a>
                                            </p>
                                            contact : <a href="mailto:volley-ball.eu@gmail.com" target="_blank">volley-ball.eu@gmail.com</a> <br>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                      </tbody></table>
                    </td>
                  </tr>
                </tbody></table>
              </td>
            </tr>
          </tbody></table>
        </td>
      </tr>
    </tbody></table>
  </center>
</div>