<div style="height:100%;margin:0;padding:0;width:100%;background-color:#47433b">
  <center>
    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="bodyTable" style="height:100%;border-collapse:collapse;margin:0;padding:0;width:100%;background-color:#47433b">
      <tbody><tr>
        <td align="center" valign="top" id="bodyCell" style="height:100%;margin:0;padding:0;width:100%;border-top:0">
          
          <table border="0" cellpadding="0" cellspacing="0" width="100%" class="templateContainer" style="border-collapse:collapse;max-width:600px;border:0">
            <tbody><tr>
              <td align="center" background="https://gallery.mailchimp.com/c294e5e6fcd7996580bb94ded/images/0145f403-eca3-4a00-abf7-904371561369.jpg" valign="top" id="templateHeader">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                  <tbody><tr>
                    <td align="center" valign="top">
                      
                      <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                        <tbody><tr>
                          <td align="center" bgcolor="#63ABAF" style="background-color:#63abaf;color:#93d3d6;font-family:Helvetica;font-size:30px;font-style:normal;font-weight:bold;letter-spacing:normal;line-height:100%;padding-bottom:20px;text-align:center" valign="bottom" id="ribbon">
                              <a href="http://volley-ball.eu" style="text-decoration:none;color:#95d3d5" target="_blank">VB<br><span style="font-size:12px">.eu</span>
                            </a>
                          </td>
                          <td align="left" valign="bottom" class="headerContainer" style="padding-top:10px">
                            <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width:100%;border-collapse:collapse">
                              <tbody class="mcnTextBlockOuter">
                                <tr>
                                  <td valign="top" class="mcnTextBlockInner" style="padding-top:9px">
                                    <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%" class="mcnTextContentContainer">
                                      <tbody>
                                        <tr>
                                          <td valign="top" class="mcnTextContent" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#ddd;font-family:Helvetica;font-size:16px;font-style:normal;font-weight:bold;line-height:150%;letter-spacing:normal;text-align:left">
                                            <h2 style="color:#66abae;display:block;margin:0;padding:0;font-family:Helvetica;font-size:30px;font-style:normal;font-weight:bold;line-height:150%;letter-spacing:normal;text-align:left">Volley-ball.eu</h2>
                                            <h4 style="color:#66abae;display:block;margin:0;padding:0;font-family:Helvetica;font-size:20px;font-style:normal;font-weight:bold;line-height:100%;letter-spacing:normal;text-align:left">Mot de passe oublié</h4>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                        <tr>
                          <td align="left" bgcolor="#1E1D1A" valign="bottom" width="60" class="ribbon" style="background-color:rgba(0,0,0,.25)">
                            <img src="https://cdn-images.mailchimp.com/template_images/gallery/ribbon_bottom.png" height="35" width="60" style="display:block;max-width:100%;border:0;height:auto;outline:none;text-decoration:none" class="ribbonTail" alt="ribbon_bottom.png">
                          </td>
                          <td align="left">&nbsp;</td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td align="center" valign="top" id="templateUpperBody">
                    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                      <tbody><tr>
                        <td align="left" bgcolor="#1E1D1A" valign="middle" width="60" class="opaqueLayer" style="background-color:rgba(0,0,0,.25);padding-top:20px;padding-bottom:20px">
                          
                        </td>
                        <td align="left" valign="middle" class="upperBodyContainer">
                          <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width:100%;border-collapse:collapse">
                            <tbody class="mcnTextBlockOuter">
                              <tr>
                                <td valign="top" class="mcnTextBlockInner" style="padding-top:9px">
                                  <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%" class="mcnTextContentContainer">
                                    <tbody>
                                      <tr>
                                        <td valign="top" class="mcnTextContent" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#c2c2b4;font-family:Helvetica;font-size:18px;font-style:normal;font-weight:normal;line-height:150%;letter-spacing:normal;text-align:left">
                                          
                                          <h3 style="display:block;margin:0;padding:0;color:#FEFCD2;font-family:Helvetica;font-size:14px;font-style:normal;font-weight:normal;line-height:100%;letter-spacing:normal;text-align:left;text-transform:uppercase">Réinitialisation du mot de passe</h3>
                                        </td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </td>
              </tr>
              <tr>
                <td align="center" valign="top" id="templateLowerBody" style="background-color:#47433b">
                  <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                    <tbody>
                      <tr>
                        <td align="left" bgcolor="#34312B" valign="top" width="60" class="opaqueLayer" style="background-color:rgba(0,0,0,.25);padding-top:20px;padding-bottom:20px">
                          <img src="https://cdn-images.mailchimp.com/template_images/gallery/icon_info2.gif" height="24" width="60" style="display:block;max-width:100%;border:0;height:auto;outline:none;text-decoration:none">
                        </td>
                        <td align="left" valign="middle" class="lowerBodyContainer" style="padding-top:10px;padding-bottom:10px">
                          <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width:100%;border-collapse:collapse">
                            <tbody class="mcnTextBlockOuter">
                              <tr>
                                <td valign="top" class="mcnTextBlockInner" style="padding-top:9px">
                                  <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%" class="mcnTextContentContainer">
                                    <tbody>
                                      <tr>
                                        <td valign="top" class="mcnTextContent" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#c2c2b4;font-family:Helvetica;font-size:14px;font-style:normal;font-weight:normal;line-height:150%;letter-spacing:normal;text-align:left">
                                          Une demande a été faite pour un changement de mot de passe concernant votre adresse email. Si vous n'êtes pas l'auteur de cette demande, merci d'ignorer cet email.<br><br>

                                          <table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse">
                                            <tbody>
                                              <tr>
                                                <td valign="top" style="padding-right:0;padding-bottom:9px" class="mcnFollowContentItemContainer">
                                                  <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse:collapse">
                                                    <tbody>
                                                      <tr>
                                                        <td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px">
                                                          <table align="left" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse">
                                                            <tbody>
                                                              <tr>
                                                                <td align="center" valign="middle" width="24" class="mcnFollowIconContent">
                                                                  <a href="<?= $url ?>" target="_blank">
                                                                    <img src="<?= $baseUrl . '/img/lock.png'?>" style="display:block;text-align:center;border:0;height:auto;outline:none;text-decoration:none" height="24" width="24"></a>
                                                                  </td>
                                                                  <td align="left" valign="middle" class="mcnFollowTextContent" style="padding-left:5px">
                                                                    <a href="<?= $url ?>" style="font-family:Helvetica,sans-serif;font-size:14px;text-decoration:none;color:#64acb0;font-weight:normal;line-height:180%;text-align:left" target="_blank">Réinitialiser !</a>
                                                                  </td>
                                                                </tr>
                                                              </tbody>
                                                            </table>
                                                          </td>
                                                        </tr>
                                                      </tbody>
                                                    </table>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                        </td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                  </tbody>
                </table>
                </td>
              </tr>
                  <tr>
                    <td align="center" valign="top" id="templateLowerFooter">
                      <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                        <tbody><tr>
                          <td align="left" bgcolor="#1E1D1A" valign="middle" width="60" class="opaqueLayer" style="background-color:rgba(0,0,0,.25);padding-top:20px;padding-bottom:20px">
                            <img src="https://cdn-images.mailchimp.com/template_images/gallery/icon_contact2.gif" height="15" width="60" style="display:block;max-width:100%;border:0;height:auto;outline:none;text-decoration:none" alt="icon_contact2.gif">
                          </td>
                          <td align="left" valign="middle" class="lowerFooterContainer">
                            <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width:100%;border-collapse:collapse">
                              <tbody class="mcnTextBlockOuter">
                                <tr>
                                  <td valign="top" class="mcnTextBlockInner" style="padding-top:9px">
                                    <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%" class="mcnTextContentContainer">
                                      <tbody>
                                        <tr>
                                          <td valign="top" class="mcnTextContent" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#838176;font-family:Helvetica;font-size:12px;line-height:150%;text-align:left">
                                            <p style="margin:10px 0;padding:0;color:#838176;font-family:Helvetica;font-size:12px;line-height:150%;text-align:left">Cet email a été envoyé automatiquement, merci de ne pas y répondre.<br>
                                              <!-- <a href="#_" style="color:#838176;font-weight:normal;text-decoration:underline">Paramètres d'email</a> -->
                                            </p>
                                            contact : <a href="mailto:volley-ball.eu@gmail.com" target="_blank" style="font-family:Helvetica,sans-serif;font-size:14px;text-decoration:none;color:#64acb0;font-weight:normal;line-height:180%;text-align:left">volley-ball.eu@gmail.com</a> <br>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                      </tbody></table>
                    </td>
                  </tr>
                </tbody></table>
              </td>
            </tr>
          </tbody></table>
        </td>
      </tr>
    </tbody></table>
  </center>
</div>