<div class="row">
    <div class="col-md-12">
        <div class="card card-calendar">
            <div class="card-content">
                <div id="fullCalendar"></div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <?php foreach ($events as $event): ?>
        <div class="col-lg-4 col-md-6">
            <?= $this->partial('partial/event.phtml', $event) ?>
        </div>
    <?php endforeach ?>
</div>

<div id="fullCalModal" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span> <span class="sr-only">close</span></button>
                <h4 id="modalTitle" class="modal-title">- Dunois REM</h4>
            </div>
            <div id="modalBody" class="modal-body">
                <h5 id="modalDate">Mardi 20/08/17 à 20h00</h5>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>
                <hr>
                <div class="" data-buttons="4">
                    <a href="#" class="col-xs-4 text-center">
                        <i class="ti ti-check text-success" style="font-size: 40px;"></i>
                    </a>
                    <a href="#" class="col-xs-4 text-center">
                        <i class="ti ti-close text-danger" style="font-size: 40px;"></i>
                    </a>
                    <a href="#" class="col-xs-4 text-center">
                        <i class="ti ti-help text-warning" style="font-size: 40px;"></i>
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button class="btn btn-primary"><a id="eventUrl">Event Page</a></button>
            </div>
        </div>
    </div>
</div>