<div class="header header-filter" style="background-image: url('/img/bg-recep-ori.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="brand">
                    <h1>Volley-ball.eu</h1>
                    <h3>Gestion de groupes, entrainements, matchs.</h3>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="main main-raised">
    <div class="section section-basic">
        <div class="container text-center">
            <div class="row">
                <h2>Recherche</h2>
                <h4>Recherchez un groupe ou un évènement en particulier.</h4>
                <div class="form-group label-floating is-empty text-left">
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">search</i>
                        </span>
                        <label class="control-label" for="main-search">
                            Nom de groupe, match, évènement
                        </label>
                        <input type="text" id="main-search" name="main-search" class="form-control" required="required" value="" aria-required="true">
                    </div>
                    <span class="material-input"></span>
                </div>
            </div>
        </div>
    </div>

    <?php if ($this->user->display != Application\Model\User::DISPLAY_TABLE): ?>
        <div class="section section-tabs">
            <div class="container">
                <div class="row text-center">
                    <h2>Vos évènements à venir</h2>
                    <div class="checkbox col-xs-12 text-center">
                        <?php foreach ($groups as $group): ?>
                            <label class="checkbox-inline">
                                <input type="checkbox" name="groups" class="group-filter" data-brand="<?= $group->brand ?>" checked="checked">
                                <?= $group->name ?>
                            </label>
                        <?php endforeach ?>
                    </div>
                    <?php if ($this->user->display == Application\Model\User::DISPLAY_LARGE): ?>
                        <div class="col-xs-12">
                            <?php foreach ($events as $event): ?>
                                <?php echo $this->partial('partial/events/extend.phtml', $event) ?>
                            <?php endforeach ?>
                        </div>
                    <?php else: ?>
                        <?php foreach ($events as $event): ?>
                            <?php echo $this->partial('partial/events/minimal.phtml', $event) ?>
                        <?php endforeach ?>
                    <?php endif ?>
                </div>
            </div>
        </div>
    <?php elseif ($this->user->display == Application\Model\User::DISPLAY_TABLE): ?>
        <div class="section section-tab">
            <div class="container">
                <div class="row text-center">

                    <h2>Vos évènements à venir</h2>
                    <div class="fresh-table">
                        <div class="toolbar"></div>
                        <table class="ftable table">
                            <thead>
                                <th data-field="name" data-sortable="true">Nom</th>
                                <th data-field="group" data-sortable="true">Groupe</th>
                                <th data-field="date" data-sortable="true">Date</th>
                                <th data-field="action" data-sortable="false" data-width="50px">Actions</th>
                            </thead>
                            <tbody>
                                <?php foreach ($events as $event): ?>
                                    <?php echo $this->partial('partial/events/table.phtml', $event) ?>
                                <?php endforeach ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    <?php endif ?>
</div>

<?php if ($this->user): ?>
    <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
        <a class="btn-floating btn-large red">
          <i class="large material-icons md-48">add</i>
        </a>
        <ul>
            <li>
                <span class="mobile-fab-tip">Créer un groupe</span>
                <a href="/group/create" class="btn-floating amber tooltipped" data-position="left" data-tooltip="Créer un groupe">
                    <i class="material-icons submenu">group_add</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Vue étendue</span>
                <a href="javascript:void();" class="btn-floating display blue tooltipped display" data-user="<?= $this->user->id ?>" data-display="<?= Application\Model\User::DISPLAY_LARGE ?>">
                    <i class="material-icons submenu">dashboard</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Vue minimale</span>
                <a href="javascript:void();" class="btn-floating display pink tooltipped display" data-user="<?= $this->user->id ?>" data-display="<?= Application\Model\User::DISPLAY_SMALL ?>">
                    <i class="material-icons submenu">view_module</i>
                </a>
            </li>
            <li>
                <span class="mobile-fab-tip">Vue tableau</span>
                <a href="javascript:void();" class="btn-floating display green tooltipped display" data-user="<?= $this->user->id ?>" data-display="<?= Application\Model\User::DISPLAY_TABLE ?>">
                    <i class="material-icons submenu">border_all</i>
                </a>
            </li>
        </ul>
    </div>
<?php endif ?>

<?php echo $this->partial('partial/signin.phtml') ?>
<?php echo $this->partial('partial/signup.phtml') ?>


