<div class="row">
    <div class="col-md-12">
        <div class="card card-calendar">
            <div class="card-content">
                <div id="fullCalendar">
                    <div id="full-calendar-loading" class="text-center col-xs-12">
                        <i class="fa fa-spinner fa-spin fa-4x"></i>
                        <h2>Chargement</h2>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="fullCalModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span> <span class="sr-only">close</span></button>
                <h4 id="modal-title" class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <div class="col-sm-3">
                    <div class="tab-pane active" id="date">
                        <div class="date-icon">
                            <em>Aout</em>
                            <strong>Jeudi</strong>
                            <span>31</span>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 text-center">
                    <h5 id="modal-place"></h5>
                    <span id="modal-address"></span><br>
                    <span id="modal-zipcode"></span> <span id="modal-city"></span>
                </div>
                <div class="col-sm-3">
                    <h2 class="text-center text-success"><span id="modal-count"></span> <i class="ti ti-check text-success"></i></h2>
                </div>
                <div class="clearfix"></div>
                <hr>
                <div class="col-sm-12" data-buttons="4">
                    <a id="event-url-ok" href="#" class="col-xs-3 text-center">
                        <i class="ti ti-check text-success" style="font-size: 30px;"></i>
                    </a>
                    <a id="event-url-no" href="#" class="col-xs-3 text-center">
                        <i class="ti ti-close text-danger" style="font-size: 30px;"></i>
                    </a>
                    <a id="event-url-incertain" href="#" class="col-xs-3 text-center">
                        <i class="ti ti-help text-warning" style="font-size: 30px;"></i>
                    </a>
                    <a id="event-url" href="#" class="col-xs-3 text-center">
                        <i class="ti ti-search text-info" style="font-size: 30px;"></i>
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>