<div class="header header-filter" style="background-image: url('/img/bg-recep-ori.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="brand">
                    <h1>Volley-ball.eu</h1>
                    <h3>Gestion de groupes, entrainements, matchs.</h3>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="main main-raised">
    <div class="section section-basic">
        <div class="container text-center">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <h2>Volley-ball.eu</h2>
                    <h4>La gestion d'entrainement, de match et de présence en toute simplicité!</h4>
                </div>
            </div>
        </div>
    </div>
    <div class="section section-basic">
        <div class="owl-carousel owl-theme">
            <div class="text-center item">
            </div>
        </div>
    </div>
    <div class="section section-tabs">
        <div class="container">
            <div class="row">
               <div class="col-md-4 col-sm-6">
                   <div class="card-container">
                       <div class="card">
                           <div class="front">
                               <div class="cover">
                                   <img src="/img/rotating_card_thumb2.png"/>
                               </div>
                               <div class="user card text-center">
                                   <div class="agenda">
                                       <div class="agenda-header">
                                           <b>Octobre</b>
                                       </div>
                                       <div class="agenda-content">
                                           <p>Jeudi</p>
                                           <p class="day">15<p>
                                       </div>
                                   </div>
                               </div>
                               <div class="content">
                                   <div class="main">
                                       <h3 class="name text-primary">Entrainement</h3>
                                       <p class="profession">Dunois</p>
                                       <p class="text-center">Le RDV est à <b>20h00</b></p>
                                       <p class="text-center">
                                           Gymnase Dunois<br/>
                                           70 rue de Dunois<br/>
                                           75013, Paris
                                       </p>
                                   </div>
                                   <div class="footer visible-xs visible-sm">
                                       <button class="btn btn-simple" onclick="rotateCard(this)">
                                           <i class="fa fa-mail-forward"></i> Rotation
                                       </button>
                                   </div>
                               </div>
                           </div> <!-- end front panel -->
                           <div class="back">
                               <div class="header header-primary">
                                   <h5 class="motto">Vous êtes noté <b>En Attente</b> à cet évènement</h5>
                               </div>
                               <div class="content">
                                   <div class="main">
                                       <h3 class="name">Entrainement</h3>
                                       <p class="profession">Dunois</p>
                                       <p class="text-center">
                                           <a href="javascript:void(0);"> <i class="material-icons">search</i>Voir les Détails</a>
                                       </p>
                                       <div class="stats-container">
                                           <div class="stats">
                                               <h4>7</h4>
                                               <a href="javascript:void(0);" class="text-success response">
                                                    Présent
                                               </a>
                                           </div>
                                           <div class="stats">
                                               <h4>2</h4>
                                               <a href="javascript:void(0);" class="text-danger response">
                                                	Absent
                                               </a>
                                           </div>
                                           <div class="stats">
                                               <h4>3</h4>
                                               <a href="javascript:void(0);" class="text-warning response">
                                                    Incertain
                                               </a>
                                           </div>
                                       </div>

                                   </div>
                                   <div class="text-center">
                                       <a href="https://www.google.fr/maps/search/70+rue+de+Dunois+75013+Paris"><i class="material-icons">place</i>Google Maps</a>
                                   </div>
                                   <div class="footer visible-xs visible-sm">
                                       <button class="btn btn-simple" onclick="rotateCard(this)">
                                           <i class="fa fa-mail-forward"></i> Retour
                                       </button>
                                   </div>
                               </div>
                           </div> <!-- end back panel -->
                       </div> <!-- end card -->
                   </div> <!-- end card-container -->
               </div> <!-- end col sm 3 -->
               <div class="col-md-8 col-sm-6">
                    <div class="card card-signup">
                        <div class="header header-primary text-center">
                            <h4>Évènements</h4>
                        </div>
                        <div class="content">
                            <div class="main">
                                <h3 class="name">Entrainement</h3>
                                <p class="profession">Dunois</p>
                                <p class="text-center">
                                    <a href="javascript:void(0);"> <i class="material-icons">search</i>Voir les Détails</a>
                                </p>
                                <div class="stats-container">
                                    <div class="stats">
                                        <h4>7</h4>
                                        <a href="javascript:void(0);" class="text-success response">
                                             Présent
                                        </a>
                                    </div>
                                    <div class="stats">
                                        <h4>2</h4>
                                        <a href="javascript:void(0);" class="text-danger response">
                                            Absent
                                        </a>
                                    </div>
                                    <div class="stats">
                                        <h4>3</h4>
                                        <a href="javascript:void(0);" class="text-warning response">
                                             Incertain
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
               </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->partial('partial/signin.phtml') ?>
<?php echo $this->partial('partial/signup.phtml') ?>


